### ISSUE TITLE
New names for tide level variables

### ISSUE THREAD

**Issue by marceloandrioni** [cf-convention/discuss#10]
Hello, as of v69 of the Standard Names Table, there are two variables for tide level with different reference levels:
```
tidal_sea_surface_height_above_lowest_astronomical_tide
tidal_sea_surface_height_above_mean_sea_level
```
But as shown in the following table from [“Shoreline Management Guidelines”. DHI Water and Environment](https://www.dhigroup.com/marine-water/ebook-shoreline-management-guidelines)  (page 73/462) there are a lot of other reference levels that can be used:

![tide_levels](https://user-images.githubusercontent.com/13545615/70172429-681c6280-16af-11ea-9ad6-6316b0e660f5.png)

Currently, only LAT and MSL exist, so I would like to suggest the inclusion of another variable based in an also much-used reference level (MLWS - Mean Low Water Springs):
```
tidal_sea_surface_height_above_mean_low_water_springs
```
It would be great to receive feedback from "shallow water people" if someone else works with other reference levels and would also need more standard_names for tides.

Thank you.

**Comment by roy-lowry** [comment]
@marceloandrioni Standard Names have always been managed on an 'as needed' basis rather than covering every foreseeable use case because resources are finite. As you have a requirement for adding MLWS then I see no problem - it is a straightforward modification to the existing Names. If there are other specific requests from people wanting to put data relative to other references into CF then these could be also be added.

**Comment by marceloandrioni** [comment]
Hello @roy-lowry, you are right, if all the "possible" names were to be included the list would be endless. So my suggestion is only:
```
tidal_sea_surface_height_above_mean_low_water_springs
```
with a possible explanation:

> "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean low water springs" describes a local vertical reference based on the time mean of the low water levels during spring tides expected to occur under average meteorological conditions and under any combination of astronomical conditions. The tidal component of sea surface height describes the predicted variability of the sea surface due to astronomic forcing (chiefly lunar and solar cycles) and shallow water resonance of tidal components; for example as generated based on harmonic analysis, or resulting from the application of harmonic tidal series as boundary conditions to a numerical tidal model.

Thank you.

**Comment by feggleton** [comment]
Hi @marceloandrioni, thank you for your proposal and to @roy-lowry for his comments. I agree with Roy that this term looks fairly straight forward as it is just another reference level for similar existing names. The unit would be 'm' as with the other terms I assume. All the phrases from the existing names have been added into the descriptions and so this seems fine. I don't know much about this topic and so I am unsure about the sentence describing 'mean low water springs' unfortunately. As this has been open for a while and little other discussion has been posted I would like to propose we give people a few more days but if everyone is in agreement then we can accept this term for the next publication. I'll check back on Monday.

Fran

**Comment by marceloandrioni** [comment]
Hi @feggleton, thank you for your reply. I forgot to write it down but the unit is meters as you said.
One suggestion to clarify a little the explanation would be to include "(corresponding to New Moon and Full Moon periods)" after the spring tides reference, as opposed to "neap tides (corresponding to First Quarter and Third Quarter Moon periods)":

> "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean low water springs" describes a local vertical reference based on the time mean of the low water levels during spring tides (corresponding to New Moon and Full Moon periods) expected to occur under average meteorological conditions and under any combination of astronomical conditions. The tidal component of sea surface height describes the predicted variability of the sea surface due to astronomic forcing (chiefly lunar and solar cycles) and shallow water resonance of tidal components; for example as generated based on harmonic analysis, or resulting from the application of harmonic tidal series as boundary conditions to a numerical tidal model.

Thank you.

**Comment by roy-lowry** [comment]
@feggleton You're right - units are m.

**Comment by roy-lowry** [comment]
@marceloandrioni I think adding the concept of neaps is unnecessarily confusion .  If you want to clarify the meaning of springs how about:

"Mean low water springs" describes a local vertical reference based on the time mean of the low water levels during spring tides (the tides each lunar month with the greatest difference between high and low water that follow full and new moons) expected to occur under average meteorological conditions and under any combination of astronomical conditions.

**Comment by roy-lowry** [comment]
@marceloandrioni Reading again I see you didn't intend the reference to neaps to be in the definition. Apologies for misunderstanding. However, I still feel my explanation of springs does a little more to explain what they are. 

My version of the complete definition would be:

"Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean low water springs" describes a local vertical reference based on the time mean of the low water levels during spring tides (the tides each lunar month with the greatest difference between high and low water that follow full and new moons) expected to occur under average meteorological conditions and under any combination of astronomical conditions. The tidal component of sea surface height describes the predicted variability of the sea surface due to astronomic forcing (chiefly lunar and solar cycles) and shallow water resonance of tidal components; for example as generated based on harmonic analysis, or resulting from the application of harmonic tidal series as boundary conditions to a numerical tidal model.

Is that OK?

**Comment by marceloandrioni** [comment]
Hi @roy-lowry, I agree that your version with the "spring tides (the tides each lunar month with the greatest difference between high and low water that follow full and new moons)" is better. My only suggestion would be to replace the "that follow full and new moons" by "that happen during full and new moons phases". To me, as a non-native english speaker, the "follow" bit can maybe imply that the spring tides happen after the full/new moons and not during it.
But whatever you and @feggleton decide is Ok for me.

Thank you.

**Comment by roy-lowry** [comment]
@marceloandrioni You'r right.'follow' is open to misinterpretation, so that is better.

**Comment by feggleton** [comment]
Thank you for further comments and clarification. As there has been no further discussion and you have both agreed, I think this term can now be accepted for publication.

Thanks,

Fran

**Comment by feggleton** [comment]
This name is accepted for publication in the standard name table and will be added in the next update on 3rd February.

**Comment by marceloandrioni** [comment]
Okay, thank you very much @feggleton.

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
