### ISSUE TITLE
 Standard names: improved permafrost characterization

### ISSUE THREAD

**Issue by nicholas512** [cf-convention/discuss#106]
The following terms are related to the characterization of permafrost; we aim to adopt them within the NSERC PermafrostNet research network as a means to promote data interoperability. We foresee applications both for the publication of observational data in an interoperable way, and for land surface models that increasingly take permafrost into consideration.

**Proposer's name** Nick Brown & Michel Paquette (@MichelPqt)
**Date**  2021-05-04

**Term**: mass_fraction_of_gravel_in_soil
**Description**: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.
**Units**: 1

**Term**: mass_fraction_of_sand_in_soil
**Description**: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.
**Units**: 1

**Term**: mass_fraction_of_silt_in_soil
**Description**: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.
**Units**: 1

**Term**: mass_fraction_of_clay_in_soil
**Description**: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.
**Units**: 1

**Term**: mass_fraction_of_organic_matter_in_soil
**Description**: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction
**Units**: 1

**Term**: frozen_ground_thermal_conductivity
**Description**: Thermal conductivity is the constant k in the formula q = -k grad T where q is the heat transfer per unit time per unit area of a surface normal to the direction of transfer and grad T is the temperature gradient. Thermal conductivity is a property of the material.
**Units**: W m-1 K-1

**Term**: frozen_ground_thermal_capacity
**Description**: Thermal capacity, or heat capacity, is the amount of heat energy required to increase the temperature of 1 kg of material by 1 K. It is a property of the material. 
**Units**: J kg-1 K-1

**Term**: soil_water_ph
**Description**: soil_water_ph is the measure of acidity of soil moisture, defined as the negative logarithm of the concentration of dissolved hydrogen ions in soil water.
**Units**: 1

**Term**: volume_ratio_of_ice_to_ground_pores
**Alias**: ice_saturation_index
**Description**: "Ratio_of_X_to_Y" means X/Y. Ground pores is the volume of the porosity of the ground under natural, unfrozen conditions. 
**Units**: 1

**Term**: volume_fraction_of_excess_ice_in_the_ground
**Alias**: excess ice
**Description**:  "Volume fraction" is used in the construction "volume_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the volume of X divided by the volume of Y (including X).The phrase “excess_ice” means the volume of ice in the ground which exceeds the total volume of the saturated ground under thawed conditions.
**Units**: 1
**Source**: https://nrc-publications.canada.ca/eng/view/ft/?id=69fb8993-1baa-4225-b33a-6a02341d383d
https://doi.org/10.1002/ppp.458

**Term**: depth_of_surface_thaw_in_permafrost
**Definition**: depth_of_surface_thaw is the instantaneous depth of the downward penetration of thaw from the ground surface at a given time. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more consecutive years. The maximum measurable depth_of_surface_thaw_in_permafrost value as recorded at the end of a thawing season corresponds to the permafrost_active_layer_thickness
**Units**: m

On the use of term “ground”: We note that existing terms use either “soil”, “bedrock”, or more recently, “solid_earth_subsurface”. For our applications, “soil” is too specific (we measure these properties beyond where plants sink their roots) and “solid_earth_subsurface” includes soil and bedrock, but is limited by the notion of a material defined as “solid earth”.  As an example typical of permafrost applications, beds of massive ice several meters thick or  layers of buried vegetation do not intuitively fit the definition of “solid earth” whereas in natural language, “ground” incorporates all soil phases and components including air, water, sediment or rock, and organic matter, and could be the preferred terminology.

**Comment by JonathanGregory** [comment]
Dear Nick

Thanks for your proposals. It will be good to make standard names more appealing to permafrost experts. Here are some comments.

`mass_fraction_of_`X`_in_soil` is fine, following other patterns, and all the X are present in existing names except `gravel`.

`frozen_ground_thermal_capacity` is like the existing `soil_thermal_capacity`, but we also have `specific_heat_capacity_of_sea_water`, which has the same canonical units (J kg-1 K-1). I would say that the latter is the common physical term for this quantity, so I would suggest your name should be `specific_heat_capacity_of_frozen_ground`, and we should make `soil_thermal_capacity` an alias of `specific_heat_capacity_of_soil`. Maybe `thermal_conductivity_of_frozen_ground` would also be a bit clearer? There are no existing thermal conductivity names except for soil.

Does `volume_ratio_of_ice_to_ground_pores` mean the fraction of the volume which is pores, and that these pores are entirely filled with ice? If so, could it be called `volume_ratio_of_pores_in_ground`, or `volume_ratio_of_ice_in_ground`?

Reading the description of `volume_fraction_of_excess_ice_in_the_ground` and the subsequent discussion of `ground`, I realise I am not sure what you actually mean by it. I think it might be `solid_earth_subsurface`, which you mention, and is used in one existing name to mean the solid (whatever it is) underneath the snow, seasonal ice or permanent ice, whose definition explicitly states that `solid_earth_subsurface` includes permafrost. But you also say, "Beds of massive ice several meters thick or layers of buried vegetation do not intuitively fit the definition of solid earth." Maybe they don't in general, but they do in the context of that existing standard name (if the vegetation is a compact solid, I suppose). Would it be bad? What do you mean by "beds of massive ice"? Is that *pure* ice? If so, is it permafrost? Isn't permanent ice on the surface an incipient ice-cap? Maybe you mean a pingo?

Best wishes

Jonathan

**Comment by MichelPqt** [comment]
Hi Jonathan,

Thank you for commenting on this issue.

About `volume_fraction_of_ice_to_ground_pores`, in permafrost the volume of ice can largely exceed pore saturation, and this ratio is basically an ice saturation index which helps determine whether excess ice is present or not. In this sense, it is different from a `volume_ratio_of_pores_in_ground` (since it can exceed the volume of pores). In the case of `volume_ratio_of_ice_in_ground`, this would be the volume of ice / volume of ground, which is not typically measured in permafrost studies (Volumetric ice content is widely used, as the `volume_fraction_of_frozen_water_in_soil`).

The discussion on `ground` vs `solid_earth` is important. `solid_earth` seemed to have appeared during a [previous discussion](https://github.com/cf-convention/discuss/issues/48) to replace "soil", yet its use over `ground` (which was also suggested) wasn't discussed. `ground` is much more inclusive, because by definition it includes everything below the surface. In the case of beds of massive ice, we are talking about deep and thick, sometimes almost pure ice formations within permafrost, where ice is the principal component of the ground. A pingo typically contains such ice, but so does many other frost mounds, and this can also be buried glacial ice, buried sea / lake ice, or ice wedges. In addition, permafrost often forms in peatlands, where the ground is composed of vegetation and ice only (for [example](https://www.sciencedirect.com/science/article/pii/S0033589496918694)). In all cases, these material, and especially the high frozen water component fit poorly the concept of the rarely used `solid_earth`. They could be considered as `solid_earth` if we insist on using the term, but it would have to be better defined as an alias for `ground`, and not simply the "solid" portion of the ground. You also noted that there are uses of `soil` that would require a duplicate term to account for the `ground` or the `solid_earth` (`volume_fraction_of_frozen_water_in_soil`, `specific_heat_capacity_of_soil`, etc.). Since for now `solid_earth` is only used once in the convention, and is rarely used in the general literature, we figured it would be a good time to discuss its meaning and usage, and potentially replacing it with the widely used and accepted `ground`.

Regards,

Michel

**Comment by nicholas512** [comment]
Thanks Jonathan for the quick reply.  A few comments to supplement what Michel has said:

* `frozen_ground_thermal_capacity` vs `specific_heat_capacity_of_frozen_ground`  and `frozen_ground_thermal_conductivity` vs `thermal_conductivity_of_frozen_ground`.  I don't see a problem with using the terms you suggested. As you pointed out, we based these off the relevant terms for soil, but if the soil ones are going to change too then all the more reason to go with the `standard_name_of_X` form. This also lends itself nicely to e.g. `volumetric_heat_capacity_of_frozen_ground` which is also common.
*  Regarding `volume_fraction_of_excess_ice_in_the_ground`, this term measures how much more ice there is in the ground than would otherwise be possible if it were water, given the total pore space. By way of example: if a 1m column of ground with 25% excess ice were to thaw completely, one would be left with 0.25m of water atop a 0.75m column of 100% saturated "ground" (ignoring runoff).


Finally, it may be worthwhile to note that the thermal properties of `frozen_ground` are sometimes used as counterparts to those same thermal properties of `thawed ground` (e.g. frozen (&lambda;<sub>f</sub>) and thawed (&lambda;<sub>t</sub>) thermal conductivities in [Nicolsky et al. (2007)](https://tc.copernicus.org/articles/1/41/2007/tc-1-41-2007.pdf).

**Comment by JonathanGregory** [comment]
Dear Michel and Nick

Thanks for your replies. Rereading https://github.com/cf-convention/discuss/issues/48 I see that `solid_earth` was prefixed to `solid_earth_subsurface` in order to distinguish it from the sea, where `subsurface` is also used. Although that proposal started with `ground`, this seems to have been forgotten in the discussion of the distinction between surface and subsurface temperature. There are quite a few existing standard names containing `ground_level`, and also `wrt_ground`, `grounded_ice`, and `groundwater`, but not `ground` by itself as a medium. I agree with you that "solid Earth subsurface" means "ground" as a medium, but maybe participants in that earlier discussion (e.g. @taylor13 @awi-gamma @roy-lowry) can remember if there was a reason against it. Otherwise I would favour renaming `solid_earth_subsurface_temperature` as `temperature_in_ground`, like `temperature_in_surface_snow`.

Apart from the question of "ground", I found the two names about volume of ice hard to interpret, so thanks for your explanations. In order to make them more self-explanatory to a non-expert (I think, if I've understood them), would you consider `ratio_of_ice_volume_in_frozen_ground_to_pore_volume_in_unfrozen_ground` and `ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_ratio`? Other names use `unfrozen` or `expressed_as` (most of the latter are chemical names).

I realise I overlooked `depth_of_surface_thaw_in_permafrost` before. Since this instantaneous, could it not be called `freezing_level_depth_in_ground`?

Best wishes

Jonathan

**Comment by Polardan** [comment]
Hi Nick/Michel,

Regarding: depth_of_surface_thaw_in_permafrost.

Actually: The maximum measurable depth_of_surface_thaw_in_permafrost value as recorded **near** the end of a thawing season corresponds to the permafrost_active_layer_thickness.

Suggestion: change 'near' to 'at'

Cheers

**Comment by JonathanGregory** [comment]
Dear @nicholas512

> I think that `ratio_of_ice_volume_in_frozen_ground_to_pore_volume_in_unfrozen_ground` is suitable, provided that the alias `ice_saturation_index` is also available.

We introduce aliases to correct mistakes or change our mind while retaining backward-compatibility, not to provide synonyms. In cases like this, where there's a commonly used but less self-explanatory phrase, it's usual to mention it in the definition e.g. "This is often known as X". Then people will find it by searching the standard name table, if they include the help text in the search. Would that be OK?

> In `ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_ratio`, the denominator of the ratio is the volume of frozen ground, _not_ the pore volume.

I see, thanks. I misunderstood - an illustration of how careful and clear we have to be! How about `ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume`?

I appreciate your points regarding the thaw depth. This quantity seems similar to the existing `depth_at_shallowest_isotherm_defined_by_soil_temperature`. On the pattern, could we call it `depth_at_shallowest_freezing_isotherm_in_ground`?

By the way, do you need to name `ground_temperature`? You haven't requested it, but I suppose you wouldn't want to use the existing `soil_temperature`.

Best wishes

Jonathan

**Comment by MichelPqt** [comment]
Dear @JonathanGregory,

On the discussion surrounding `depth_of_surface_thaw_in_permafrost`, I think its important to avoid any reference to temperature or thermal conditions in the name. This is because ground often thaws while remaining cryotic (with temperature <0°C), due to salinity content or other factors. In many case, this measurement is performed by probing the ground, and therefore the thermal conditions are not as important as the phase of the ice cement / water in the ground. The use of `thaw` also relates to the dominant condition of the ground (frozen), which is affected by the passing warm conditions, and therefore thaws seasonally and briefly. Therefore, it is not a depth to an isotherm, rather a `surface_thickness_of_unfrozen_ground`, or `thickness_of_unfrozen_ground_from_the_surface`. I'm not sure these are well constructed, however.

Regards,

Michel

**Comment by JonathanGregory** [comment]
Dear @MichelPqt 

Ah, I see, thanks. Your suggestions make sense, but I'm slightly doubtful about whether `surface` might be confusing. What do you think of `thickness_of_unfrozen_ground_layer` or `depth_at_base_of_unfrozen_ground`? Since `depth` means a distance below the surface, the second is clearest in specifying that it refers to a layer which extends from the surface downwards.

Best wishes

Jonathan

**Comment by nicholas512** [comment]
@JonathanGregory 

Thanks for the clarification about aliases.
 
`ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume` : I think this is clear.  The definition will have to change to reflect the different name and to replace the alias information. Something along the lines of:

> ```ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume represents the fractional amount of "excess ice" in frozen ground. Excess ice is the volume of ice in the ground which exceeds the total pore volume that the ground would have under natural unfrozen conditions. Due to the presence of ground ice, the total water content of a frozen soil may exceed that corresponding to its normally consolidated state when unfrozen. As a result, upon thawing, a soil containing excess ice will settle under its own weight until it attains its consolidated state. Reference: van Everdingen, R. O. editor 1998: Multi-language glossary of permafrost and related ground ice terms. International Permafrost Association. ```

`ground_temperature`: In my opinion this would be a good term to have (or `temperature_in_ground` as you suggest above) for the reasons laid out by Michel. The reason we didn't propose it because of possible overlap with `solid_earth_subsurface_temperature`. However, if this is a case where renaming or adding an alias is appropriate I'd be happy to update the issue to include it.

**Comment by JonathanGregory** [comment]
Dear Nick @nicholas512

Sorry, of course - we've already discussed this. I'm still in favour of renaming `solid_earth_subsurface_temperature` as `temperature_in_ground` or `ground_temperature`, with `solid_earth_subsurface_temperature` becoming an alias. I hope others will comment who contributed to the earlier discussion.

Thanks

Jonathan

**Comment by MichelPqt** [comment]
Hi @JonathanGregory and @nicholas512,

Here's a recap of the discussion so far:

There was a compelling argument to rename `solid_earth_subsurface_temperature` to `temperature_in_ground`, since `ground` is more inclusive to a range of material and phases and more widely used than `solid_earth`.  `solid_earth_subsurface_temperature` would become an alias.


The submission `volume_fraction_of_excess_ice_in_the_ground`, was modified to:
`ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume`,
with the definition: 
`ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume` represents the fractional amount of "excess ice" in frozen ground. Excess ice is the volume of ice in the ground which exceeds the total pore volume that the ground would have under natural unfrozen conditions. Due to the presence of ground ice, the total water content of a frozen soil may exceed that corresponding to its normally consolidated state when unfrozen. As a result, upon thawing, a soil containing excess ice will settle under its own weight until it attains its consolidated state. Reference: van Everdingen, R. O. editor 1998: Multi-language glossary of permafrost and related ground ice terms. International Permafrost Association.


The submission: `volume_ratio_of_ice_to_ground_pores` should be modified to `ratio_of_ice_volume_in_frozen_ground_to_pore_volume_in_unfrozen_ground`. The description should be changed to: "Ratio_of_X_to_Y" means X/Y. Pore volume is the volume of the porosity of the ground under natural, unfrozen conditions. This is often known as "ice saturation index".
Units: 1


The submission `depth_of_surface_thaw_in_permafrost` was modified to `thickness_of_unfrozen_ground_layer` or `depth_at_base_of_unfrozen_ground`. Both seem fine to me, and @JonathanGregory suggested `depth_at_base_of_unfrozen_ground` should be preferred since `depth` already implies a dimension.
The definition would be:
Definition: `depth_at_base_of_unfrozen_ground` is the instantaneous depth of the downward penetration of thaw from the ground surface at a given time. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more consecutive years. The maximum measurable `depth_at_base_of_unfrozen_ground` value as recorded at the end of a thawing season corresponds to the permafrost_active_layer_thickness.
Units: m


The submissions `frozen_ground_thermal_conductivity `and `frozen_ground_thermal_capacity` should be changed to `thermal_conductivity_of_frozen_ground` and `specific_heat_capacity_of_frozen_ground`, with the following descriptions:

Description: Thermal conductivity is the constant k in the formula q = -k grad T where q is the heat transfer per unit time per unit area of a surface normal to the direction of transfer and grad T is the temperature gradient. Thermal conductivity is a property of the material.
Units: W m-1 K-1

Term: `specific_heat_capacity_of_frozen_ground`
Description: Thermal capacity, or heat capacity, is the amount of heat energy required to increase the temperature of 1 kg of material by 1 K. It is a property of the material.
Units: J kg-1 K-1


The following submissions seemed fine, but I received comments that asked for the grain-size scale to be divulged in the description:

Term: mass_fraction_of_gravel_in_soil
Description: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale
Units: 1

Term: mass_fraction_of_sand_in_soil
Description: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale
Units: 1

Term: mass_fraction_of_silt_in_soil
Description: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale
Units: 1

Term: mass_fraction_of_clay_in_soil
Description: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale
Units: 1

Term: mass_fraction_of_organic_matter_in_soil
Description: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction
Units: 1

Term: soil_water_ph
Description: soil_water_ph is the measure of acidity of soil moisture, defined as the negative logarithm of the concentration of dissolved hydrogen ions in soil water.
Units: 1


I think this sums it up, anything else to add?

Cheers,

Michel

**Comment by feggleton** [comment]
Hi all,

Thank you for this proposal. I think I have managed to get all the terms and the changes into the cfeditor correctly. I will clarify all below. Please let me know if there are any parts I have got wrong or any more discussions to be had.

Changes to an existing name: solid_earth_subsurface_temperature

Term: temperature_in_ground
Definition: The quantity with standard name solid_earth_subsurface_temperature is the temperature at any depth (or in a layer) of the "solid" earth, excluding surficial snow and ice (but not permafrost or soil). For temperatures in surface lying snow and ice, the more specific standard names temperature_in_surface_snow and land_ice_temperature should be used. For temperatures measured or modelled specifically in the soil layer (the near-surface layer where plants sink their roots) the standard name soil_temperature should be used.

Changes need to be made to the definition which I don't think is just a case of switching the name in the first sentence. Do we need to remove the term 'solid earth' if we are now referring to 'ground'?

This term is also referred to in one name which might need to be changed:

soil_temperature
Soil temperature is the bulk temperature of the soil, not the surface (skin) temperature. "Soil" means the near-surface layer where plants sink their roots. For subsurface temperatures that extend beneath the soil layer or in areas where there is no surface soil layer, the standard name solid_earth_subsurface_temperature should be used.

Other terms include:

Term:ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume
Definition:ice_volume_in_frozen_ground_in_excess_of_pore_volume_in_unfrozen_ground_expressed_as_fraction_of_frozen_ground_volume represents the fractional amount of "excess ice" in frozen ground. Excess ice is the volume of ice in the ground which exceeds the total pore volume that the ground would have under natural unfrozen conditions. Due to the presence of ground ice, the total water content of a frozen soil may exceed that corresponding to its normally consolidated state when unfrozen. As a result, upon thawing, a soil containing excess ice will settle under its own weight until it attains its consolidated state. Reference: van Everdingen, R. O. editor 1998: Multi-language glossary of permafrost and related ground ice terms. International Permafrost Association.

Term:ratio_of_ice_volume_in_frozen_ground_to_pore_volume_in_unfrozen_ground
Definition:The phrase "ratio_of_X_to_Y" means X/Y. "X_volume" means the volume occupied by X within the grid cell. Pore volume is the volume of the porosity of the ground under natural, unfrozen conditions. This is often known as "ice saturation index".

Term:depth_at_base_of_unfrozen_ground
Definition:The phrase depth_at_base_of_unfrozen_ground is the instantaneous depth of the downward penetration of thaw from the ground surface at a given time. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more consecutive years. The maximum measurable depth_at_base_of_unfrozen_ground value as recorded at the end of a thawing season corresponds to the permafrost_active_layer_thickness.

Term:thermal_conductivity_of_frozen_ground 
Definition:Thermal conductivity is the constant k in the formula q = -k grad T where q is the heat transfer per unit time per unit area of a surface normal to the direction of transfer and grad T is the temperature gradient. Thermal conductivity is a property of the material.

Term:specific_heat_capacity_of_frozen_ground
Definition:Thermal capacity, or heat capacity, is the amount of heat energy required to increase the temperature of 1 kg of material by 1 K. It is a property of the material.

Term:mass_fraction_of_gravel_in_soil
Definition:"Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale.

Term:mass_fraction_of_sand_in_soil
Definition:"Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale.

Term:mass_fraction_of_silt_in_soil
Definition:"Mass fraction" is used in the construction "mass_fraction_of_X_in_Y'', where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale.

Term:mass_fraction_of_clay_in_soil
Definition:"Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Grain-size class distribution is based on the Udden-Wentworth scale.

Term:mass_fraction_of_organic_matter_in_soil
Definition: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It is evaluated as the mass of X divided by the mass of Y (including X). It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.

Term:soil_water_ph
Definition:soil_water_ph is the measure of acidity of soil moisture, defined as the negative logarithm of the concentration of dissolved hydrogen ions in soil water.

**Comment by MichelPqt** [comment]
Hi Francesca,

Thank you for your edits. I think you're right that we should remove the reference to solid_earth_subsurface_temperature from the soil_temperature definition, and replace it with temperature_in_ground. For the definition of temperature_in_ground, I would suggest the following change:

Term: temperature_in_ground
Definition: The temperature at any given depth (or in a layer) below the surface of the ground, excluding surficial snow and ice (but not permafrost or soil). For temperatures in surface lying snow and ice, the more specific standard names temperature_in_surface_snow and land_ice_temperature should be used. For temperatures measured or modelled specifically for the soil layer (the near-surface layer where plants sink their roots) the standard name soil_temperature should be used.

How does that sound to you @nicholas512 ?

MP

**Comment by nicholas512** [comment]
@MichelPqt @feggleton 
 This all looks good to me.  Good catch on the `soil_temperature` description.

**Comment by feggleton** [comment]
Thank you all. If there are no further comments in the next 7 days then these terms can be accepted.

**Comment by feggleton** [comment]
These terms have now been accepted.

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
