### ISSUE TITLE
 Standard names: particulate carbon terms

### ISSUE THREAD

**Issue by markusfiebig** [cf-convention/discuss#128]
**Proposer's name:** Markus Fiebig
**Date:** 2021-09-22

CEDA vocabulary editor [link](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=%23128&filter+and+display=Filter). Use this to see the current status of the names in the CF discussion process.

* **Term:** mass_concentration_of_elemental_carbon_in_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. Chemically, "elemental carbon" is the carbonaceous fraction of particulate matter that is thermally stable in an inert atmosphere to high temperatures near 4000K and can only be gasified by oxidation starting at temperatures above 340 C. It is assumed to be inert and non-volatile under atmospheric conditions and insoluble in any solvent (Ogren and Charlson, 1983). Elemental carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_elemental_carbon_in_pm1_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm1 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 1 micrometer. Chemically, "elemental carbon" is the carbonaceous fraction of particulate matter that is thermally stable in an inert atmosphere to high temperatures near 4000K and can only be gasified by oxidation starting at temperatures above 340 C. It is assumed to be inert and non-volatile under atmospheric conditions and insoluble in any solvent (Ogren and Charlson, 1983). Elemental carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_elemental_carbon_in_pm2p5_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm2p5 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 2.5 micrometers. Chemically, "elemental carbon" is the carbonaceous fraction of particulate matter that is thermally stable in an inert atmosphere to high temperatures near 4000K and can only be gasified by oxidation starting at temperatures above 340 C. It is assumed to be inert and non-volatile under atmospheric conditions and insoluble in any solvent (Ogren and Charlson, 1983). Elemental carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_elemental_carbon_in_pm10_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm10 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 10 micrometers. Chemically, "elemental carbon" is the carbonaceous fraction of particulate matter that is thermally stable in an inert atmosphere to high temperatures near 4000K and can only be gasified by oxidation starting at temperatures above 340 C. It is assumed to be inert and non-volatile under atmospheric conditions and insoluble in any solvent (Ogren and Charlson, 1983). Elemental carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_organic_carbon_in_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. Chemically, "organic carbon" refers to the carbonaceous fraction of particulate matter contained in any of the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl, etc. Organic carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_organic_carbon_in_pm1_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm1 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 1 micrometer. Chemically, "organic carbon" refers to the carbonaceous fraction of particulate matter contained in any of the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl, etc. Organic carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_organic_carbon_in_pm2p5_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm2p5 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 2.5 micrometers. Chemically, "organic carbon" refers to the carbonaceous fraction of particulate matter contained in any of the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl, etc. Organic carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_organic_carbon_in_pm10_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm10 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 10 micrometers. Chemically, "organic carbon" refers to the carbonaceous fraction of particulate matter contained in any of the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl, etc. Organic carbon may include inorganic carbon, which is operationally distributed between elemental and organic carbon.

* **Term:** mass_concentration_of_carbon_in_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. Chemically, "carbon" is the total sum of elemental, organic, and inorganic carbon. Inorganic carbon is operationally distributed between, i.e. aliased to, elemental and organic carbon.

* **Term:** mass_concentration_of_carbon_in_pm1_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm1 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 1 micrometer. Chemically, "carbon" is the total sum of elemental, organic, and inorganic carbon. Inorganic carbon is operationally distributed between, i.e. aliased to, elemental and organic carbon.

* **Term:** mass_concentration_of_carbon_in_pm2p5_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm2p5 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 2.5 micrometers. Chemically, "carbon" is the total sum of elemental, organic, and inorganic carbon. Inorganic carbon is operationally distributed between, i.e. aliased to, elemental and organic carbon.

* **Term:** mass_concentration_of_carbon_in_pm10_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm10 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 10 micrometers. Chemically, "carbon" is the total sum of elemental, organic, and inorganic carbon. Inorganic carbon is operationally distributed between, i.e. aliased to, elemental and organic carbon.

* **Term:** mass_concentration_of_absorption_equivalent_black_carbon_of_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. The absorption equivalent black carbon mass concentration is obtained by conversion from the particle light absorption coefficient with a suitable mass absorption cross-section.

* **Term:** mass_concentration_of_absorption_equivalent_black_carbon_of_pm1_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm1 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 1 micrometers. The absorption equivalent black carbon mass concentration is obtained by conversion from the particle light absorption coefficient with a suitable mass absorption cross-section.

* **Term:** mass_concentration_of_absorption_equivalent_black_carbon_of_pm2p5_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm2p5 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 2.5 micrometers. The absorption equivalent black carbon mass concentration is obtained by conversion from the particle light absorption coefficient with a suitable mass absorption cross-section.

* **Term:** mass_concentration_of_absorption_equivalent_black_carbon_of_pm10_dry_aerosol_particles_in_air
**Unit:** kg m-3
**Description:** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. Aerosol takes up ambient water (a process known as hygroscopic growth) depending on the relative humidity and the composition of the aerosol. "Dry aerosol particles" means aerosol particles without any water uptake. "Pm10 aerosol" means atmospheric particulate compounds with an aerodynamic diameter of less than or equal to 10 micrometers. The absorption equivalent black carbon mass concentration is obtained by conversion from the particle light absorption coefficient with a suitable mass absorption cross-section.

**Comment by JonathanGregory** [comment]
Dear @markusfiebig 

Thanks for your proposals here and in the other two issues. I am not an expert in the subject matter, but the constructions look fine to me. I have only one comment: in `total_carbon` I think `total` should be omitted, because in standard names the sum of everthing is implied if there is no qualification stated. I hadn't read of "equivalent black carbon" before, but I gather from Google that it is a well-known term. Nonetheless I wonder if it's possible to insert some extra adjective to indicate to the non-expert in what way it's "equivalent"? Not being an expert, my first guess was that it was some kind of chemical equivalent like we convey with `expressed_as`.

Best wishes

Jonathan

**Comment by markusfiebig** [comment]
> Dear @markusfiebig
> 
> Thanks for your proposals here and in the other two issues. I am not an expert in the subject matter, but the constructions look fine to me. I have only one comment: in `total_carbon` I think `total` should be omitted, because in standard names the sum of everthing is implied if there is no qualification stated. I hadn't read of "equivalent black carbon" before, but I gather from Google that it is a well-known term. Nonetheless I wonder if it's possible to insert some extra adjective to indicate to the non-expert in what way it's "equivalent"? Not being an expert, my first guess was that it was some kind of chemical equivalent like we convey with `expressed_as`.
> 
> Best wishes
> 
> Jonathan

Dear @JonathanGregory ,

apologies for replying late. 

To answer your second question first, the term  `equivalent black carbon` has been coined precisely to express its definition in only a few words, namely "obtained by conversion from the particle light absorption coefficient with a suitable mass absorption cross-section", i.e. assuming one fixed or a few fixed absorbing species in a fixed mass ratio. The term `equivalent` intends to sum up this whole definition. There is also a publication on this definition.

Also `total carbon` as used here is defined as the sum of organic and elemental carbon, but excludes for example carbon contained in carbonate minerals. so also this term is in fact a short hand of the stated definition.

All the best,
Markus

**Comment by markusfiebig** [comment]
Hi Jonathan,

thanks for your very thoughtful comments!

Concerning the question of the term "total", I took another round of discussion with my resident experts. The "total" in total carbon is in fact total, i.e. is used correctly, but consists in reality of elemental, organic, and inorganic carbon. Operationally, the inorganic carbon is distributed between / aliased to organic and elemental carbon. I'm well aware that this must sound messy to someone not working with these measurements, but it's as good as we can do it until we find a better method. These observations are widely used, they are a cornerstone of air quality networks in both Europe and North America. However, I updated the definition text of the concerned terms in order to clarify how the inorganic carbon is aliased to organic and elemental carbon. I also omitted the term "total".

The `equivalent black carbon` issue is more tricky. It not possible to say that we observe "the equivalent mass concentration of black carbon", because [black carbon can't be observed directly by definition](https://doi.org/10.5194/acp-13-8365-2013). Black carbon is defined by 5 characteristic properties, but there is no method that is sensitive to all these 5 properties at the same time. Thus, it is only possible to observe properties of black carbon, such as the absorption coefficient or the elemental carbon concentration. In this situation, the `equivalent black carbon` mass concentration is obtained from the absorption coefficient to imitate the elemental carbon concentration, but the 2 must not be confused.

Would it be ok to use "mass concentration of absorption equivalent black carbon" instead of "mass concentration of equivalent black carbon"?

Best regards,
Markus

**Comment by markusfiebig** [comment]
Hi @JonathanGregory ,

yes, omitting `total` is ok. I reworded the defintion slightly to clarify that the sum of carbon in all types of carbon components is meant. I also reworded the proposed names to "absorption equivalent ... of ...".

Do you think the names are now mature enough to be sent to Alison for the next release?

All the best,
Markus

**Comment by JonathanGregory** [comment]
Dear @markusfiebig 

Great, thanks. If no-one else has any comments, I agree that these proposals are ready for inclusion. I don't know what Alison's @japamment  schedule is for that, but I hope we will hear soon.

Jonathan

**Comment by japamment** [comment]
Dear @markusfiebig,

Apologies for the delay in responding to this issue.

The names are well constructed, the units are absolutely fine, and I can see that much of the text in the descriptions is consistent with existing names.

I have added this set of names to the [CEDA vocabulary editor](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=%23128&filter+and+display=Filter) which can be used to check on their status (currently marked as "under discussion"). Once the names are marked as "accepted" in the editor they will automatically be included in the next update to the standard name table. The next update is planned to take place on 16th/17th March. I have also added the editor link at the top of this issue so that you can find it again easily and see the progress of your names. I will shortly be adding similar links to the top of your other open issues so you can track those too.

Thank you for pointing us to your paper on the definitions and measurement methods for the various forms of carbonaceous aerosol. This is an extremely useful source and I think we should cite it in the descriptions of all the proposed names. This is evidently a complex subject. I am part way through reading the paper and would like to finish it before coming back with any further comments or questions.

I will get back to you later today - certainly it looks like we are close to agreement on these names.

Thank you for your patience.

Best wishes,
Alison

**Comment by japamment** [comment]
Dear @markusfiebig,

Having finished reading the paper, I am in agreement with the names as they appear in your updated proposals at the top of this issue. I do have some comments about the descriptions.

**Carbon names:**
I am happy with the sentence "Chemically, "carbon" is the total sum of elemental, organic, and inorganic carbon." However, 
I was confused by what is meant by the last sentence, "Inorganic carbon is operationally distributed between, i.e. aliased to, elemental and organic carbon." This is partly because at first I didn't understand what is meant by "operationally distributed". Also, I'd like to avoid using the word "aliased" because in standard names an "alias" means a deprecated version of a current standard name, which is clearly a different usage. Could we change the last sentence to say "In measurements of carbonaceous aerosols, inorganic carbon is neglected and its mass is assumed to be distributed between the elemental and organic carbon components of the aerosol particles." This is more verbose, but I hope a bit easier to understand for non-experts like myself.

**Elemental carbon names:**
Again, it was the last sentence in the descriptions that I found confusing. Could we change it to "In measurements of carbonaceous aerosols, elemental carbon samples may also include some inorganic carbon compounds, whose mass is
neglected and assumed to be distributed between the elemental and organic carbon components of the aerosol particles."

**Organic carbon names:**
We need to be careful with the wording of the organic carbon descriptions because we have existing standard names for "dissolved_organic_carbon" in sea water. The existing names are used for modelled variables and their descriptions say "Organic carbon describes a family of chemical species and is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute." Clearly dissolved_organic_carbon and organic_carbon in carbonaceous aerosol are very different quantities, and we need to keep the associated descriptions distinct. As with the carbon and elemental_carbon names, I would also like to modify the final
sentence in the descriptions. Putting all this together, I suggest the last two sentences of the organic carbon descriptions should be " Chemically, "organic carbon aerosol" refers to the carbonaceous fraction of particulate matter contained in any of the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl,
etc. In measurements of carbonaceous aerosols, organic carbon samples may also include some inorganic carbon compounds, whose mass is neglected and assumed to be distributed between the elemental and organic carbon components of the aerosol particles."

I like the description of organic carbon as "the vast number of compounds where carbon is chemically combined with hydrogen and other elements like O, S, N, P, Cl, etc.". I think we should add this text to the ocean name descriptions and I will open a separate issue to propose that.

**Black carbon names:**
The descriptions of these look fine as they are.

In addition to the above suggestions, I would like to add the following citation to the end of all the descriptions: "Reference: Petzold, A., Ogren, J. A., Fiebig, M., Laj, P., Li, S.-M., Baltensperger, U., Holzer-Popp, T., Kinne, S., Pappalardo, G., Sugimoto, N., Wehrli, C., Wiedensohler, A., and Zhang, X.-Y.: Recommendations for reporting "black carbon" measurements, Atmos. Chem. Phys., 13, 8365–8379, https://doi.org/10.5194/acp-13-8365-2013, 2013. "

As part of this discussion, I would like to review two existing black carbon names, atmosphere_absorption_optical_thickness_due_to_black_carbon_ambient_aerosol and atmosphere_optical_thickness_due_to_black_carbon_ambient_aerosol. If I have
understood your paper correctly, it is sensible to refer to black_carbon in these names since they refer only to optical properties and are not being interpreted as particulate mass. However, the descriptions contain no explanation of what  black carbon means in this context. Please could you suggest some suitable text?

Best wishes,
Alison

**Comment by feggleton** [comment]
Hi @markusfiebig, if you're able to respond to the above comments we can get a summary of the updated terms after this discussion and hopefully agree on these terms in time for the next update. Thanks

**Comment by efisher008** [comment]
Hello @markusfiebig,

I have now marked the standard names and their descriptions as written in my last message as accepted. Thanks again for your proposal and patience!

Best regards,
Ellie

**Comment by efisher008** [comment]
Closing this issue as the names were already published in version 80 of the standard names table.
