### ISSUE TITLE
New standard name number_concentration_of_biological_taxon_pollen_grains_in_air

### ISSUE THREAD

**Issue by atmodatcode** [cf-convention/discuss#144]
CEDA vocabulary editor [link ](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=144&filter+and+display=Filter). Use this to see the current status of the names in the CF discussion process.

Dear all, 

in July 21, I had submitted a proposal for a new standard name for airborne pollen concentrations to https://github.com/cf-convention/cf-conventions/issues/332 and it was subsequently accepted.  When submitting, I was unaware that https://github.com/cf-convention/discuss/issues (i.e. this GitHub repository) is the correct place to propose new standard names. 

I'm opening this issue to make sure that my proposed standard name will be included in the next CF standard name table while I'm referring to  https://github.com/cf-convention/cf-conventions/issues/332  for more details on my proposal. 

Thanks a lot!

Regards: Angelika

P.S: Anyone knows when the CF standard name table v79 will be released?

**Comment by feggleton** [comment]
Yes this proposal has already been through discussion and been accepted, I will post it here so it's easy for @japamment to add to the editor and she can advise about the next table update also. Thanks!

Proposer's name AtMoDat Project - Angelika Heil
Date 2021-07-23

Term: number_concentration_of_biological_taxon_pollen_grains_in_air
Description: "Number concentration" means the number of particles or other specified objects per unit volume. "Pollen grain" refers to the male gametophyte of seed plants (either angiosperms or gymnosperms). The number concentration of pollen grains refers to the number of individual pollen grains per unit volume. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.
Units: m-3

**Comment by japamment** [comment]
@atmodatcode,

My apologies, looking at this ticket and the discussion in the conventions repository [#332](https://github.com/cf-convention/cf-conventions/issues/332) I now realise that your proposal should have been included in the latest update to the standard name table. I have now marked it as "Accepted" in the [standard names editor](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=144&filter+and+display=Filter) so that it will automatically included in the next update. I will aim to do another update in April as their are quite a number of standard names in the pipeline.

Best wishes,
Alison

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
