### ISSUE TITLE
The 2022 CF meeting - Hackathon proposals

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#152]
Dear CF Community,

We are excited to solicit "Hackathon" proposals for the upcoming [2022 CF Conventions Workshop](https://github.com/cf-convention/discuss/issues/143) scheduled for 13-15 September, 2022 in Santander, Spain. We envision devoting some portion of each day to focused attention on high priority issues for CF. Hackathon sessions may be organized around new (without an associated GitHub issue) or existing topics. Suggestions will nominate a discussion leader, preferably someone attending the workshop in person, who will solicit in-person and on-line participation from a critical mass of individuals interested in making progress on the topic. Self-nominations are welcome!

We hope that the outcome of each hackathon will be:
* Progress on some new, neglected, or stymied issue of importance
* Exposure on how to write, edit, and review CF proposals
* More future contributors to CF
* To dispel any sense that the CF proposal-adoption cycle must be slow
* Stronger community spirit as we emerge from COVID isolation

Proposals can be short and informal. One or two paragraphs will suffice. Please attach your proposal to this announcement prior by **May 4, 2022** so the Workshop Organizing Committee can rank the proposals at its next meeting.

Sincerely,
The CF Workshop Organizing Committee.

**Comment by sadielbartholomew** [comment]
Hi all, here are a few of my own ideas, which can be taken forward or left depending on interest! I should add that I really like all of @erget's ideas as covered above, so really just want to provide some further options to diversify the possibilities.

For both of these, should either be chosen to go ahead with, I am happy to lead, but would be equally happy if someone else wanted to lead with them (volunteers can just shout here or in some other suitable location at any point).

# Automation of standard names countdown process

To make a start towards resolution of #88, which ultimately aims to create:

>  a tool to automate the management (time-tracking, repeated announcement, pausing etc.) of time periods initiated by lack of further comment on a given issue to propose a new standard name

and in particular see my new comment in that issue, https://github.com/cf-convention/discuss/issues/88#issuecomment-1110149596, where I suggest a tool (protobot) and highlight applications that already exist that were created using it which solve problems which are quite similar and which we can hopefully use as a means to get something (at least close to) working within the timescale of a Hackathon.


# Diagrams to summarise rules/processes for changes

See cf-convention/cf-convention.github.io#217 where I have outlined the idea in its own issue, because it might be thought of as a good thing to do whether or not we end up tackling it in the Hackathon. Ultimately concerns the presentation of information on the website, but the diagrams could be useful for potential incorporation into other resources, e.g. presentations and future training.

**Comment by czender** [comment]
Here is my idea for a followup of a breakout originally held at the CF 2021 Workshop:

NetCDF version 4.9.0 contains significantly more featureful support for compression, both lossless and lossy. Lossless compression filters present no outstanding issues for CF because they do not alter data, and have been widely used for years in large-scale projects such as CMIP. Lossy compression, however, does alter data and is increasingly viewed as an optimal choice to reduce storage requirements while preserving a desired level of information content. What roles can and should CF play in establishing metadata standards to encode the history and preserve the provenance of data transformation by lossy compression? Please join this hackathon/workgroup to discuss and draft metadata standards to facilitate the use and transparency of lossy compression in CF-compliant datasets.

**Comment by japamment** [comment]
Proposal from Gwen Moncoiffé (NOC/BODC) (@gwemon), Alexandra Kokkinaki (NOC/BODC) (@alko-k) and Alison Pamment (NCAS/CEDA).

We propose a hackathon session on mapping CF standard names to the Interoperability Framework developed by the Research Data Alliance I-ADOPT (InteroperAble Descriptions of Observable Property Terminologies) Working Group https://doi.org/10.15497/RDA00071. The work of I-ADOPT was described at the CF 2021 meeting and the “Advancing CF Conventions for NetCDF” session of the 2021 AGU Fall meeting and the framework is now ready to be implemented in the NERC Vocabulary Server. Mapping standard names to the Interoperability Framework will enable the discovery of equivalent terms in other vocabularies like, e.g., the BODC Parameter Usage Vocabulary, and broaden the discovery of comparable datasets. The hackathon would be used to show some examples of mappings already created and work together on some further examples.

**Comment by ngalbraith** [comment]
> 

I see that the I-ADOPT proposal is listed on the CF meeting registration page. Can someone provide a link to more info on this project?  Google isn't helping for some reason; the I-ADOPT area on github isn't helping much either.

**Comment by rmendels** [comment]
Hi Nan:

Did you do a search on the full name?  One link for example is:

https://rd-alliance.org/group/interoperable-descriptions-observable-property-terminology-wg-i-adopt-wg/outcomes

HTH,

-Roy

> On Aug 13, 2022, at 1:06 PM, Nan Galbraith ***@***.***> wrote:
> 
> 
> I see that the I-ADOPT proposal is listed on the CF meeting registration page. Can someone provide a link to more info on this project? Google isn't helping for some reason; the I-ADOPT area on github isn't helping much either.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: ***@***.*** www: https://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by davidhassell** [comment]
The [workshop agenda](http://cfconventions.org/Meetings/2022-Workshop.html) has been updated with the I-ADOPT link. Thanks.

**Comment by davidhassell** [comment]
The [meeting agenda](http://cfconventions.org/Meetings/2022-Workshop.html) has now been updated with I-ADOPT link https://zenodo.org/record/6520132  - thanks for pointing this out.

**Comment by jypeter** [comment]
I'm not sure I'll be able to attend a _hackaton_ remotely, but I have some suggestions that some people can possibly discuss. Maybe in _Housecleaning_?

There are **32 mentions of software** on the https://cfconventions.org/ site, like:
- _enables software tools to display data and perform operations on specified subsets of the data with minimal user intervention_ **and** _write software that allows a machine to parse that metadata and to automatically associate each data value with its location in time and space_ (in [1.1 Goals](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_goals))
- _helps software developers to design CF-compliant data-processing applications_ (in [Appendix 1](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#appendix-CF-data-model))

But **there is no mention of actual software that can be used to usefully work with CF**. 

There is **one** mention of Python (in the last reference of the [References](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_references) at the very end of the page), and a few references of `udunits` and `Proj`, but there are not exactly for end users

I have just found the [Software that “Understands” CF Data](https://cfconventions.org/software.html) page. This is accessible from the [CF convention home page](https://cfconventions.org/), but is **not referenced in the [NetCDF Climate and Forecast (CF) Metadata Conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html) page itself**

Maybe an appendix listing/advertising the software packages that can handle/understand at least part of CF and that can be easily used by end users would be too long, but there should be an easy way to find the [Software that “Understands” CF Data](https://cfconventions.org/software.html) page from the convention document

Also, the potentially very useful software page seems to be **out of date and missing packages**. I'm a long time user of the awesome `PCMDI's cdms2` (initially developed by Bob Drach, the "D" in "GDT convention"), other people use `(py)Ferret`, maybe there are some `R` packages that can help 

Note that there is some work to try replace the python `cdms2` package with an [xCDAT extension of xarray](https://xcdat.readthedocs.io/en/latest/) (ping @tomvothecoder @durack1)

Also, Housecleaning should **include a reference to the original "GDT convention"** and a link to the document. I was not able to find the document on Google, and I have sent a mail to Karl Taylor and Jonathan Gregory asking if they had it somewhere

**Comment by JonathanGregory** [comment]
Dear @jypeter et al.

Thanks for raising this point. If we made explicit mentions of or links to CF webpages in the CF standards document, it would require more maintenance to keep the document and the website consistent. Also, it's harder and slower to update the document than the website. However, I appreciate that people who have the standards document as a PDF or as a URL may not be aware of the website. Therefore I would suggest instead that we insert a statement something like this near the start of the CF document:

Please see the CF website at `cfconventions.org` for previous versions of the conventions, the standard name table, forums for questions and proposals about the conventions, a list of software for working with CF, and other resources.

Would that meet the need?

Cheers

Jonathan

**Comment by jypeter** [comment]
Well, as long as there is an easy-to-find reference in the "CF document" to a place where people can find CF aware software (and the other resources you mention), this would work for me! Maybe several references, because you never know what string people are going to look for in a document

Also, having a link to the CF website near the top of the CF document would solve what I noticed earlier today: there is no convenient way to navigate from the document (back) to the website, unless you go to the URL field in your browser and remove `Data/cf-conventions/cf-conventions-1.9/cf-conventions.html` from https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html

Actually, there is a [kind of logo](https://cfconventions.org/Data/media/images/logo.png) on the home page, and I was trying to find it at the top of the document, in order to click on it and go back to the home page. Maybe having a logo with a link in the document would help

**Comment by ethanrd** [comment]
I like the idea of adding to the Housekeeping hackathon list an item to work on updating the CF software web page (as suggested  by @jypeter above). I've created an issue (cf-convention/cf-convention.github.io#241) to start gathering ideas for the CF software web page.

**Comment by taylor13** [comment]
Just a reminder that another web "navigational" issue that still needs addressing was raised in https://github.com/cf-convention/cf-convention.github.io/issues/191 .  Should this be added to some "list of things to do" along with items above?

**Comment by JonathanGregory** [comment]
Dear Karl

Following your comment about https://github.com/cf-convention/cf-convention.github.io/issues/191, I have added to that issue. What do you think of what I wrote? I agree, we should resolve it.

Best wishes

Jonathan

**Comment by JonathanGregory** [comment]
I believe that all of the above proposals have been considered and implemented or are the subject of other issues, so I am closing this now. If that's wrong, please open new issues as appropriate addressing individual proposals. Thanks.
