### ISSUE TITLE
Standard names: temperature_of_solar_panel_back

### ISSUE THREAD

**Issue by agraillet** [cf-convention/discuss#157]
**Proposer's name**
Alexandre Graillet from ENERGY-lab

**Background**
Our research laboratory is a member of the BSRN network and has a large network of ground-based solar metrology stations. For several years now, we have been working to respect a FAIR-type data management strategy, which is based in particular on compliance with CF conventions. We are aware and very grateful for the work you are doing and have a few questions.

We collect measurements from the SUV5 radiometer which can measure UV-radiation of extended spectra of radiation as from solar radiation and incandescent lamps with the overall spectral range is 280 to 400 nm.
In practice, we use the standard_name `solar_irradiance` to qualify this measurement. **Is there metadata to specify the spectral range 280 to 400 nm (UV-A/UV-B range)?**

In addition, our stations are self-powered, in particular with solar panels and we have installed a thermocouple located on the rear surface of the solar panel.
This measurement is very useful for solarists because temperature has an effect the efficiency and maximum pv output of a solar panel. The hotter a panel gets, the less power it generates. The ambient temperature, temperature coefficient of the actual panel and the type of installation are all factors that affect the yield potential of a solar power system.
We have not found a suitable standard name and suggest the following standard name: `temperature_of_solar_panel_back`.

**Comment by JonathanGregory** [comment]
Dear Alexandre @agraillet

To specify the spectral range, you can give the data variable a size-one coordinate variable or a scalar coordinate variable, with standard name of `radiation_wavelength`, and record 280 nm and 400 nm as the bounds of this coordinate variable. The value of the single coordinate is nominal. It's usual to choose a value within the range, probably the middle of it, as a representative coordinate.

CF standard names are mostly for geophysical quantities which might be compared among datasets; some of them are for metadata related to those quantities. If the temperature at the back of a solar panel is a quantity which is specific to a piece of equipment rather than concerned with an environmental quantity, I'm not sure it can have a standard name. I wonder what other people think about this.

You could give it a `long_name`, of course, since they are not standardised. If it is a measurement of air temperature, its standard name could be `air_temperature`, with a `long_name` or `comment` describing it further.

Best wishes

Jonathan

**Comment by feggleton** [comment]
I would agree that this wouldn't be a typical standard name in CF due to the reasons Jonathan has given. My first thought was to use one of the existing temperature names as there are many describing different things but it depends if it is the air temperature above or the temperature of that surface. I looked at surface temperature but this refers to the lower boundary of the atmosphere.
