### ISSUE TITLE
 New standard_name: atmosphere_mass_content_of_rain

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#17]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20

**- Term** atmosphere_mass_content_of_rain
**- Definition** "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. "Rain" refers to the precipitating part of liquid water in the atmosphere – the cloud liquid water is excluded. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used.
**- Units** kg m-2

This proposal belongs to http://cfeditor.ceda.ac.uk/proposal/4296 which was discussed earlier via the mailing list and lead to the standard_name given above.

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for this proposal. Looking back at the mailing list discussion, I think we had all agreed on the name atmosphere_mass_content_of_rain (kg m-2). However, I have now realized there is another issue with this.

We have an existing name mass_concentration_of_rain_in_air which contains the following sentence in its definition: ' "Rain" means drops of water falling through the atmosphere that have a diameter greater than 0.5 mm.' I think this was to distinguish it from mass_concentration_of_drizzle_in_air which is defined as ' "Drizzle" means drops of water falling through the atmosphere that have a diameter typically in the range 0.2-0.5 mm.' (If memory serves me, these definitions of rain and drizzle were taken from the AMS glossary).

My understanding is that your proposed name is intended to cover both rain and drizzle (since it only excludes cloud water). To avoid possible confusion over what is/is not included in the quantity, my suggestion is to amend the proposal to:
atmosphere_mass_content_of_rain_and_drizzle (kg m-2)
' "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used. "Rain" means drops of water falling through the atmosphere that have a diameter greater than 0.5 mm.  "Drizzle" means drops of water falling through the atmosphere that have a diameter typically in the range 0.2-0.5 mm.'

Would that be okay?

The issue with rain/drizzle also affects another existing name, mass_fraction_of_rain_in_air, which is currently only defined as 'Mass fraction is used in the construction mass_fraction_of_X_in_Y, where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X).' I suspect that we should also change this one to mass_fraction_of_rain_and_drizzle_in_air. Do others agree?

Best wishes,
Alison

**Comment by JonathanGregory** [comment]
Dear Alison

I agree with changing rain to rain_and_drizzle in mass_fraction_of_rain_in_air. Thanks for spotting this problem.

Cheers

Jonathan

**Comment by GeyerB** [comment]
It is good to tackle this concretisation! Thanks for having the overview, Alison!!
We would like to have **atmosphere_mass_content_of_liquid_precipitation** more then
atmosphere_mass_content_of_rain_and_drizzle.

This name would leed to a description like
' "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used. 'Liquid_precipitation'  includes the two types "Rain" and "Drizzle". "Rain" means drops of water falling through the atmosphere that have a diameter greater than 0.5 mm. "Drizzle" means drops of water falling through the atmosphere that have a diameter typically in the range 0.2-0.5 mm.'

Would you agree to that?
Beate and Ronny

**Comment by GeyerB** [comment]
The fact that no one has objected in the last month could be taken as a sign that the name is acceptable...??
Cheers
Beate

**Comment by japamment** [comment]
Dear Beate,

We already have standard names for solid_precipitation meaning snow, hail and graupel. We also have terms that refer simply to "precipitation" meaning precipitation of water in all phases. It does seem logical, therefore, to introduce the term liquid_precipitation to mean rain and drizzle.

Following an earlier comment from @JonathanGregory I created the alias mass_fraction_of_rain_in_air -> mass_fraction_of_rain_and_drizzle_in_air in V71 of the standard name table, so for consistency that should also be changed (again) to be mass_fraction_of_liquid_precipitation_in_air. As far as I can see there are no consequences for any other existing names.

If there are no further comments/objections before 9th March I will mark this name as accepted and include it in the scheduled update.

Best wishes,
Alison

**Comment by GeyerB** [comment]
Great!!
Thanks for all the work again!!
Beate

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
