### ISSUE TITLE
New standard_name: atmosphere_mass_content_of_snow

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#18]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20

**- Term** atmosphere_mass_content_of_snow
**- Definition** "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. "Snow" refers to the precipitating part of snow in the atmosphere – the cloud snow content is excluded. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used.
**- Units** kg m-2

This proposal belongs to http://cfeditor.ceda.ac.uk/proposal/4297

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for proposing this name. In our previous mailing list discussion I think everyone was happy with the name atmosphere_mass_content_of_snow (kg m-2). We should swap the order of the third and fourth sentences in the definition, but otherwise it looks fine. This name is accepted for publication in the standard name table. The next update is scheduled for 3rd February.

I think it makes sense to also add your sentence ' "Snow" refers to the precipitating part of snow in the atmosphere – the cloud snow content is excluded' to the existing name mass_fraction_of_snow_in_air. Unless there are any objections I will add it at the next update.

Best wishes,
Alison

**Comment by GeyerB** [comment]
Great, thanks a lot!!!
Beate and Ronny

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
