### ISSUE TITLE
Insert `of_radiative_flux` in four `volume`...`coefficient` names

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/discuss#186]
**Proposer's name** Jonathan Gregory, **Date** 12th October 2022

Dear all

I propose that the existing standard names
```
volume_absorption_coefficient_in_air_due_to_dried_aerosol_particles
volume_backwards_scattering_coefficient_in_air_due_to_dried_aerosol_particles
volume_extinction_coefficient_in_air_due_to_ambient_aerosol_particles
volume_extinction_coefficient_in_air_due_to_cloud_particles
```
should be modified by inserting `of_radiative_flux` after `coefficient`, retaining the existing names as aliases. This would make them consistent with the eleven other standard names of volume absorption, attenuation and scattering coefficient or function that all include `of_radiative_flux`.

Best wishes

Jonathan

**Comment by feggleton** [comment]
I would tend to agree with this. The definition of volume absorption coefficient states:

The volume scattering/absorption/attenuation coefficient is **the fractional change of radiative flux** per unit path length due to the stated process. 

They would therefore include the phrase: Radiative flux is the sum of shortwave and longwave radiative fluxes.

**Comment by feggleton** [comment]
@japamment if you could add these changes to the editor please and let me know your opinion I think we can get these changes into the next update.

**Comment by taylor13** [comment]
I agree with the proposed edits.  Hope this doesn't reset any clocks.

**Comment by JonathanGregory** [comment]
Thanks, Ellie @efisher008

**Comment by efisher008** [comment]
Dear @JonathanGregory,

I have noticed that identical names for 
1. `volume_absorption_coefficient_of_radiative_flux_in_air_due_to_dried_aerosol_particles` 
2. `volume_backwards_scattering_coefficient_of_radiative_flux_in_air_due_to_dried_aerosol_particles` 

are found in the proposal by @markusfiebig in issue #130 re. particle optical properties, as new suggested standard names. There also seems to be a separate, newer, proposed change to 1. with a very similar description (adding the definition for radiative flux). I propose that I remove the newest proposed term change, and modify the accepted term change to include the radiative flux phrase in its description. As it looks the older/original versions of 1. and 2. existed prior to Markus's proposal, they do not need to be included in the batch of new names introduced with this and those entries in the CF editor can be removed. In that way there is only one term in the CF editor with each name, and preserves the history of the standard name aliases from their original versions instead of being new standalone names with none of this information. Does this make sense? 

The radiative flux description is the following: _"Radiative flux is the sum of shortwave and longwave radiative fluxes."_

Best regards,
Ellie

**Comment by JonathanGregory** [comment]
Thanks, Ellie @efisher008. I believe that Alison @japamment will advise us.

**Comment by efisher008** [comment]
Dear @JonathanGregory,

I have looked into this issue with @japamment and she agreed with the proposed actions - the radiative flux definition has therefore been absorbed into the description for the 'accepted' version of the name  
(1.) `volume_absorption_coefficient_of_radiative_flux_in_air_due_to_dried_aerosol_particles`
and the 'new' version of this was removed from the CF editor. The 'new' version of the name 
(2.) `volume_backwards_scattering_coefficient_of_radiative_flux_in_air_due_to_dried_aerosol_particles`
was marked as accepted. Meaning these two terms will appear in the next update (v84) of the standard names table. 

The 'under discussion' versions of both names (proposed in a separate issue #130 by @markusfiebig) will therefore need to be removed from that ongoing proposal so as not to introduce duplicate names to the table, and this will be dealt with in that GitHub issue. Thank you for your patience here and let me know if there are further questions!

Best regards,
Ellie

**Comment by efisher008** [comment]
Closing this issue as the last two names in this proposal have been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
