### ISSUE TITLE
Does a latitude/longitude grid mapping imply a spherical Earth?

### ISSUE THREAD

**Issue by gerritholl** [cf-convention/discuss#188]
In [Appendix F](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_latitude_longitude), the CF conventions describe that a latitude/longitude grid mapping takes no map parameters and refers to a spherical earth:

> Latitude-Longitude
> --
> 
> `grid_mapping_name = latitude_longitude`
> 
> This grid mapping defines the canonical 2D geographical coordinate system based upon latitude and longitude coordinates on a spherical Earth. It is included so that the figure of the Earth can be described.
> 
> **Map parameters**:  
>     None.
> **Map coordinates**:
> The rectangular coordinates are longitude and latitude identified by the usual conventions ([Section 4.1, "Latitude Coordinate"](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#latitude-coordinate) and [Section 4.2, "Longitude Coordinate"](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#longitude-coordinate)).

But in [the examples in §5.6](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#grid-mappings-and-projections), there are two examples using a latitude/longitude grid mapping, and these examples do define additional parameters, and one of them uses a non-spherical Earth:

> Example 5.8. Latitude and longitude on a spherical Earth
> 
> ```
> dimensions:
>   lat = 18 ;
>   lon = 36 ;
> variables:
>   double lat(lat) ;
>   double lon(lon) ;
>   float temp(lat, lon) ;
>     temp:long_name = "temperature" ;
>     temp:units = "K" ;
>     temp:grid_mapping = "crs" ;
>   int crs ;
>     crs:grid_mapping_name = "latitude_longitude"
>     crs:semi_major_axis = 6371000.0 ;
>     crs:inverse_flattening = 0 ;
> ```
> 
> Example 5.9. Latitude and longitude on the WGS 1984 datum
> 
> ```
> dimensions:
>   lat = 18 ;
>   lon = 36 ;
> variables:
>   double lat(lat) ;
>   double lon(lon) ;
>   float temp(lat, lon) ;
>     temp:long_name = "temperature" ;
>     temp:units = "K" ;
>     temp:grid_mapping = "crs" ;
>   int crs ;
>     crs:grid_mapping_name = "latitude_longitude";
>     crs:longitude_of_prime_meridian = 0.0 ;
>     crs:semi_major_axis = 6378137.0 ;
>     crs:inverse_flattening = 298.257223563 ;
> ```

It seems to me that the examples in §5.6 contradict the definition in the appendix.

Questions:

- Are examples 5.8 and 5.9 CF conform?
- Is the description in Appendix F correct and complete?
- If not, what are the recognised map parameters for a latitude/longitude grid mapping?

**Comment by dblodgett-usgs** [comment]
Hi @gerritholl -- thanks for the nicely posed question.

There's been a lot of back and forth on this over the years. Practically speaking, the "default" lon/lat should be WGS84 (the GPS datum) and datum transformations should almost never be applied when working with data that is described as being on a spherical datum. (e.g. `+nadgrids=@null` in proj4 terms). This is because when lon/lat referenced data (say a weather station) are used for things like data assimilation, no ellipsoid to sphere transform is applied (in general). 

I have suggested that the `latitude_longitude` grid mapping have CF-implied default parameters that map to the WGS84 datum but some feel that is implying a level of precision that is inappropriate for some data thus no default is provided.

This is an area that some are going to feel CF is incomplete and others see no issue as lon/lat is treated as a base unit with no required earth shape in all their applications. 

Is that answering your questions? I could probably dig up some historical issues on this topic if it would be helpful, but wanted to jot down an answer quickly now.

**Comment by JonathanGregory** [comment]
Dear @gerritholl and Dave @dblodgett-usgs

Perhaps the word "spherical" should not appear in the definition of the `latitude_longitude` grid_mapping?

Best wishes

Jonathan

**Comment by dblodgett-usgs** [comment]
That would be a good step, yes.

**Comment by davidhassell** [comment]
Removing the word "spherical" where @JonathanGregory suggests is fine by me.

**Comment by gerritholl** [comment]
> Is that answering your questions?

I think so.  I'm glad to hear that WGS84 is CF-conform; the definition of the `latitude_longitude` grid mapping suggested otherwise.  It would be good if that formulation could be changed.

**Comment by JonathanGregory** [comment]
Dear all

Everyone who's given a view agrees on deleting the word "spherical" from the definition of the `latitude_longitude` grid_mapping, and enough support has been expressed for it. This change will be adopted in 21 days from now, according to the rules, if no-one expresses reservations about it sooner. Thanks for raising the issue, @gerritholl.

One reason why there isn't a default for the shape of the Earth in CF is that a lot (perhaps most) of the data that uses CF is from GCMs. In at least some of these (perhaps many or most) the Earth is treated as spherical.

Best wishes

Jonathan

**Comment by JonathanGregory** [comment]
I've opened [issue 410](https://github.com/cf-convention/cf-conventions/issues/410) in the conventions repo to make this change, so I'll close this issue now. Thanks, everyone.
