### ISSUE TITLE
New description for atmosphere_mass_content_of_cloud_liquid_water

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#19]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20

The description of atmosphere_mass_content_of_cloud_liquid_water is incomplete, as "cloud_liquid_water" is not mentioned.

**- Term** atmosphere_mass_content_of_cloud_liquid_water
**- New Definition** "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. **"Cloud liquid water" refers to the liquid phase of cloud water.** For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used.
**- Units** kg m-2

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for raising this issue. I agree that we should improve the definition. In fact, there are 45 existing cloud_liquid_water names, only one of which has a definition that actually explains what the term means!

The definition of  mass_concentration_of_cloud_liquid_water_in_air says: 'Cloud droplets are spherical and typically a few micrometers to a few tens of micrometers in diameter. An upper limit of 0.2 mm diameter is sometimes used to distinguish between cloud droplets and drizzle drops, but in active cumulus clouds strong updrafts can maintain much larger cloud droplets.'

In the mailing list discussion I suggested that we combine the existing text about droplet size with your proposed additional text and add it to all 45 affected names.  For example, atmosphere_mass_content_of_cloud_liquid_water would be defined as:
' "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used. "Cloud liquid water" refers to the liquid phase of cloud water. Cloud droplets are spherical and typically a few micrometers to a few tens of micrometers in diameter. An upper limit of 0.2 mm diameter is sometimes used to distinguish between cloud droplets and drizzle drops, but in active cumulus clouds strong updrafts can maintain much larger cloud droplets.'

I don't think anyone commented about this suggestion - is this a good way to proceed?

Best wishes,
Alison

**Comment by graybeal** [comment]
Perhaps we can fix the construction of the last sentence too. The word 'but' is confusing, because 0.2mm diameter is the line between droplets and drizzle, not an upper limit on droplet size. So the second phrase doesn't counter the first phrase, it just adds another piece of (rather vague) info.

**Comment by japamment** [comment]
Thanks for your comment @graybeal. The origin of the cloud droplet definition is the AMS glossary. As you rightly say, the information is rather vague but I feel it's still useful to include. For clarity, perhaps we should just include the whole of the AMS text as follows:
atmosphere_mass_content_of_cloud_liquid_water
' "Content" indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used. "Cloud liquid water" refers to the liquid phase of cloud water. Cloud droplets are spherical and typically a few micrometers to a few tens of micrometers in diameter. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.'

Best wishes,
Alison

**Comment by GeyerB** [comment]
Thanks for all updates!!
Ronny and Beate

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for getting back to me. I think we can accept this name for publication in this week's update. I will create a separate issue for the updating of the other 45 cloud liquid water names.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
