### ISSUE TITLE
New description for air_potential_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#21]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20

The variable is valid for air by name. 

**- Term** air_potential_temperature
**- New Definition** Potential temperature is the temperature a parcel of air ~~or sea water~~ would have if moved adiabatically to sea level pressure.
**- Units** K

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for this proposal and the related one for changing the definition of sea_water_potential_temperature [#22 ](https://github.com/cf-convention/discuss/issues/22).

If the definitions seem confusing in relation to the names then we should try to improve them. Potential temperature is a general concept so I think it is reasonable to use the same definition in the case of air and sea water but perhaps it would be better to say 'fluid' rather than list the different mediums: 'Potential temperature is the temperature a fluid parcel would have if moved adiabatically to sea level pressure.'

Would that be better?

Best wishes,
Alison

**Comment by roy-lowry** [comment]
@japamment Thanks for pointing out what I had missed this ticket. The design of many Standard Name descriptions is based on the concatenation of the descriptions of individual Standard Name elements. This is the case here with the same description used for potential temperature whether it be in air or water. There must be many cases where description elements have broader semantics than their associated Standard Names. Unless we want to establish a precedent for large-scale description updates I would suggest leaving things as they are unless Beate and Ronny have very strong feelings on the issue.

**Comment by japamment** [comment]
Dear All,

Martin Juckes (@martinjuckes) and I discussed (offline) the definition of air_potential_temperature and we both feel that it does need to be reviewed.

air_potential_temperature has existed in the standard name table since version 1 and dates back to around 2002, thus it has been in use for a long time and is likely to be present in many thousands, if not millions, of existing data files. Throughout that time it has been defined as 'Potential temperature is the temperature a parcel of air or sea water would have if moved adiabatically to sea level pressure.' Although not stated, the "sea level pressure" referred to here is probably mean sea level pressure.

The AMS glossary (http://glossary.ametsoc.org/wiki/Potential_temperature) refers to a "standard pressure" rather than sea level: "The temperature that an unsaturated parcel of dry air would have if brought adiabatically and reversibly from its initial state to a standard pressure, p0, typically 100 kPa." Many other online references contain a similar definition. The inclusion of the word "typically" leaves room for a different value to be used and Martin has seen instances in the past of 1015 hPa being used as the standard pressure. (Perhaps that was taken to be a representative value of mean sea level pressure).

The AMS glossary goes on to say: "In oceanography, the temperature that a water sample would attain if raised adiabatically to the sea surface." This is consistent with the current definition of sea_water_potential_temperature being discussed in the related issue [#22](https://github.com/cf-convention/discuss/issues/22). I think this strengthens the argument for separating the standard name definitions of air and sea_water potential temperature, rather than continuing to use the same text for both.

For air_potential_temperature we need to be careful not to invalidate existing data but I think it would be helpful to bring the definition more in line with what seems to be general practice. I propose amending it as follows: 'The quantity with standard name air_potential_temperature is the temperature a parcel of air would have if moved dry adiabatically to a standard pressure. To specify the standard pressure to which the potential temperature applies, provide a scalar coordinate variable with standard name reference_air_pressure_for_air_potential_temperature.' 

We would then also need to introduce a new standard name:
**reference_air_pressure_for_air_potential_temperature** (Pa)
'The "reference air pressure for air potential temperature" means the standard pressure referred to by a quantity with standard name air_potential_temperature.'
We have similar existing standard names such as reference_air_pressure_for_atmosphere_vertical_coordinate and water_surface_reference_datum_altitude.

I have stopped short of saying that the reference coordinate variable **must** be supplied because obviously it wouldn't be there in older data files. Further comments on these ideas would be most welcome!

**Comment by taylor13** [comment]
I support this clarification/correction;  For the new standard name proposed, I think "reference_pressure_for_potential_temperature" would suffice and would serve both  air_potential_temperature and sea_water_potential_temperature.  

It would be good to make the same improvement for many of the other standard names including the string, "potential_temperature"

**Comment by martinjuckes** [comment]
I like the new definition for `potential_temperature`, and the proposal to include a mechanism for recording the reference pressure used. I was slightly wrong with the 1015 hPa figure which I mentioned to Alison: the standard pressure I was thinking of is one standard atmosphere, which udunits will tell you is defined by `1 atm = 1013.25 hPa`.

Could the standard name for the reference pressure just be `reference_pressure`, with a definition "A constant pressure value, typically representative of mean sea level pressure, which can be used in defining coordinates or functions of state."? This is also needed for the `dimensionless_exner_function` and `sea_water_potential_density`, which currently have ambiguous dependencies on a reference pressure. 

I can see that there is a precedent for having a reference pressure named specifically for the way it is going to be used, but this looks like an unnecessary duplication of information. If someone is presenting both `dimensionless_exner_function` and `air_potential_temperature`, and using `sigma` coordinates, wouldn't it make sense for them to use a single reference pressure? There is always the possibility of having multiple values in different NetCDF variables if someone really wants to use  a different reference value for each parameter, but it would be good, I think, to make it possible to specify a single generic value. For that we need a generic term: `reference_pressure`.

The terms `sound_pressure_level_in_air/water` also refer to "p0", but in this case it is a reference sound pressure .. according to wikipedia this is usually taken 20 micro Pa, so it might make sense to add a `reference_sound_pressure` term.

**Comment by japamment** [comment]
Dear Karl and Martin,

Thank you both for your comments. I agree with Karl that we do need to improve the definitions of a number of names that mention "potential temperature". I suggest continuing the discussion of those other names in [issue #20](https://github.com/cf-convention/discuss/issues/20) where a similar point has been raised.

I think we are agreed on introducing a coordinate variable to state the value of reference pressure for air_potential_temperature and I like Martin's suggestion of having a generic standard name that can be referred to by any quantity that requires a similar reference pressure value.

Following Martin's suggestions we would have the following.

1. **air_potential_temperature** (K)
'Air potential temperature is the temperature a parcel of air would have if moved dry adiabatically to a standard pressure, typically representative of mean sea level pressure. To specify the standard pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.'

2. **dimensionless_exner_function** (1)
'The term "Exner function" is applied to various quantities in the literature. "Dimensionless Exner function" is the standard name of (p/p0)^(R/Cp), where p is pressure, p0 a reference pressure, R the gas constant and Cp the specific heat at constant pressure. This quantity is also the ratio of in-situ to potential temperature. Standard names for other variants can be defined on request. To specify the reference pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.'

3. **sea_water_potential_density** (kg m-3)
'Sea water potential density is the density a parcel of sea water would have if moved adiabatically to a reference pressure, by default assumed to be sea level pressure. To specify the reference pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure. The density of a substance is its mass per unit volume. For sea water potential density, if 1000 kg m-3 is subtracted, the standard name sea_water_sigma_theta should be chosen instead.'
N.B. I have removed the reference to 'air or sea water' in this definition so that we can separate definitions of sea_water_potential_density and air_potential_density in the same way as we are now doing for potential temperature. We don't currently have any names for air_potential_density but AMS says it refers to 1000 hPa rather than 'sea level pressure' so having separate definitions should help avoid confusion in the future.

4. **reference_pressure** (Pa)
'A constant pressure value, typically representative of mean sea level pressure, which can be used in defining coordinates or functions of state.'

For consistency we should update the definition of change_over_time_in_sea_water_potential_density:

5. **change_over_time_in_sea_water_potential_density** (kg m-3)
'The phrase "change_over_time_in_X" means change in a quantity X over a time interval, which should be defined by the bounds of the time coordinate. Sea water potential density is the density a parcel of sea water would have if moved adiabatically to a reference pressure, by default assumed to be sea level pressure. To specify the reference pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure. The density of a substance is its mass per unit volume. For sea water potential density, if 1000 kg m-3 is subtracted, the standard name "sea_water_sigma_theta" should be chosen instead.'

The definition of sea_water_sigma_theta also refer to an unspecified reference pressure, so again for consistency we should update it:

6. **sea_water_sigma_theta** (kg m-3)
'Sigma-theta of sea water is the potential density (i.e. the density when moved adiabatically to a reference pressure) of water having the same temperature and salinity, minus 1000 kg m-3. Note that sea water sigma is not the same quantity as the dimensionless ocean sigma coordinate (see Appendix D of the CF convention), for which there is another standard name. To specify the reference pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.'

If others are happy with names 1-6 I think they can be accepted for publication.

7. We have one other existing name whose definition mentions an unspecified reference pressure:
**difference_of_air_pressure_from_model_reference** (Pa)
'In some atmosphere models, the difference of air pressure from model reference is a prognostic variable, instead of the air pressure itself. The model reference air pressure is a model-dependent constant. Air pressure is the force per unit area which would be exerted when the moving gas molecules of which the air is composed strike a theoretical surface of any orientation.'

I don't have any experience of working with models that use this variable - is the "model reference" usually a constant air pressure close to sea level? If so, I think we should recommend the use of reference_pressure as a coordinate variable. If not, we would need to define another suitable standard name to use as a coordinate variable.

8. Martin mentions the possibility of using the same reference_pressure coordinate variable with vertical coordinates such as sigma coordinates, etc. Currently we use **reference_air_pressure_for_atmosphere_vertical_coordinate** for this. This is recommended in Appendix D of the conventions for atmosphere natural log pressure coordinate and atmosphere hybrid sigma pressure coordinate so I think we should stick with using the existing name for those particular cases.

9. Regarding the existing sound_pressure_level_in_air|sea_water names and also sound_intensity_level_in_air|sea water I think the values of the reference pressure/intensity are already stated in the definitions, e.g. 'Sound pressure level in air is expressed on a logarithmic scale with reference to a sound pressure of 2e-5 Pa.' The specified reference pressure/intensity is different for the various names. I suggest we don't change these at the moment as we haven't had a specific request to do so and the definitions as they stand are correct. We could generalize them to allow use of a coordinate variable if that were needed in the future.

Best wishes,
Alison

**Comment by martinjuckes** [comment]
Hello Alison,

Proposals 1-6 look good to me. On 7, I've not come across the form of vertical coordinate implied by difference_of_air_pressure_from_model_reference (Pa), so I'd be tempted to leave it unchanged.

On 7: The reference pressure for log-pressure and atmospheric hybrid-sigma coordinates is intended to be a constant, and the constant used in log-pressure coordinates would usually be the same as the constant used in thermodynamic state variables (so temperature and potential temperature are the same at log-pressure equals zero) and representative of surface pressure, but the reference value in hybrid-sigma coordinates would usually be a different number (these coordinates have an explicit and  spatially varying surface pressure). I agree that sticking with things as they are is probably the best option.

8. Agreed.

**Comment by GeyerB** [comment]
We like the idea of additional reference_pressure!!
Thanks to all contributers,
Beate and Ronny

**Comment by japamment** [comment]
Hi Beate, Ronny and Martin,

Thanks again for your comments. It looks like all these names are now agreed. Proposals 1-6 are accepted for inclusion in the standard name table and will be added in this week's update. For proposals 7-9 I think we are agreed to leave the current definitions unchanged.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
