### ISSUE TITLE
 Standard names: Specific conductivity

### ISSUE THREAD

**Issue by slbrunner** [cf-convention/discuss#212]
Name: Shelby Brunner
Date: March 2, 2023

Term: sea_water_specific_conductivity 
Description: Specific conductivity is the electrical conductivity of water standardized to 25 degrees Celsius. Often it is used in freshwater environments where salinity is not as applicable. 
Units: S m-1

**Comment by JonathanGregory** [comment]
Dear Shelby

We already have a standard name for this, viz. `sea_water_electrical_conductivity`.

Best wishes

Jonathan

**Comment by slbrunner** [comment]
Dear Jonathan,

We view sea_water_electrical_conductivity as the general, non-temperature standardized measurement of sea_water_specific_conductivity. Data providers and users of specific conductivity look for it to be specified as "specific conductivity" which is why we want to see it added as a CF parameter. Happy to chat more about this if you'd like.

Thanks,
Shelby

**Comment by JonathanGregory** [comment]
Dear Shelby @slbrunner

Since CF standard names are used by people from all disciplines, they have to be self-explanatory to non-experts, so often they don't use exactly the words or phrases that are customary in a particular field. We should include "electrical" because it's not thermal conductivity. As far as I can tell from Google the word "specific" isn't widely used with your meaning, but I'm not an expert myself.

Since your quantity is really `sea_water_electrical_conductivity` but measured at a defined temperature rather than the in-situ property, I would suggest calling it `sea_water_electrical_conductivity_at_reference_temperature`. The reference temperature could be specified by attaching a scalar or size-one coordinate variable of `sea_water_temperature`, e.g.

```
float conductivity(lat,lon);
  conductivity:units="S m-1";
  conductivity:standard_name="sea_water_electrical_conductivity_at_reference_temperature";
  conductivity:coordinates="reftemp";
float reftemp;
  reftemp:units="K";
  reftemp:standard_name="sea_water_temperature";
```

If 25degC is the usual choice, the definition could specify this as the default, if the reference temperature isn't specified, but I wonder whether it is better always to specify. For example, I see that Bacon et al. (2007, https://doi.org/10.1175/JTECH2081.1) mention 15degC and 21degC as standard temperatures for sea water.

Best wishes

Jonathan

**Comment by DocOtak** [comment]
Also consider the name [temperature_of_analysis_of_sea_water](http://vocab.nerc.ac.uk/collection/P07/current/THTBXRBY/) that was added specifically to address reference/analysis temperatures used in other measurements.

**Comment by JonathanGregory** [comment]
Dear Andrew @DocOtak 

Thanks for reminding us. Would `temperature_of_analysis_of_sea_water` be a more appropriate standard name for the temperature at which the electrical resistance is measured than `sea_water_temperature`?

Cheers

Jonathan

**Comment by JonathanGregory** [comment]
@slbrunner The definition of the standard name could say that this quantity is sometimes called "specific conductivity", because then people would be able to find it if they search for that phrase in the standard name table (including the definitions in the search, which is an available option).

**Comment by slbrunner** [comment]
Thanks for all these great ideas! I, as well as my DMAC team, all agree that using sea_water_electrical_conductivity_at_reference_temperature, then adding temperature_of_analysis_of_sea_water as a scalar/sub variable makes complete sense.

I also appreciate the suggestion to add "specific conductivity" in the definition to make it findable by anyone searching. 

For anyone reading-- 25 degrees C is the standard that [USGS ](https://pubs.usgs.gov/tm/09/a6.3/tm9-a6_3.pdf)and [EPA](https://www.epa.gov/sites/default/files/2015-08/documents/method_120-1_1982.pdf) reference, and is where our definition stems from.

**Comment by DocOtak** [comment]
@JonathanGregory I think in this instance,`temperature_of_analysis_of_sea_water` makes it very clear that the variable is the temperature for some other variable (meta) vs some environment variable (data).

This is my first time seeing actual conductivity being the report variable rather than practical salinity, though, my work is in the ocean.

**Comment by JonathanGregory** [comment]
Dear @slbrunner @DocOtak 

I agree with the argument in favour of `temperature_of_analysis_of_sea_water` for the reference temperature. Please could you post a revised proposal in this issue, Shelby, with the updated definition and new standard name?

Best wishes

Jonathan

**Comment by slbrunner** [comment]
Updated proposal (though I'm not entirely sure I formatted the scalar variable correctly or how to set a default one):

Term: sea_water_electrical_conductivity_at_reference_temperature
Description: Electrical conductivity of a water sample is temperature dependent. When conductivity is standardized to a known temperature, 25 degrees Celsius, this quantity is called specific conductivity.
Units: S m-1
conductivity:coordinates="reftemp";
   reftemp;
  reftemp:units="K";
  reftemp:standard_name="temperature_of_analysis_of_sea_water";

**Comment by JonathanGregory** [comment]
I would suggest: "The electrical conductivity of sea water in a sample measured at a defined reference temperature. The reference temperature should be recorded in a scalar coordinate variable, or a coordinate variable with a single dimension of size one,  and the standard name of `temperature_of_analysis_of_sea_water`. This quantity is sometimes called 'specific conductivity' when the reference temperature 25 degrees Celsius."

It would be better to require the reference temperature to be specified, I think, rather than to have a default.

**Comment by slbrunner** [comment]
Update again thanks to @JonathanGregory 

Term: sea_water_electrical_conductivity_at_reference_temperature
Description: The electrical conductivity of sea water in a sample measured at a defined reference temperature. The reference temperature should be recorded in a scalar coordinate variable, or a coordinate variable with a single dimension of size one, and the standard name of temperature_of_analysis_of_sea_water. This quantity is sometimes called 'specific conductivity' when the reference temperature 25 degrees Celsius.
Units: S m-1
conductivity:coordinates="reftemp";
reftemp;
reftemp:units="K";
reftemp:standard_name="temperature_of_analysis_of_sea_water";

**Comment by JonathanGregory** [comment]
Thanks, @slbrunner. If no-one expresses any concerns about this in the next week or two it should be accepted for inclusion in the standard name table.

**Comment by feggleton** [comment]
Thanks all for discussing this proposal. I have added to the editor and as no more comments have been made, this can be accepted into the next update.

**Comment by japamment** [comment]
I am closing this ticket as the proposed name was added in V81 of the standard name table.
