### ISSUE TITLE
 Standard names: Typo/Error for the name moles_of_particulate_inorganic_carbon_per_unit_mass_of_sea_water

### ISSUE THREAD

**Issue by DocOtak** [cf-convention/discuss#216]
While mapping the new names from #135 submitted by @fcarvalhopacheco on behalf of HOT/CCHDO (myself included) to existing vocabularies already in use in GO-SHIP/WOCE. I noticed we used the `*_of_sea_water` form. I did some looking and this appear to be an error because this is not a property of the water itself and I think we should have used the `*_in_sea_water` form.

As such, I think this needs correcting to `moles_of_particulate_inorganic_carbon_per_unit_mass_in_sea_water` and add the erroneous name as an alias.

**Comment by JonathanGregory** [comment]
Dear Andrew @DocOtak 

Thanks for raising this point. I see there are currently 12 names of the form `moles_of_`X`_per_unit_mass_in_sea_water` and one with `of` (the one you mention). I think either form could be correct, because it's referring to a unit mass _of_ sea water. But we ought to be consistent, and if both are OK it's easier to make the change you suggest. Also that will lead to fewer mistakes because all the other kinds of concentration names (without `per_unit_mass`) have `in`. So I agree with you.

Best wishes

Jonathan

**Comment by DocOtak** [comment]
Hi @JonathanGregory I think this also is inline with the [naming guidelines for mediums](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html#medium), but am not quite sure.

**Comment by fcarvalhopacheco** [comment]
@roy-lowry

**Comment by roy-lowry** [comment]
@fcarvalhopacheco Thanks. I totally agree with this correction.

**Comment by feggleton** [comment]
Thanks all, have added this to the next update on Monday.

**Comment by japamment** [comment]
I am closing this ticket as the proposed change was added in V81 of the standard name table.
