### ISSUE TITLE
New description for sea_water_potential_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#22]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2020/01/10

The variable is valid for sea_water by name.

**- Term** sea_water_potential_temperature
**- New Definition** Potential temperature is the temperature a parcel of ~~air or~~ sea water would have if moved adiabatically to sea level pressure.
**- Units** K

**Comment by japamment** [comment]
Dear Beate and Ronny,

As per my comment in the related issue [#21](https://github.com/cf-convention/discuss/issues/21) I am suggesting we change this definition as follows:
'Potential temperature is the temperature a fluid parcel would have if moved adiabatically to sea level pressure.'

N.B. There are 17 existing names that refer to sea_water_potential_temperature whose definitions would also need to be updated in line with this issue.

Best wishes,
Alison

**Comment by roy-lowry** [comment]
@japamment Thanks for pointing out what I had missed in this ticket. The design of many Standard Name descriptions is based on the concatenation of the descriptions of individual Standard Name elements.  With the exception of sea_water_potential temperature the phrase 'air or sea water' is obviously within such an element description and therefore OK in my opinion.

In the case of sea_water_potential_temperature (and air_potential_temperature) 'air or sea water' becomes somewhat nonsensical because 'Potential temperature is the temperature a parcel of air or sea water would have if moved adiabatically to sea level pressure' is the whole description. 

To me the fixes proposed in this ticket and issue #21 would do the job, except that I would change the description to 'Sea water potential temperature is the temperature a parcel of sea water would have if moved adiabatically to sea level pressure.'  ( 'Air potential temperature is the temperature a parcel of air would have if moved adiabatically to sea level pressure.') so we don't have what look like two different definitions of 'potential temperature'.

A global substitution of 'fluid' for 'air or sea water' would also work. My only concern would be unecessary extra work.

**Comment by japamment** [comment]
@roy-lowry many thanks for your comments. On looking further into the definitions of air and sea water potential temperature I have now changed my position and feel that it does make sense to separate them.

In issue [#21](https://github.com/cf-convention/discuss/issues/21) I have suggested that the definition of air_potential_temperature should refer to a "standard pressure" rather than sea level for consistency with the AMS glossary and other online references. For sea water potential temperature the AMS glossary says "In oceanography, the temperature that a water sample would attain if raised adiabatically to the sea surface." If, as now seems likely, we are going to separate the definitions I think it makes sense to accept Beate's proposal for sea_water_potential_temperature, which I think is also what you are proposing.

Best wishes,
Alison

**Comment by roy-lowry** [comment]
Yes, that's fine.

**Comment by japamment** [comment]
@roy-lowry @GeyerB, okay I think we are agreed on this one. The definition of sea_water_potential_temperature will be amended as follows:
'Sea water potential temperature is the temperature a parcel of sea water would have if moved adiabatically to sea level pressure.'

This change is accepted for inclusion in the 3 February update.

Best wishes,
Alison

**Comment by GeyerB** [comment]
Fine, thanks for the work!
Ronny and Beate

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
