### ISSUE TITLE
 Standard names: Ekman current

### ISSUE THREAD

**Issue by abiardeau** [cf-convention/discuss#222]
Hello,

I am Aurore BIARDEAU from Mercator Ocean international.
Date 03/04/2023

We plan to add new variables linked to the ekman current in the Copernicus Marine service.
The data producer proposes those standard names : 
ekman_eastward_sea_water_velocity
ekman_northward_sea_water_velocity

Following the guidelines, do you suggest another construction for those standard names, such as eastward_sea_water_velocity_due_do_XXX ? 

Thanks for your advice, 

Aurore BIARDEAU

**Comment by feggleton** [comment]
Thanks, I have now added this to the cfeditor. There are some names which follow this construction such as baroclinic_eastward_sea_water_velocity and barotropic_eastward_sea_water_velocity and geostrophic_eastward_sea_water_velocity. Have a look at those in the table and see if they fit your terms construction. Or as you say there is due_to terms such as eastward_sea_water_velocity_due_to_parameterized_mesoscale_eddies - this is the phrase for due_to: The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. I assume the units are ms-1?

**Comment by abiardeau** [comment]
Thanks @feggleton for your answer. 
We are finally going for "eastward_sea_water_velocity_due_to_ekman_drift". Indeed the units are ms-1

**Comment by JonathanGregory** [comment]
Probably it's what you both mean, but for the avoidance of any doubt, may I clarify that the units are `m s-1`, with a space, not `ms-1`, which is reciprocal milliseconds (equivalent to `kHz`).

**Comment by feggleton** [comment]
Thanks both. Have added additional phrase now it's a due_to term. 

"The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase."

Yes m s-1.

**Comment by marceloandrioni** [comment]
Hello, to keep the same standard as other "velocity" variables, e.g.:

```
eastward_sea_water_velocity_due_to_tides
northward_sea_water_velocity_due_to_tides
sea_water_speed_due_to_tides
sea_water_velocity_to_direction_due_to_tides
```

I would like to suggest that variables

```
sea_water_speed_due_to_ekman_drift
sea_water_velocity_to_direction_due_to_ekman_drift
```

also be included. Bellow a tentative description:

Term: sea_water_speed_due_to_ekman_drift
Description: Speed is the magnitude of velocity. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase.
Units: m s-1

Term: sea_water_velocity_to_direction_due_to_ekman_drift
Description: A velocity is a vector quantity. The phrase "to_direction" is used in the construction X_to_direction and indicates the direction towards which the velocity vector of X is headed. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase.
Unit: degree

Thank you.

**Comment by japamment** [comment]
Thanks @abiardeau @feggleton. The first two names proposed in this issue have been agreed and published in V83 of the standard name table:
eastward_sea_water_velocity_due_to_ekman_drift
northward_sea_water_velocity_due_to_ekman_drift

@marceloandrioni has proposed further ekman standard names:
sea_water_speed_due_to_ekman_drift
sea_water_velocity_to_direction_due_to_ekman_drift

I agree that these follow established syntax for standard names and I don't see any problem with adding them. I've added them to the CF editor  ([http://cfeditor.ceda.ac.uk/proposals/1](http://cfeditor.ceda.ac.uk/proposals/1)).

I notice that we haven't yet defined "Ekman drift" for use in standard names. I suggest we add the following to the description of all four names in this issue:
"Ekman drift" is the movement of a layer of water (the Ekman layer) due to the combination of wind stress at the sea surface and the Coriolis effect. Ekman drift is to the right of the wind direction in the Northern Hemisphere and the left in the Southern Hemisphere. Reference: https://www.open.edu/openlearn/science-maths-technology/the-oceans/content-section-4.3.
Does that sound okay?

Best wishes,
Alison

**Comment by efisher008** [comment]
Dear @marceloandrioni,

The two additional Ekman standard names and their descriptions (including the new text @japamment has suggested) appear to be agreed. Unless there are any further comments in the next 7 days, the text will be added to all four Ekman names and the two new names you proposed will be accepted.

Best wishes,
Ellie

**Comment by efisher008** [comment]
Dear @marceloandrioni,

The two further names (`sea_water_speed_due_to_ekman_drift` and `sea_water_velocity_to_direction_due_to_ekman_drift`) have now been accepted and will be published in the next release of the standard names table - apologies for the wait and thanks again for the proposal.

Best wishes,
Ellie

**Comment by marceloandrioni** [comment]
Great, thank you @efisher008.

**Comment by abiardeau** [comment]
Thanks a lot @efisher008

**Comment by efisher008** [comment]
Closing this issue as these names have been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
