### ISSUE TITLE
 Proposal for a new standard_name modifier or standard_name : normalized_frequency

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#23]
The application of online model diagnostics leads more and more to statistical values of variables. One example could be the frequency distribution of wind direction on the basis of model time step in bins of 10 degree.

We see two possibilities:

## standard_name modifier
A new standard_name modifier "normalized_frequency"  in [Appendix C, Table C.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#standard-name-modifiers).

To deliver the information on the interval of the original variable (line 1a in the example below) or additionally the variable containing the bins (line 1b in the example), this possibility implies an **additional** entry for cell_methods in [Appendix E, Table E.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#table-cell-methods): "normalized_frequency", with   
**Description:** "The data values represent the distribution of a specific quantity over a grid cell with respect to the specified dimension and the given bins. It is the number of events normalizes by the sample size."
**Units:** "1"

**Example**

```
dimensions:
  time = UNLIMITED; // (5 currently)
  nclass = 36;
  nv = 2;
variables:
  double time(time);
    time:standard_name = "time";
    time:long_name = "time" ;
    time:units = "days since 1970-01-01 00:00:00" ;
    time:bounds = "time_bnds"
  double time_bnds(time,nv);
  float class(nclass);
    class:long_name = "wind sector";
    class:units = "degree";
    class:bounds = "class_bnds"
  float class_bnds(nbin,nv);

  float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "wind_from_direction  normalized_frequency”;
    WDIR_freq: units = "1";
1a  WDIR_freq: cell_methods = "time: normalized_frequency (interval: 40 s)”;

1b  WDIR_freq: cell_methods = "time: normalized_frequency (interval: 40 s, bins: class)”;
```

## standard_name "normalized_frequency"
This possibility implies a new usage of `ancillary_variables` to clarify, which quantity is counted.

**Example**

```
  float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "normalized_frequency";
    WDIR_freq: ancillary_variables = "wind_from_direction"
    WDIR_freq: units = "1";
```

**Description:** The data values represent the distribution of a specific quantity over a grid cell with respect to the given bins. It is the number of events normalized by the sample size.

**Problem:** the information of the interval of the original data (in the given example `wind_from_direction` with interval 40 s) does not belong to `cell_methods`. Do we need a new attribute?

We prefer possibility 1b but recognized that standard_name modifiers seem to be deprecated if the unit is not the same like the initial variable…

**Comment by roy-lowry** [comment]
Might this be the time to consider making the Standard Name Modifiers a controlled vocabulary like Cell Methods rather than a table in the Conventions document to make the mechanism for future changes more akin to Standard Name updates?

To be clear, I would not suggest blocking this request until such a change were implemented.

**Comment by JonathanGregory** [comment]
Dear Beate

If I understand correctly, your normalized frequency is a probability distribution. We have a guideline template for this in http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html. So far we don't have any standard names of this type, but we do have a couple with `histogram`, which is a similar construction. The guidelines suggest that your quantity should have a standard name of `probability_distribution_of_wind_from_direction_over_time`, and it should have a coordinate variable of `wind_from_direction`, whose bounds will specify the bin limits you used. You could omit `over_time`, which indicates that the distribution was computed from temporal variation. Does that make sense?

This doesn't seem to me to be a case for a standard name modifier. It is not ancillary information about the data variable; it's a new data variable that was computed from the original one. In my opinion, standard name modifiers are not a good part of the convention; I would rather that we didn't add any more of them.

Best wishes

Jonathan

**Comment by GeyerB** [comment]
@JonathanGregory 
We could live with 'probability_distribution_of_wind_from_direction_over_time'. It would lead to a huge set of new variables starting with 'probability_distribution', but we understand that new modifiers are not wellcome.
We wonder, where to let the information of the original time interval (in our case of model simulation we have hourly output with a simulation time step of 40s).

**Description:** "'probability_distribution..._over_time' means that the data represent the distribution of a specific quantity over a grid cell with respect to the time dimension and the given bins. It is the number of events normalizes by the sample size. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) In meteorological reports, the direction of the wind vector is usually (but not always) given as the direction from which it is blowing (wind_from_direction) (westerly, northerly, etc.). In other contexts, such as atmospheric modelling, it is often natural to give the direction in the usual manner of vectors as the heading or the direction to which it is blowing (wind_to_direction) (eastward, southward, etc.) "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming."
**Units:** "1"
Example

```
dimensions:
  time = UNLIMITED; // (5 currently)
  nclass = 36;
  nv = 2;
variables:
  double time(time);
    time:standard_name = "time";
    time:long_name = "time" ;
    time:units = "days since 1970-01-01 00:00:00" ;
    time:bounds = "time_bnds"
  double time_bnds(time,nv);
  float class(nclass);
    class: standard_name = "wind_from_direction"
    class:long_name = "wind sector";
    class:units = "degree";
    class:bounds = "class_bnds"
  float class_bnds(nbin,nv);

  float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "probability_distribution_of_wind_from_direction_over_time”;
    WDIR_freq: units = "1";
    WDIR_freq: coordinates = "lon lat class"
```
Thanks,
Beate

**Comment by neumannd** [comment]
Could the information on original interval/calculate-step/measurement-interval of the data expressed as follows:

```
  float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "probability_distribution_of_wind_from_direction_over_time”;
    WDIR_freq: units = "1";
    WDIR_freq: coordinates = "lon lat class"
    WDIR_freq: cell_methods = "time: point (interval: 40s)"
```

The information on interval over which the distribution is calculated should be defined by the `time_bnds`.

**Comment by Casthardi** [comment]
I am not quite happy with extensions in standard_names like "change_over_time" (as it is e.g. in "change_over_time_in_groundwater_amount""), "foo_over_time" and alike. This makes software development reading netCDF data more difficult and less straight foreward. In addition to checking the cell_methods attribute the software also has to check for the string "over_time" in the standard_name to distinguish whether the time bounds values should be used. It would be much better to have a cell_methods name handle the "over_time"  for these quantities (as it does for sum, mean etc.). Actually the description for the "over_time" standard_name reads: 
"The phrase 'change_over_time_in_X' means change in a quantity X over a time-interval, which should be defined by the bounds of the time coordinate"
Isn't this an ideal candidate for cell_methods?
For change over time for instance "time: change" or "time: difference" (the English natives should find the optimal wording here) would be a good solution from my point of view.

**Comment by JonathanGregory** [comment]
I agree with @neumannd that `interval` in  the `cell_methods` entry for time is the logical place to record the original time-interval. I think the method itself would be `sum` rather than `point` as the quantity refers to the whole of the cell in time.

Regarding the point of @Casthardi, I would say that standard names are not intended to be parsed. They are intended to be human-readable and constructed as systematically as we can, but they information they contain is very complex, with most possible distinctions not being mentioned in most names.

**Comment by Casthardi** [comment]
@JonathanGregory You write `standard names are not intended to be parsed`
This is exactly what I wanted to point to. But presently the standard names have to be parsed  to find standard names with "change_over_time" otherwise the software will not use the values of time bounds for these quantities because they don't have a cell method `time` that demands it.
I agree with your comment on the cell methods suggestion by Daniel that `point` is not appropriate. However, I think `sum` is not exactly what Beate has in mind. I think after summing up values of each class over the time period (which can be described by `sum`) in the next step these values are summed up over all classes and then each class is divided by this total sum.

**Comment by GeyerB** [comment]
I agree to a combination of all contributions to the discussion:
From Daniel that cell_methods are simple as we define everything concerning normalization in the description of the standard_name.
As mentioned by Burkhardt omitting `_over_time` in the end of the standard_name would lead to better machine readability. And the proposal of Jonathan to use `time: sum` seems to be correct as the variable itself is defined as `It is the number of events normalized by the sample size.`
So we end up with
```  
float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "probability_distribution_of_wind_from_direction";
    WDIR_freq: units = "1";
    WDIR_freq: coordinates = "lon lat class"
    WDIR_freq: cell_methods = "time: sum (interval: 40s)"
```

**Comment by JonathanGregory** [comment]
Dear Beate
If you omit `_over_time` the standard name will not be so informative. Something a user of the data might naturally ask is what independent variables were collapsed to make the PDF. Time is not the only possibility; it might be an ensemble statistic, for example. I think `_over_time` is a useful part of the description of the quantity in order to make it clear what it should be compared with. That is the purpose of standard names.
On the other hand, machine readability is *not* a consideration in the construction of standard names. They are intended to be readable by _humans_, to make the data self-explanatory. Their systematic nature is intended also to make them easier for humans, for not machines, to deal with. They may need to be treated as if they were intrinsically meaningless in application programs, like codes - but unlike codes, they are intelligible to humans.
Maybe that seems unhelpful! This sort of issue has been discussed a few times before. If there is a strong use-case for a particular "semantic" aspect of standard names to be processed by software, I think a reasonable way to do it would be to add a further tag specifying this property in the standard name table. Thus, programs could look it up in the table, rather than attempting to parse the name.
Best wishes, Jonathan

**Comment by Casthardi** [comment]
@JonathanGregory Then you mean we have to have both `_over_time` and cell_method `time: sum`? That's a compromise I can live with. In this case also the machine readability is covered. 
This would result in: 
```
float WDIR_freq(time,lat,lon,class);
    WDIR_freq: standard_name = "probability_distribution_of_wind_from_direction_over_time";
    WDIR_freq: units = "1";
    WDIR_freq: coordinates = "lon lat class"
    WDIR_freq: cell_methods = "time: sum (interval: 40s)"
```

**Comment by JonathanGregory** [comment]
Dear Burkhardt
Yes, that's right. The `cell_methods` indicates that the quantity is extensive in time. The `standard_name` provides an indication of _how_ it relates to time.
Cheers, Jonathan

**Comment by GeyerB** [comment]
Dear Alison,
we asked in our community and every one was satisfied with the result of the discussion - can the proposal be accepted now?

**Comment by japamment** [comment]
Dear Beate,

Reading through the discussion it seems that agreement has indeed been reached and thank you for checking again with your own community.

We are agreed on adding the standard name **probability_distribution_of_wind_from_direction_over_time** (Canonical units: 1). Following the Standard Name Guidelines and drawing together other existing text the definition would be:
'The construction "probability_distribution_of_X_over_Z" means that the data variable is a number in the range 0.0-1.0 for each range of X, where X varies over Z. The data variable should have an axis for X. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity"). The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. In meteorological reports, the direction of the wind vector is usually (but not always) given as the direction from which it is blowing ("wind_from_direction") (westerly, northerly, etc.). In other contexts, such as atmospheric modelling, it is often natural to give the direction in the usual manner of vectors as the heading or the direction to which it is blowing ("wind_to_direction") (eastward, southward, etc.).'

If you are happy with this, then the name can be accepted for publication.

Best wishes,
Alison

**Comment by GeyerB** [comment]
That is fine with us!!
How should we proceed to introduce the example in the conventions - should I open an extra issue once the new standard name table is public?
Beate

**Comment by japamment** [comment]
Dear Beate,

Many thanks. The name is accepted for publication in the standard name table and will be added in the March 9th update.

If you would like to add a new example to the conventions document the best way is to open an issue in the cf-convention/conventions repository. There are some general [guidelines](https://github.com/cf-convention/cf-conventions/blob/master/CONTRIBUTING.md) to contributing to the conventions and also a more detailed set of [rules](http://cfconventions.org/rules.html) for the procedure. Since this issue is now agreed I think it would be okay to go ahead - I don't think you need wait for publication of the standard name before proposing the example.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.

**Comment by feggleton** [comment]
Apologies, if you need this issue open for the other discussion which isn't standard names please reopen.
