### ISSUE TITLE
Duplicate ID in CF Standard Name aliases

### ISSUE THREAD

**Issue by DocOtak** [cf-convention/discuss#245]
This is mostly resurrecting an old issue from Trac: I was doing some updates of an internal mapping database at my group and finally noticed that the alias `surface_carbon_dioxide_mole_flux` is listed twice in the standard name xml document. I'm not the first one to notice this: https://cfconventions.org/Data/Trac-tickets/155.html

The trac ticket above references a [schema](https://cfconventions.org/Data/cf-standard-names/8/src/CFStandardNameTable-1.1.xsd) that defines the id attribute as being type [ID](https://www.w3.org/TR/xml/#id) which does not allow for duplicate values for any element in the document. I suspect the original suggestion of having more than one `entry_id` element per alias is probably the correct way do support one to many aliasing.

**Comment by larsbarring** [comment]
cf. [cf-convention/#132](https://github.com/cf-convention/cf-conventions/issues/132)

**Comment by JonathanGregory** [comment]
As Lars @larsbarring has pointed out, this issue is also being addressed by an issue in the [conventions repo](https://github.com/cf-convention/cf-conventions/issues/132). That's a suitable place to resolve it, because it would require a change to the format of the standard name table, which is defined by Appendix B. Therefore I'm closing this issue now. Thanks.
