### ISSUE TITLE
 Correction of canonical unit for `product_of_air_temperature_and_specific_humidity`

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/discuss#254]
In standard name table v. 82 (and earlier) `product_of_air_temperature_and_specific_humidity` has canonical unit **`K`**, which would imply that it is a temperature quantity, which it is not. As it in fact is a product I believe the correct canonical unit is **`K 1`**. Note that the ***`1`*** *is a unit in itself*, not the integer **1**, which can be removed. This becomes evident if one considers that the specific humidity could be reported in units `g kg-1` or `kg kg-1`  (and more), instead of the canonical unit `1` .

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

I don't agree with this proposal, because `K 1` is exactly equivalent to `K` in both SI and UDUNITS, and so is `1 K`. The canonical unit is `K`. Quantities with this unit are not necessarily temperatures. For example, the empirical inversion strength of the troposphere is a quantity in `K`, but it's not a temperature. It has that unit because it's derived from a temperature difference.

You've pointed to a pitfall for units conversion of `product_of_air_temperature_and_specific_humidity`, which I suggest should be stated in the definition of this quantity and of `specific_humidity`. Specific humidity is a mass fraction. It is not explicitly stated, and probably it should be, that it's the ratio of one mass to another when they are in the same units. If it is `g kg-1` rather than `kg kg-1`, it should have `units="1e-3"` for instance, and that would carry over to `product_of_air_temperature_and_specific_humidity`.

Best wishes

Jonathan
