### ISSUE TITLE
CF meeting in 2024: Plans and dates

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#276]
Dear CF community,

We would like to announce the plans for the 2024 CF meeting, held in person at **SMHI, Norrköping, Sweden**. The meeting will be a **four day meeting**. The exact dates have not been decided, but it will be certainly be during the three week period of **9th - 27th September 2024**. If you know of any potential synergies or clashes with other meetings, please let us know. The meeting dates will be finalised towards the end of February. 

* In a change from the usual arrangement, the meeting will be divided into two parts, and meeting participants may choose to attend the first two days of the programme, the last two days, or the whole meeting, according to their own interests and availability.
  - **Part 1 (days one and two)**: Engaging the cross-domain CF community to gather user needs and develop a high-level CF roadmap.
  - **Part 2 (days three and four)**: Detailed CF development including hackathon sessions (days three and four).

* The plan for **Part 1** of the workshop is to invite speakers from a broad range of CF users and potential users, for example, representatives of data producers and data archives in the earth system sciences, the health and biological research communities.
  * The aim is to maximise the usefulness of CF to a wide range of communities, encourage others to join and contribute to the CF community effort, and enhance interoperability with other widely used standards. 
  * The desired outcome is a publication of the proceedings, including a roadmap for development of the CF conventions and vocabularies over the next 1 to 5 years.

* **Part 2** will follow the familiar format of our usual annual meeting.

An organising committee is in the process of being formed, and we would like to invite anyone who wants to participate. No prior experience is necessary (but if you have been involved with organising CF workshops in the past you are equally welcome), just an ability to commit to regular on-line meetings  - one per month at the start, and increasing in frequency nearer the meeting date. 

Many thanks,
Lars Bärring, Ethan Davis, David Hassell, Alison Pamment

**Comment by erget** [comment]
Great initiative!

EUMETSAT has its STG-OPS Working Group meeting on 12 and 13 September 2024, so some of the folks here (or our Member State delegates) would be blocked during that time.

Otherwise I'm not aware of any major conflicts.

**Comment by efisher008** [comment]
Dear Lars, Ethan, David and Alison,

Thank you very much for the information about possible dates and provisional plan for the meeting. 

For me there doesn't seem to be any conflicts/overlap for those weeks in September. The [EUMETSAT Meteorological Satellite Conference](https://www.eumetsat.int/eumetsat-meteorological-satellite-conference-2024) runs from the 30th September - 4th October in Würzburg (so after the timeframe being considered). From a quick look, there's also a [WMO-IMO Symposium on Extreme Maritime Weather](https://wmo.int/events/meeting/2nd-wmo-imo-symposium-extreme-maritime-weather-bridging-knowledge-gap-towards-safer-shipping-0) from the 22nd-25th September - I'm not sure if that's likely to be on the radar of those attending the CF meeting, but perhaps worth noting.

And if you're still welcoming participants to the organising committee, I'd like to express interest for this! It will be a good opportunity to get more involved in the running of CF events and help with some of the practicalities. 

Best regards,
Ellie

**Comment by larsbarring** [comment]
Regarding availability of rooms and facilities it turn out that the last of the three alternative weeks, 23-27 September is not possible (anymore) because of another workshop. But the two weeks 9-13, and 16-20 are available. And I have preliminary booked rooms. Preferably, we need to decide fairly soon.

Kind regards,
Lars

**Comment by efisher008** [comment]
I think as Daniel (@erget) mentioned, the EUMETSAT STG-OPS Working Group meeting is happening during the first of those weeks (12th-13th September), perhaps the freest sounding period would be the second week (16th-20th)? Although, I've just seen that the International Conference on Atmospheric Science, Computational Methods and Meteorology (ICASCMM) is due to take place on the 20th-21st in Paris. The 16th-19th would therefore be possible for a four-day meeting, and would theoretically allow for participants to travel on the weekend preceding the event. But if anyone is strongly against this, we should definitely have a longer discussion.

Kind regards,
Ellie
