### ISSUE TITLE
 Standard names: add variable for wave energy flux

### ISSUE THREAD

**Issue by meteolien** [cf-convention/discuss#280]
**Date** - 23/02/2024

Meteolien would like to proposed the following new terms for addition to the CF standard names. 
In fact, we are currently working on a dataset with NetCDF format, destinated to be published in the european ODATIS platform. 
This dataset is an Atlas of the wave energy flux. It appears that the variable describing the wave energy flux is not listed in the CF Standard Name Table.

In the IEC standard 62600-100 for Marine Energy, this variable is named "wave energy flux" or "wave power" and is noted J with unit W/m.

**Term** - Sea_surface_omnidirectional_wave_energy_flux_in_deep_water_conditions
(Update 27/02/24 - Standard name proposed  : `sea_surface_wave_energy_flux`)

**Description** - Wave energy flux, or wave power, is the average rate of transfer of wave energy through a vertical plane of unit width perpendicular to the direction of wave propagation. It should be understood as omnidirectional, or as the sum of all wave power components regardless of direction. 
In deep water conditions, the wave energy flux can be obtained with the water density, the wave significant height and the energy period.

**Units** - W m-1.

**Comment by JonathanGregory** [comment]
Thanks for the proposal. I have some comments (which may be ill-informed, since I know little about this).

* I think it would be better to omit `omnidirectional`, for two reasons.
   1. `sea_surface_wave_energy_at_variance_spectral_density_maximum` also refers to the integral over all directions, and its description says it would be called `directional` if it wasn't omnidirectional (in your sense). That is, "omnidirectional" is the default. 
   2.  `omnidirectional` has a different meaning in `omnidirectional_photosynthetic_spherical_irradiance_in_sea_water`. Introducing it n your sense for sea surface waves could cause confusion.

* Can we omit `in_deep_water_conditions`? Your description text suggests that this quantity isn't defined specifically or differently for deep water, but just that there's a particular way to calculate it in deep water. If it's the same physical quantity in deep and shallow water, we shouldn't have the qualification.

* I may have asked this before (in previous issues) but I note that sea surface wave energy names don't appear to have units of energy - there is no `kg` in the unit. Why is that?

Jonathan

**Comment by meteolien** [comment]
Thank you for your comments.
Indeed, the physical quantity is the same in deep and shallow water, it is only the way it is computed that can be simplified in deep water. In addition, if 'omnidirectional' is the default, the standard name of the variable J could be `Sea_surface_wave_energy_flux`.

To answer your question, the watts have the unit kg.m².s^-3.

**Comment by meteolien** [comment]
In fact, it is not the same quantity. The variable `sea_surface_wind_wave_energy_at_variance_spectral_density_maximum` is a spectral energy density E(f) [m².s-1]. E is the variance of the sea surface elevation and f is the wave frequency. For convenience, the elevation variance E is (abusively) called 'energy' but the true energy, in Joules per unit surface, is rho.g.E. 

The wave energy flux (`Sea_surface_wave_energy_flux`) also denoted wave power density or wave energy potential [W.m-1] is evaluated as an integral of the spectral energy density E(f).

**Comment by JonathanGregory** [comment]
Thanks for that useful clarification, @metolien. I wonder whether _E_(_f_) is in `m2 s`, rather than `m2 s-1`, as you write? It isn't spectral  energy density either, but elevation variance spectral density, i.e. elevation variance (`m2`) per unit frequency (`Hz-1`=`s`). When you integrate it over all frequencies, you get elevation variance in `m2`. Then you multiply by rho g (I guess) to get `m2 kg m-3 m s-2`=`kg s-2`. To get a power per unit length perpendicular to the wave direction I suppose you multiply by the speed of the wave, `kg s-2 m s-1`=`kg m s-3`=`W m-1`. Is that right?

Given your explanation, I think we ought to replace the following existing standard names, with aliases for backwards compatibility as usual:

```
sea_surface_primary_swell_wave_energy_at_variance_spectral_density_maximum
sea_surface_secondary_swell_wave_energy_at_variance_spectral_density_maximum
sea_surface_tertiary_swell_wave_energy_at_variance_spectral_density_maximum
sea_surface_wave_energy_at_variance_spectral_density_maximum
sea_surface_wind_wave_energy_at_variance_spectral_density_maximum
```

which are all in `m2 s`, by replacing `wave_energy_at` with `wave_elevation` i.e.

```
sea_surface_primary_swell_wave_elevation_variance_spectral_density_maximum
sea_surface_secondary_swell_wave_elevation_variance_spectral_density_maximum
sea_surface_tertiary_swell_wave_elevation_variance_spectral_density_maximum
sea_surface_wave_elevation_variance_spectral_density_maximum
sea_surface_wind_wave_elevation_variance_spectral_density_maximum
```

Would these names be correct? If so, I will propose this change as a separate issue from this one because, as you explain, they aren't actually energy. It would be inconsistent to continue to call them "energy" if we include your new name for "energy flux", which is actually a flux of energy. We can insert a sentence in their descriptions to say that the wave elevation variance is often called "wave energy", because if you multiply it by rho g you get energy per unit area.

**Comment by meteolien** [comment]
Yes indeed, `sea_surface_wind_wave_energy_at_variance_spectral_density_maximum` is in m2.s (or m2.Hz-1).
And yes, to get the power unit per unit length perpandicular to the wave direction, E(f) [m2.s] is multiplied by the "group velocity" Cg (speed of the overall envelope shape of the wave's amplitude) [m.s-1] and thus we get the wave energy flux CgE in [kg.m.s-3]=[W.m-1]

I agree with your analysis but maybe there is a specific reason to distinguish the elevation variance *at* variance spectral density maximum and the elevation variance spectral density maximum but I do not know it...

**Comment by JonathanGregory** [comment]
OK, fine. To reiterate, I think `sea_surface_wave_energy_flux` is fine as a new standard name, with the description and units you initially proposed.

Once this issue is concluded, for the new name, I'll open another one about the existing `wave_energy` names. Thanks.

**Comment by efisher008** [comment]
Hello,

The standard name `sea_surface_wave_energy_flux` has been added to the editor. You can view the entry here: https://[cfeditor.ceda.ac.uk/proposal/5274/edit](https://cfeditor.ceda.ac.uk/proposal/5274/edit)

As it looks as though there is agreement about this, I will add the tag "accept within 7 days". If there are no further comments within this period, the name will be accepted and published in the next standard names table release. I can see there will be another issue opened by Jonathan for changes to existing `wave_energy` names given the discussion. That's fine.

Could we have an author for the proposal to add to this entry, please? This is generally the full name of the person responsible for creating the GitHub issue. It would be used to add to the list of contributors for the standard name table.

Best regards,
Ellie

**Comment by meteolien** [comment]
Hello! And sorry for the late reply.

I have added my name as "Proposer" in the editor.
Thank you for validating the standard name. Do you know when is the next
standard name table release?
Thank you in advance!
Best regards,

-- 

Marie Peniguel--Raffray

Ingénieure d'études | M.Sc. Renewable Energy


Meteolien ScopARL 26/28 rue Marie Magné 31300 Toulouse tel : +33 5 61 72 55
21

Le ven. 8 mars 2024 à 15:58, Ellie Fisher ***@***.***> a
écrit :

**Comment by efisher008** [comment]
Hello, 

I have now marked the name as accepted and it will appear in the next standard names table release, which is planned for the first half of April. Thanks again for the proposal!

Best regards,
Ellie

**Comment by efisher008** [comment]
Closing this issue as this name has been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
