### ISSUE TITLE
CF Parameters for partial pressure of carbon dioxide in sea water

### ISSUE THREAD

**Issue by iwensu0313** [cf-convention/discuss#295]
Hi there,

Is there a difference between `partial_pressure_of_carbon_dioxide_in_sea_water` and `surface_partial_pressure_of_carbon_dioxide_in_sea_water`, as they have the same exact definition and canonical units ([CF Standard Name Table](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html)):

<img width="1200" alt="Screenshot 2024-03-11 at 3 11 55 PM" src="https://github.com/cf-convention/discuss/assets/9053844/049a7c56-d3df-4acf-9b74-4d991ea76fd4">

When might you use one or the other?

Cheers

**Comment by taylor13** [comment]
the partial pressure can be measured/reported anywhere throughout the column of water, but the surface partial pressure is the value that would be seen by the atmosphere above.  So only use surface partial pressure when you are reporting the partial pressure at the surface.  We should augment the description so that this is made clear.  
In the standard names there are several cases where we define a "surface" version of a more general standard name.
When reporting the partial pressure beneath the surface, one should include a vertical coordinate indicating the depth.

**Comment by iwensu0313** [comment]
Thanks @taylor13! That makes sense and is incredibly helpful.
