### ISSUE TITLE
New description for equivalent_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#30]
old: No help available

new:
The equivalent temperature is the temperature that an air parcel would have if all water vapor were condensed at constant pressure and the enthalpy released from the vapor used to heat the air.
It is the **isobaric** equivalent temperature and not to the **adiabatic** equivalent temperature (also known as pseudoequivalent temperature, see variable pseudo_equivalent_temperature).
Reference AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_temperature
The equivalent temperature is the temperature of a parcel of air if all the moisture contained in it were condensed, releasing latent heat.

Beate and Ronny

**Comment by japamment** [comment]
@GeyerB ,

Many thanks for proposing this change. We should definitely add some definition text for this name which has been in the standard name table since version 1!

As discussed and agreed with @roy-lowry in [#20](https://github.com/cf-convention/discuss/issues/20) we should add 'air_' at the start of the name for clarity. Hence we will be creating the alias equivalent_temperature -> air_equivalent_temperature.

I agree that in the definition it is very useful to point out the difference between the standard names air_equivalent_temperature and air_pseudo_equivalent_temperature. I would suggest leaving off the last sentence as it is essentially repeating the first which is taken from the AMS glossary. I have made a couple of other cosmetic changes to the wording and suggest it should be:
'The equivalent temperature is the temperature that an air parcel would have if all water vapor were condensed at contstant pressure and the enthalpy released from the vapor used to heat the air. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_temperature. It is the isobaric equivalent temperature and not the adiabatic equivalent temperature, also known as pseudoequivalent temperature, which has the standard name pseudo_equivalent_temperature.'

Is this okay? If so, I think this name is ready to be accepted.

Best wishes,
Alison

**Comment by japamment** [comment]
Correction: the last sentence of the definition should refer to air_pseudo_equivalent_temperature since we are also updating that name in #32.

**Comment by GeyerB** [comment]
Excellent, thanks for the work!!

**Comment by japamment** [comment]
@GeyerB many thanks. This name is accepted for publication in the standard name table and will be added in the 9th March update.

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
