### ISSUE TITLE
 New description for pseudo_equivalent_potential_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#31]
old: Potential temperature is the temperature a parcel of air or sea water would have if moved adiabatically to sea level pressure.

new:
The pseudo equivalent potential temperature is the temperature a parcel of air would have if it is expanded by a pseudoadiabatic (irreversible moist-adiabatic) process to zero pressure and afterwards compressed by a dry-adiabatic process to a standard pressure (typically mean sea level pressure or 1000 hPa).
Pseudoadiabatic process means that the liquid water that condenses is assumed to be removed as soon as it is formed.
To specify the standard pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.

Beate and Ronny

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for your proposal to update this description.

As agreed with @roy-lowry in [#20](https://github.com/cf-convention/discuss/issues/20) we should add 'air_' at the beginning of the name for clarity. Hence we are creating the alias pseudo_equivalent_potential_temperature -> air_pseudo_equivalent_potential_temperature.

The new description you propose looks fine. I've added a couple of references to the AMS glossary pages but otherwise kept it the same:
'The pseudoequivalent potential temperature is the temperature a parcel of air would have if it is expanded by a pseudoadiabatic (irreversible moist-adiabatic) process to zero pressure and afterwards compressed by a dry-adiabatic process to a standard pressure (typically mean sea level pressure or 1000 hPa). Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Pseudoequivalent_potential_temperature. A pseudoadiabatic process means that the liquid water that condenses is assumed to be removed as soon as it is formed. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Pseudoadiabatic_process. To specify the standard pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.'

If you are happy with this then I think the name is ready to be accepted for publication.

Best wishes,
Alison

**Comment by GeyerB** [comment]
Fine with me!!
In all other definitions the '1000 hPa' were killed - perhaps they shouldn't survive this time either??

Thanks a lot,
Beate

**Comment by japamment** [comment]
Dear Beate,

Yes, good point. I'll change the first sentence to say 'The pseudoequivalent potential temperature is the temperature a parcel of air would have if it is expanded by a pseudoadiabatic (irreversible moist-adiabatic) process to zero pressure and afterwards compressed by a dry-adiabatic process to a standard pressure, typically representative of mean sea level pressure.' That will match the other names!

This change is now accepted for publication in the standard name table and will be added in the March 9th update.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
