### ISSUE TITLE
 New description for pseudo_equivalent_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#32]
old: No help available

new:
The pseudoequivalent temperature is also known as the **adiabatic** equivalent temperature. It is the temperature that an air parcel would have after undergoing the following process: dry-adiabatic expansion until saturated; pseudoadiabatic expansion until all moisture is precipitated out; dry- adiabatic compression to the initial pressure.
Reference AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_temperature

Beate and Ronny

**Comment by japamment** [comment]
Dear Beate and Ronny,

Many thanks for this proposal. This is another quantity that has been in the standard name table since version 1 and lacks a description.

As agreed with @roy-lowry in [#20](https://github.com/cf-convention/discuss/issues/20) we should add 'air_' at the beginning of the name for clarity. Hence we are creating the alias  pseudo_equivalent_temperature -> air_pseudo_equivalent_temperature.

To make the definition consistent with the one being suggested for air_equivalent_temperature I suggest we again point out the difference between the two terms:
'The pseudoequivalent temperature is also known as the adiabatic equivalent temperature. It is the temperature that an air parcel would have after undergoing the following process: dry-adiabatic expansion until saturated; pseudoadiabatic expansion until all moisture is precipitated out; dry- adiabatic compression to the initial pressure. Reference AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_temperature. This quantity is distinct form the isobaric equivalent temperature, also known as equivalent temperature, which has the standard name air_equivalent_temperature.'

Is this okay? If so, I think this name is ready to be accepted.

Best wishes,
Alison

**Comment by GeyerB** [comment]
@japamment - yes, that is fine with us!
Thanks for the work!!

**Comment by GeyerB** [comment]
This is fine with us, thanks for the work,
Beate

**Comment by japamment** [comment]
@GeyerB many thanks. This name is now accepted for publication and the change will be added in the March 9th standard names update.

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
