### ISSUE TITLE
 Standard names: renaming of atmosphere_absolute_vorticity to atmosphere_upward_absolute_vorticity

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#40]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2020/03/11

**- Term** atmosphere_upward_absolute_vorticity
**- New Definition** The vorticity is a vector quantity. "Upward" indicates a vector component which is positive when directed upward (negative downward). Atmosphere upward absolute vorticity is the sum of the atmosphere upward relative vorticity and the vertical component of vorticity due to the Earth’s rotation.
**- Units** s-1

**Comment by feggleton** [comment]
Hi Beate and Ronny,

Thank you for your request. As similarly mentioned in issue #38 

The changes here would be:

From atmosphere_absolute_vorticity to atmosphere_upward_absolute_vorticity
Definition from: Absolute vorticity is the sum of relative vorticity and the upward component of vorticity due to the Earth's rotation.

to: The vorticity is a vector quantity. "Upward" indicates a vector component which is positive when directed upward (negative downward). Atmosphere upward absolute vorticity is the sum of the atmosphere upward relative vorticity and the vertical component of vorticity due to the Earth’s rotation.

This would be amending the phrase "Absolute vorticity is the sum of relative vorticity and the upward component of vorticity due to the Earth's rotation." to "Atmosphere upward absolute vorticity is the sum of the atmosphere upward relative vorticity and the vertical component of vorticity due to the Earth’s rotation."

It would be great to get some discussion going here about the changes to the vorticity names (there are 6 in the standard name table), if the definitions are appropriate and if people think this detail is needed for clarification. When you say upward are you referring to the vertical vorticity? In which can would we also need horizontal vorticity names? In this case, would we have 2 new names (vertical and horizontal of the term) in addition to the existing names instead of amending the existing names? Just some questions to think about for all of these requests, not suggesting I am right or have the answers.  This term is now in the cfeditor.

Thanks

**Comment by awill-btu** [comment]
I would like to support the suggestion of Beate Geyer.  Indeed, vorticity is a vector quantity (see J. Pedlosky, Geophysical Fluid Mechanics, second edition, p.22). Thus, a direction information is needed. 
Nevertheless the term "vorticity" is used to name its vertical component, since 1. the atmospehre is stratified and 2. the most scientists consider mid-latitudes and not the tropics. I suggest to rename the quantity and to start with the definition  and not with additional explanations in the following way:
new: Atmosphere upward absolute vorticity is the sum of the atmosphere upward relative vorticity and the vertical component of vorticity due to the Earth’s rotation. The vorticity is a vector quantity. "Upward" indicates a vector component which is positive when directed upward (negative downward).

**Comment by feggleton** [comment]
Thank you @awill-btu for the clarification. That sounds good. I agree with the re-arrangement. As this definition mentions atmosphere_upward_relative_vorticity in a sense, it would make sense to agree these together. I will also write a comment in that issue ticket. If there are any further comments then please add now. I will check back in a couple of days as this appears to be close to acceptance. The cfeditor has been updated to reflect the changes above.

**Comment by japamment** [comment]
Dear Beate, Ronny, Andreas, Francesca, @GeyerB @awill-btu @feggleton 

Thank you for this proposal and the comments. I think agreement has been reached on creating the following alias:
**atmosphere_absolute_vorticity** -> **atmosphere_upward_absolute_vorticity** (Canonical units: s-1).
The definition has been clarified and will read as follows:
'Atmosphere upward absolute vorticity is the sum of the atmosphere upward relative vorticity and the vertical component of vorticity due to the Earth’s rotation. In contrast, the quantity with standard name atmosphere_upward_relative_vorticity excludes the Earth's rotation. Vorticity is a vector quantity. "Upward" indicates a vector component which is positive when directed upward (negative downward). A positive value of atmosphere_upward_absolute_vorticity indicates anticlockwise rotation when viewed from above.'

The definitions of atmosphere_upward_absolute_vorticity and atmosphere_upward_relative_vorticity [(#38)](https://github.com/cf-convention/discuss/issues/40) are now written consistently and cross-reference one another.

This change is accepted for publication in the standard name table and will be added in the September update.

Best wishes,
Alison

**Comment by japamment** [comment]
This proposal has been accepted and published in version 75 of the standard name table. Closing this issue now.
