### ISSUE TITLE
 Standard names: Standard names for Acoustic Doppler Current Profiler data

### ISSUE THREAD

**Issue by hhourston** [cf-convention/discuss#56]
**Hana Hourston, Di Wan**  
**June 15, 2020**  

We would like to propose several standard names for ADCP (Acoustic Doppler Current Profiler) data as part of an effort to improve the compliance of ADCP data with CF Standards that is processed at the Institute of Ocean Sciences.  

**-Term:**  sea_water_velocity_error_by_adcp
**- Description:** A velocity is a vector quantity. The error velocity is the difference between two estimates of vertical velocity, one estimate from the East-West pair of beams and the other from the North-South pair of beams. Source: https://www.physics.mun.ca/~bdeyoung/P6314/doc/Broadband%20Primer.pdf
**- Units:** m s-1

**- Term:** echo_intensity_in_sea_water_by_adcp
**- Description** Echo intensity from the sea water body in counts by moored acoustic doppler current profiler. Echo intensity data are output in units proportional to decibels (dB). Data are obtained from the receiver’s received signal strength indicator (RSSI) circuit. Source: https://www.physics.mun.ca/~bdeyoung/P6314/doc/Broadband%20Primer.pdf
**- Units:** 1

**- Term:** percent_good_signal_returns_in_sea_water_by_adcp
**- Description:** Acceptable proportion of signal returns as a percentage by moored acoustic doppler current profiler. Percent-good data indicate what fraction of data passed a variety of criteria. Rejection criteria include low correlation, large error velocity and fish detection (false target threshold). Default thresholds differ for each ADCP; each threshold has an associated command. Source: https://www.physics.mun.ca/~bdeyoung/P6314/doc/Broadband%20Primer.pdf
**- Units:** 1

**- Term:** correlation_magnitude_in_sea_water_by_adcp
**- Description** Correlation magnitude of acoustic signal returns in counts from the water body by moored acoustic doppler current profiler. Correlation is a measure of data quality, and its output is scaled in units such that the expected correlation (given high signal/noise ratio, S/N) is 128. Source: https://www.physics.mun.ca/~bdeyoung/P6314/doc/Broadband%20Primer.pdf
**- Units:** 1

**Comment by reynaj** [comment]
?We'd also appreciate the introduction of these new terms for ADCPs, and had been planning to make a similar request - so, thank you Hana.


The only one I'm curious about is the platform_heading since we'd been using platform_orientation for that same purpose. Is that the same?


Reyna Jenkyns | Data Stewardship Manager
Ocean Networks Canada | T 250 853 3908 | M 250 415 3336 | oceannetworks.ca
#100-2474 Arbutus Road, Victoria, BC, V8N 1V8

ORCID: 0000-0001-6975-6816


A UNIVERSITY OF VICTORIA INITIATIVE



________________________________

**Comment by hhourston** [comment]
Platform_orientation is the same - thank you @reynaj, as I hadn't seen that name! I will remove platform_heading from my original request.

**Comment by roy-lowry** [comment]
Initial reactions to start a discussion. The Standard Names are descriptors of the geophysical variable. Consequently, they do not include information on methodology or statistical derivatives. They also should not include units of measure such as 'percent'.

Methodology information, such as _by_adcp, would have to be included in the long name rather than the standard name parameter attribute. 

The way error information has been handled in CF is through ancillary variables linked to the primary variable and labelled using a standard name plus standard name modifier as listed in Appendix C of the CF Conventions. One of the standard name modifiers is 'standard_error' so, assuming the standard_error definition is OK for your use case, you could have a standard name of 'upward_sea_water_velocity standard_error' (note the space between velocity and standard). If it isn't OK the a new standard name modifier would need to be set up as part of your request. 

Statistical derivative information is handled in CF by the use of cell method attribute in addition to the standard name attribute. There are 17 cell methods specified in Appendix E of CF 1.8. None of these seem to me to cover 'correlation magnitude', so a new cell method would need to be specified. However, as the correlation magnitude is a kind of error estimate could that also be handled as a standard name modifier.

In fact all of your proposal could be handled through standard name modifiers. Something like:

acoustic_signal_in_sea_water echo_intensity
acoustic_signal_in_sea_water good_returns
acoustic_signal_in_sea_water correlation_magnitude

Others may have different views on this.

**Comment by JonathanGregory** [comment]
I agree with Roy that the ACDP quantities aren't the usual kind of thing we describe with a standard name. If I understand you correctly, the geophysical quantity being measured by ACDP is `upward_sea_water_velocity`, which is an existing standard name. The error, echo intensity, proportion of good returns, and correlation magnitude are all metadata about the acoustic signal used to derive the `upward_sea_water_velocity`. Is that right? Except for the error (if it is a standard error) these kinds of metadata seem specific to ACDP, so I'm not sure that standard name modifiers would be appropriate - they are rather generic. Maybe some further kind of controlled vocabulary is needed for instrument-derived metadata of this kind. I suppose that similar questions must arise for other types of observational data and I wonder what has been done. As Roy says, the `long_name` can always be used. Its content is not standardised by CF, but of course it could be standardised as an extra convention by particular interest groups.

**Comment by roy-lowry** [comment]
Dear Jonathan,
Technical clarification. The ADCP projects four sound beams upwards and from these the northwards, eastwards and upwards water velocities are resolved. The signal good returns, correlation magnitude and intensity are metadata parameters for all three current components.  The error velocity is a true measure of vertical velocity uncertainty based on duplicate measurements. Whether or not it's a standard error is beyond my statistical knowledge.

**Comment by JonathanGregory** [comment]
Dear Roy

OK - thanks. Since the metadata applies to all components, describing it with a standard_name modifier would be awkward. (I recall a long unresolved discussion about a similar thing.) These variables, then, are quantities in their own right, but they are data about a detector, not about the world. We do have some standard names like that, such as the many platform_ standard names. If they are commonly used quantities, which people want to put in netCDF files, I can see there's an argument for giving them standard names. I wonder what others think.

Cheers

Jonathan

**Comment by ngalbraith** [comment]
Thank you, Hana, for bringing forward this proposal. I looked into some of these names a long time ago, and I support adding them. Using long names and trying to standardize them outside of CF has not panned out very well in the past.  A similar concept (and precedent) is the standard name 'temperature_of_sensor_for_oxygen_in_sea_water' which is not a measurement of the water temperature, but is used as metadata about the oxygen value.

Also, I'd like to clarify that the error velocity produced by an ADCP is not a standard_error, and is a measure of uncertainty of **all** the velocities returned by the instrument. The details of how it's computed are lost (to me) now, but I don't think it's appropriate to use the standard_error modifier for this variable.

**Comment by roy-lowry** [comment]
I was going by Hana's description for the error velocity which is 'The error velocity is the difference between two estimates of vertical velocity, one estimate from the East-West pair of beams and the other from the North-South pair of beams.' I must admit my understanding of the term 'error velocity' from when I handled ADCP data was that it was as you say - an error estimate over all three components. 

However, as Hana's description was so explicit I assumed it was something different - hence my leading the Standard Name formation in the direction I did.

Can somebody please clarify?

**Comment by oceanscience** [comment]
FYI - identifiers from BODC P01: 
http://vocab.nerc.ac.uk/collection/P01/current/CMAGZZ01/
http://vocab.nerc.ac.uk/collection/P01/current/TNIHCE01/

**Comment by roy-lowry** [comment]
Might be worth pointing out that those P01 concepts are members of groups of four describing correlation magnitude and echo intensity separately for each of the four beams.  I tried opening up the primer to see if I could get any insight on what Hana wishes to describe but it timed out - behind a firewall perhaps? Could somebody possibly e-mail me a copy (rkl@bodc.ac.uk)?

Can anybody tell me whether the four beam values are merged to produce a single variable or was the intention to use the same Standard Name for each of four variables in the data file?

I should clarify that my intention is to propose straw man Standard Names rather than go down the modifier route once I have a clear understanding of how they are to be used.

**Comment by roy-lowry** [comment]
Thanks to Hana I now have the ADCP primer, a document dated 1996, which I should maybe have read years ago. It was certainly a revelation to me that the error velocity I worked with for years was not derived from all three velocity vectors but is and always has been a measured uncertainty in the vertical velocity that provides an indication of the quality of the horizontal velocity component measurements.

Now I know what it is, the question remains as to how to label it in CF. 

Option 1)  Don't assign a Standard Name and set the long name to 'error velocity' which is a term familiar to all who work with ADCP data. 

Option 2) Describe the measurement made using the existing Standard Name plus a new Standard Name modifier 'upward_sea_water_velocity error' where error is defined as something like 'uncertainty determined from duplicate determination of a measurement. 

Option 3) Set up a Standard Name like 'sea_water_velocity_error_velocity'. I know this repeats the word velocity, but error_velocity is such a well-known term that I think it is justified.

My current preference is option 3.

The primer didn't help me as to whether to expect one echo intensity etc. per time step in an ADCP data file or four of them (one per beam) per time step. Can anybody supply this information?

**Comment by hhourston** [comment]
@roy-lowry ADCP data files contain one echo intensity, etc. per beam per time step, summing to four (one per each beam) per time step for most ADCPs. I will note that since RDI Sentinel V instruments have five beams (four angled ones plus a vertical beam), data files from such instruments will have five echo intensities, etc. per time step.

**Comment by JonathanGregory** [comment]
I think that if we give these quantities standard names, we should use terminology which is more self-explanatory and less jargon e.g.

  * multibeam_acoustic_doppler_velocity_sensor_in_sea_water instead of "ACDP", to avoid an abbrevation and because "ACDP" and "SODAR" are the same kind of instrument in different media, so a generic description is better

  * indicative_error_in_sea_water_velocity for "error velocity"

  * proportion_of_acceptable_signal_returns

  * a replacement for "correlation magnitude", which I can't suggest because I don't know what it means!

On the other hand, if it is preferable to stick with the familiar terms, it would be better to use a long name, or invent an extra ACDP netCDF convention to define a non-CF attribute, and standardise its use within the expert community concerned.

**Comment by roy-lowry** [comment]
@hhourston Many thanks. That confirms what I suspected. When I handled ADCP data disk space was expensive (£400,000 for less than 1 Gigabyte) so the metadata channels got dumped before the data came to me as a data manager so I never saw them.

On the basis of Hana's answer a question to the likes of @japamment and @JonathanGregory who are familiar with Standard Name history and rules. For reasons of semantic interoperability (vocabulary mapping) I would love to have one Standard Name per beam. However, I fear that this is pushing the Standard Name concept too far and that the beams would need to be differentiated through the long name. Could I have opinions on this please before I go further?

**Comment by graybeal** [comment]
@roy-lowry by "one Standard Name per beam", do you mean for a four-beam unit, each of the measurement types would have 4 standard names, with some suffix like "_for_beam_1"? I am wondering what the suffix pattern would be that would be unambiguous for every ADCP type. 

Certainly having a different name for the vertical beam values in the 5-beam case seems called for, because they are measuring a fundamentially different thing (sorta like 'upward' vs 'downward' radiation, but 'upward' vs 'sideward'. Sorry, that might be a little punchy!)

**Comment by roy-lowry** [comment]
Hi John,

The question I was considering was indeed four standard names per measurement. I'll worry about the syntax in what I think is the unlikely event of it gaining widespread support.

I've not seen a Sentinel 5 but have handled plenty of RDI 4-beam instruments and all the transducers on them point upwards with a small offset from vertical.  I don't think an orientation difference of a few degrees constitutes anything fundamental.

**Comment by ngalbraith** [comment]
WRT Jonathan's comment, I like the term 'proportion_of_acceptable_signal_returns' because it could be used for other types of data, not just from ADCPs. I don't know if acoustic anemometers return this field, but they may, or may soon.

I'm confused by multibeam_acoustic_doppler_velocity_sensor - are you proposing using that in all the names, e.g. instead of sea_water_velocity_error_by_adcp, using
sea_water_velocity_error_by_multibeam_acoustic_doppler_velocity_sensor_in_sea_water?
If so, could we use sea_water_velocity_error_by_acoustic_sensor - which would remove some of the redundancy without (IMHO) losing clarity.  I'm suggesting this because there may be some other acoustic instruments that report this, but which are not  multibeam ADCPs.

WRT to Roy's comment, I'd much prefer to have a single standard name per concept; we sometimes record these as multidimensional variables, with the bin number as a dimension, and using different standard names rules out that option.  The number of beams can be described by instrument metadata, or inferred from the data itself. Furthermore, adding a suite of these standard names for different instruments could be a long road; if P01 has different entries for specific bins, we can surely deal with that.

**Comment by roy-lowry** [comment]
I've made an attempt to draw together the discussion above. I've tried to word the descriptions to include well known phrases as search targets and to include other oceanographic acoustic instrumentation as well as ADCPs. I've also worded the error velocity definition so as not to exclude the Sentinel V.

@ngalbraith I think I've worked out a way around the mapping issue by setting up synonym P01 concepts for the new Standard Names. I'll discuss this with Gwen once this ticket is completed.

indicative_error_in_sea_water_velocity

Sea water velocity is a vector quantity that is the speed at which water travels in a specified direction. The indicative error is an estimate of the quality of a seawater velocity profile measured using an ADCP (acoustic doppler current profiler). It is determined by differencing duplicate error velocity measurements made using different pairs of beams. The parameter is frequently referred to as the error velocity.

m s-1

proportion_of_acceptable_signal_returns

The fraction of a collection (ensemble) of returned signal transmissions that have passed a set of automatic quality control criteria. For an ADCP (acoustic doppler current profiler) the rejection criteria include low correlation, large error velocity and fish detection. The dimensionless proportion is often but not exclusively expressed as a percentage when it is referred to as percent good.

1

acoustic_signal_intensity_in_sea_water

The magnitude of an acoustic signal transmitted and received underwater. 

1

Acoustic_signal_correlation_in_sea_water

The degree to which the magnitudes of a collection (ensemble) of acoustic signals from multiple underwater acoustic transceivers relate to each other. It is used as a data quality assessment parameter in ADCP (acoustic doppler current profiler) instruments and is frequently referred to as correlation magnitude.

1

**Comment by JonathanGregory** [comment]
Dear @roy-lowry and @ngalbraith

I like Roy's collection of phrases with definitions. Thanks for explaining correlation magnitude. When you say "correlation" do you mean the correlation coefficient - that is, a *signed* quantity? The word "magnitude" might imply it's not signed, and perhaps is the square of the correlation coefficient. What is it, exactly? Of course, I appreciate that something is probably wrong if the signals are negatively correlated!

In answer to Nan's question, Yes, I was proposing that multibeam_acoustic_doppler_velocity_sensor_in_sea_water could appear in all of them, instead of mentioning ADCP. Thus, I would also delete sea_water from Roy's phrases, because it would be redundant, as you say.

I agree with Nan that measurements of different beams should have the same standard name if they're the same quantity. The beam number should be a coordinate variable of some kind.

Jonathan

**Comment by roy-lowry** [comment]
Dear Jonathan,

All I know about correlation magnitude is that it is a data quality descriptor that increases in value as the data get better (signal to noise ratio increases) up to a maximum of 128 based on measuring the consistency between the beams during the ensemble. The definition Hana gave at the start of this thread is from the documentation provided by the manufacturer. They don't give the full derivation algorithm. I'm not sure there's much to be gained from researching it further. Might it be worth adding a statement to the description that it's a number that increases with increasing data quality?

I don't have any problem with losing the 'in_sea_water' as you suggest. I would also remove the references to 'underwater' I put in the descriptions to correspond.

I thought you would prefer one standard name to cover all beams. I now totally agree after learning from Nan about the possibility of having beam number as a dimension.

**Comment by JonathanGregory** [comment]
Dear Roy

Ah, I see. That's helpful - thanks. Calling it "correlation" implies (to me) that it's the statistical quantity of that name. To avoid that misapprehension, I think the standard_name should say something more like your description e.g. beam_consistency_indicator, and the description should say it's often called "correlation magnitude", or something along those lines.

Best wishes

Jonathan

**Comment by roy-lowry** [comment]
Next try.....

indicative_error_in_sea_water_velocity

Sea water velocity is a vector quantity that is the speed at which water travels in a specified direction. The indicative error is an estimate of the quality of a seawater velocity profile measured using an ADCP (acoustic doppler current profiler). It is determined by differencing duplicate error velocity measurements made using different pairs of beams. The parameter is frequently referred to as the error velocity.

m s-1

proportion_of_acceptable_signal_returns

The fraction of a collection (ensemble) of returned signal transmissions that have passed a set of automatic quality control criteria. For an ADCP (acoustic doppler current profiler) the rejection criteria include low correlation, large error velocity and fish detection. The dimensionless proportion is often but not exclusively expressed as a percentage when it is referred to as percent good.

1

acoustic_signal_intensity

The magnitude of an acoustic signal transmitted then received.

1

Acoustic_doppler_current_profiler_beam_consistency_indicator

The degree to which the magnitudes of a collection (ensemble) of acoustic signals from multiple underwater acoustic transceivers relate to each other. It is used as a data quality assessment parameter in ADCP (acoustic doppler current profiler) instruments and is frequently referred to as correlation magnitude. Convention is that the larger the value the higher the signal to noise ratio and therefore the better the quality of the current vector measurements.

1

**Comment by JonathanGregory** [comment]
Dear @roy-lowry 

Thanks for the revised definitions. I would like to repeat my earlier suggestion to describe the sensor generically in all of these standard names. Thus, for the names I would propose

  * indicative_error_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

  * proportion_of_acceptable_signal_returns_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

  * signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

  * beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

Although this is a long phrase, I think it should be fairly self-explanatory, and the same phrase could be used for a sensor in air, if that's requested at some point. What do you think?

Also, I believe the units of the signal intensity are dB, rather than 1.

Best wishes
Jonathan

**Comment by roy-lowry** [comment]
@JonathanGregory You're right about the 'signal intensity' canonical units being dB.

I have no problems with adding 'acoustic_doppler_velocity_profiler' (not sensor - that's indicative of a different instrument measuring currents at a single depth) to indicative_error and beam_consistency_indicator as you suggest as these quantities are ADCP-specific.  

However, signal_intensity and proportion_of_acceptable_signal_returns are equally applicable to other oceanographic instruments such as bathymetric echo sounders and acoustic doppler current meters (different to profilers). I would rather avoid having to set up additional standard names for these instruments in the future. I also left out the 'in_sea_water' reference in these names to make them useful for acoustic instruments used in the atmosphere.

**Comment by JonathanGregory** [comment]
Dear @roy-lowry

Thanks for your reasoning for omitting sea_water from the names, and the type of instrument from two of them. By contrast, the original proposal had both ADCP and sea_water in each of the four names, and I was following that. Maybe we can compromise. Here's some possible reasoning.

If these are standard names, which I think is better than some kind of modifier, then they have to be self-explanatory. A quantity with this name might be the only quantity in a file, not associated with data it describes. For that reason I think it's right to include _in_sea_water in all of them. However, we will make it easier in the future to define sea_water names that could be a pattern for future names with in_air, if those are needed. I appreciate your argument that proportion of returns and signal intensity apply to various kinds of instruments, while the consistency indicator and the indicative error are specific to the ADCP. If you accept this reasoning, taking your point about "sensor", and noting that "instrument" is a word we've used in other standard names, we could call them

  * indicative_error_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water

  * proportion_of_acceptable_signal_returns_from_acoustic_instrument_in_sea_water

  * signal_intensity_from_acoustic_instrument_in_sea_water

  * beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water

Would this be all right?

Cheers

Jonathan

**Comment by roy-lowry** [comment]
@JonathanGregory I think that is a reasonable compromise.

**Comment by japamment** [comment]
Dear Hana, Roy, Jonathan, Nan, @hhourston @roy-lowry @JonathanGregory @ngalbraith

Many thanks for this set of proposals and the interesting discussion. I confess to not having met any of these quantities before, so the detailed explanations are much appreciated! It seems that the discussion is approaching a consensus on the names with no comments being received since July 15th.

To summarize, the current state of the proposal is as follows:
**indicative_error_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water** (Canonical units: m s-1)
'Sea water velocity is a vector quantity that is the speed at which water travels in a specified direction. The indicative error is an estimate of the quality of a seawater velocity profile measured using an ADCP (acoustic doppler current profiler). It is determined by differencing duplicate error velocity measurements made using different pairs of beams. The parameter is frequently referred to as the error velocity.'

The name, units and definition look fine. This name is accepted for inclusion in the standard name table and will be added in the August update.

**proportion_of_acceptable_signal_returns_from_acoustic_instrument_in_sea_water** (Canonical units: 1)
'The phrase "proportion_of_acceptable_signal_returns" means the fraction of a collection (ensemble) of returned signal transmissions that have passed a set of automatic quality control criteria. For an ADCP (acoustic doppler current profiler) the rejection criteria include low correlation, large error velocity and fish detection. The dimensionless proportion is often but not exclusively expressed as a percentage when it is referred to as "percent good." '

I've made some minor style tweaks to the definition text, otherwise this one also looks fine. This name is accepted for inclusion in the standard name table and will be added in the August update.

**beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water** (Canonical units: 1)
'The "beam_consistency_indicator" is the degree to which the magnitudes of a collection (ensemble) of acoustic signals from multiple underwater acoustic transceivers relate to each other. It is used as a data quality assessment parameter in ADCP (acoustic doppler current profiler) instruments and is frequently referred to as correlation magnitude. Convention is that the larger the value, the higher the signal to noise ratio and therefore the better the quality of the current vector measurements.'

The name and units look fine. Again I've made minor style tweaks to the definition. Hana's proposal states that the maximum value for this quantity is 128 and Roy also mentions that figure in one of his comments. It would be useful to include this piece of information if the same scale is always used to determine signal quality for ADCP instruments, so I suggest extending the last sentence of the definition as follows: 'Convention is that the larger the value, the higher the signal to noise ratio and therefore the better the quality of the current vector measurements; the maximum value of the indicator is 128.'

Is that okay? If so, I think this name is also ready to be accepted for publication in the standard name table.

**signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water** (Canonical units: 1 or dB)
'The magnitude of an acoustic signal transmitted then received.'

The name itself looks fine. For the definition I think we could borrow a bit of the language from the existing name acoustic_signal_roundtrip_travel_time_in_sea_water, just to make clear it's the intensity of a reflected signal. I'd suggest:
'The magnitude of an acoustic signal emitted by the instrument toward a reflecting surface and received again by the instrument'.

I have a question about the units. Roy and Jonathan both suggest units of dB and indeed that would be consistent with our existing sound_intensity names. However, Hana's proposal says 'Echo intensity data are output in units proportional to decibels (dB)'. I'm not sure what the 'proportional to' means. If we are going to use units of dB, the definition should state the reference intensity level as is done for the existing names sound_intensity_level_in_air and sound_intensity_level_in_water. Please can anyone help clarify this? (N.B. Units of dB are acceptable because they are defined in the CFunits extension to UDUnits2 and will therefore pass the CF-checker - it's just that we would need to know the reference level).

Best wishes,
Alison

**Comment by roy-lowry** [comment]
@japamment . Hi Alison,

I'm happy with your suggested definition changes 

As to the your units question I'm afraid it's a case of I can't be definitive. The words Hana used are taken from the RDI primer. I read 'proportional to' as meaning that a linear calibration equation (i.e. y = mx +c where m and c are empirical instrument-dependant coefficients) needs to be applied to obtain a value in decibels. However, I don't know to which reference intensity level this refers. I proposed decibels using the logic that a linear calibration can't change dimensions and so the value coming out of the instrument has to have the same dimensions as a measurement in decibels.

**Comment by hhourston** [comment]
Hi @japamment and @roy-lowry,
The raw echo intensity data we get from ADCPs are in units of counts, which is what led me to suggest canonical units of 1. I'm afraid I don't know about the reference intensity level either, though.

**Comment by ngalbraith** [comment]
The ADCP outputs are documentd (by RDI) in SensorML; examples are at at [https://xdomes.tamucc.edu/srr/](https://xdomes.tamucc.edu/srr/)
According to the description of the workhorse long ranger, the intensity is reported in candelas.
<swe:field name="beamIntensity">
<swe:uom code="cd"/>

**Comment by roy-lowry** [comment]
That stretches my credibility a little. I can't see how a measure of light can apply to sound! Possible somebody made a mistake?

**Comment by roy-lowry** [comment]
@hhourston Counts that may be linearly transformed to decibels was what I understood. To my reading of Standard Names rules that makes the canonical unit decibels. However, I could live with with '1'  as it's unclear what that calibration produces in terms of a  reference intensity.

**Comment by ngalbraith** [comment]
Yes, odd!  The same units (cd) is  also being used for beam intensity for the Nortek aquadopp profiler in sensorML, at 
https://xdomes.tamucc.edu/srr/sensorML/urn-nortek-sensor-aquadopp_profiler_400.xml.

I've written to the authors of the two files to find out why that was done.

**Comment by roy-lowry** [comment]
Do you think possibly somebody could have seen 'beam' and assumed 'light beam' rather than sound beam??????

**Comment by japamment** [comment]
Dear Hana, Roy, Nan, @hhourston @roy-lowry  @ngalbraith

Thank you for your replies to my questions. I think we can now go ahead and accept the following name:
**beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water** (Canonical units: 1)
'The "beam_consistency_indicator" is the degree to which the magnitudes of a collection (ensemble) of acoustic signals from multiple underwater acoustic transceivers relate to each other. It is used as a data quality assessment parameter in ADCP (acoustic doppler current profiler) instruments and is frequently referred to as correlation magnitude. Convention is that the larger the value, the higher the signal to noise ratio and therefore the better the quality of the current vector measurements; the maximum value of the indicator is 128.'

This name will be included in the August update to standard names (which is in preparation today).

Regarding the units question for **signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water**, it sounds like it would be safest to use '1' if none of us is sure exactly how the values are derived. I think we are close to consensus on this name, but I'll leave it out of the August update in case any further information comes to light over the next few days. I expect we'll be able to resolve this one in time for the September update.

Best wishes,
Alison

**Comment by ngalbraith** [comment]
Thanks, and yes, I've gotten confirmation from the SensorML portal people, https://xdomes.tamucc.edu/, who got a reply from Nortek, and noted that it is very likely the same for TRDI.  The SensorML representations will be corrected.

The instruments calculate the amplitude/intensity in counts (which can be converted to dB), so '1' will be the appropriate unit.

'For the Aquadopp Profilers we use a dimensionless unit called "counts" to report the amplitude or beam intensity. They are essentially a measure of how much gain we need to apply to the signal - a higher number of counts means we need less amplification of the signal than we would for a return pulse with a lower number of counts. Counts can be converted to dB if required, though this is dependent on the instrument you're using.'

**Comment by japamment** [comment]
Dear Hana, Roy, Nan, @hhourston @roy-lowry @ngalbraith

I'm just getting back to this issue - thank you again for your input. I think we can now say that the following name is accepted for publication in the standard name table:
**signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water** (Canonical units: 1)
'The magnitude of an acoustic signal emitted by the instrument toward a reflecting surface and received again by the instrument.'

The name will be added in the September update, planned for the 14th.

Best wishes,
Alison

**Comment by japamment** [comment]
All the proposals in this issue have been accepted and published in versions 74 and 75 of the standard name table. Closing this issue now.
