### ISSUE TITLE
 Standard names: tidal_sea_surface_height_above_mean_lower_low_water and tidal_sea_surface_height_above_mean_higher_high_water

### ISSUE THREAD

**Issue by jessicaaustin** [cf-convention/discuss#57]
**Proposer's name** Jessica Austin and Micah Wengren and Kathleen Bailey
**Date** 22 June 2020

**- Term** tidal_sea_surface_height_above_mean_lower_low_water
**- Description** "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean lower low water" is the average of the lower low water height of each tidal day observed at a station over the most recent U.S. National Tidal Datum Epoch, which is a 19-year period used to calculate tidal datums. 
**- Units** m

**- Term** tidal_sea_surface_height_above_mean_higher_high_water
**- Description** "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean higher high water" is the average of the higher high water height of each tidal day observed at a station over the most recent National Tidal Datum Epoch, which is a 19-year period used to calculate tidal datums. 
**- Units** m

*Note: Descriptions are based off of definitions on the [CO-OPS Tidal Datums reference page](https://tidesandcurrents.noaa.gov/datum_options.html)*

**Rationale**

* We wish to describe water level data referenced to tidal datums. Specifically, Mean Lower Low Water (MLLW) and Mean Higher High Water (MHHW). MLLW is used in tide predictions and coastal navigation products, and MHHW is commonly used in coastal inundation products
* There are existing standard names that reference tidal datums: 
  * tidal_sea_surface_height_above_lowest_astronomical_tide (LAT)
  * tidal_sea_surface_height_above_mean_sea_level (MSL)
  * tidal_sea_surface_height_above_mean_low_water_springs

**Comment by roy-lowry** [comment]
This is an extension to an established set of Standard Names for water levels wrt datums and the datum descriptions are understandable (to me at least). Consequently, this proposal looks good to me.

**Comment by marceloandrioni** [comment]
Hello, I think it is worth to check the discussion in #10. Also, I believe MLLW and MHHW are datums used in other countries besides the U.S., so I would suggest that
```the most recent U.S. National Tidal Datum Epoch, which is a 19-year period used to calculate tidal datums.```
 could be replaced by
```a relative long time period.```
or something similar.

**Comment by kbailey-noaa** [comment]
Interesting to see the desire for these variables was raised before.  Thanks for pointing us to that.  We had a similar discussion internally, and came to a similar conclusion - determined we only need MLLW and MHHW for now.

Good point about the U.S. verbage.  The 19-year window is specific/purposeful because it covers the metonic cycle, which  includes daily, monthly, annual, and decadal changes in the amplitude of tides over the 19 years.  I only clarify that because I felt 'long time period' wouldn't quite address that detail.  I've updated the descriptions below.  Please let me know what you think.
 
- **Term** tidal_sea_surface_height_above_mean_lower_low_water
- **Description**
"Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. **"Mean lower low water" is the arithmetic mean of the lower low water height of each tidal day observed at a station over a 19-year Metonic cycle.**
- **Units** m

and 

- **Term** tidal_sea_surface_height_above_mean_higher_high_water
- **Description**
"Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. **"Mean higher high water" is the arithmetic mean of the higher high water height of each tidal day observed at a station over a 19-year Metonic cycle.**
- **Units** m

**Comment by aaron-sweeney** [comment]
Unfortunately, the CF precedent has been a bit cavalier with regard to the datum epoch used for the computation of temporal means as reference heights.  I refer you to [Rich Edwing's 2010 presentation on Tidal Datum Standards](https://www.iwr.usace.army.mil/portals/70/docs/projects/02feb10/2_2_10_trilateral_edwing.pdf) (esp. Slide 6, if counting the title slide as Slide 1).  In Slide 6, you can see what years were used to define past datum epochs and the vertical offsets among them for one type of temporal mean quantity: mean sea level.  If you don't account for the change in the datum epoch and the consequent change to the local reference height, you introduce what looks like an undocumented datum shift.  Does this matter to your users?

The current U.S. National Tidal Datum Epoch (NTDE) runs from 1983 to 2001.  Consider that we will soon be transitioning to a new datum epoch.  If you report heights relative to MLLW or MHHW, without specifying which datum epoch was used, how will a user know which datum epoch was used to define the reference height as we move to a new NTDE?  One could imagine a user discovering a datum shift and erroneously attributing that to a problem with the station, or something else. 
 One potential solution is to introduce a required second standard name to accompany the tidal_sea_surface_height_XXXX quantity: tidal_datum_epoch.  So whenever you have a tidal_sea_surface_height_XXXX quantity, you also need a tidal_datum_epoch.  This epoch would be defined by a start year and an end year.

To avoid these issues, when I archive water level data from NOS/CO-OPS at NESDIS/NCEI, I ask for heights relative to the local station datum.  (I believe that Pat Caldwell also uses local station datums for the [Joint Archive for Sea Level](https://uhslc.soest.hawaii.edu/).) I also ask for accompanying metadata that includes the vertical offsets from the local station datum to the various tidal datums, and, importantly, which datum epoch, and the vertical offset between local station datum and a geodetic datum (NAVD88, when applicable).

There's another case to consider here for newer stations that weren't around for the entirety of the NTDE 1983-2001.  If a temporal mean is defined for a newer station, over what years was the reference height derived?

Anyway, give it some thought.

**Comment by marceloandrioni** [comment]
Following @aaron-sweeney suggestion, the datum information could be a [ancillary variable](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#ancillary-data), something like:
```
  float tide_lev(time) ;
    tide_lev:long_name = " Tidal Sea Surface Height" ;
    tide_lev:standard_name = "tidal_sea_surface_height_above_mean_lower_low_water" ;
    tide_lev:units = "m" ;
    tide_lev:ancillary_variables = "tide_lev_datum" ;
  string tide_lev_datum ;
    tide_lev_datum.long_name = "Tide Datum";
```
In this way, the user could use the Datum if he has it or leave the information out if he doesn't. Now the question is if is also necessary to create a new standard_name for the datum epoch (e.g. tidal_datum_epoch) to use it in the ancillary variable.

**Comment by aaron-sweeney** [comment]
Mean Lower Low Water and Mean Higher High Water are **by definition** tidal datums.  A datum is a vertical reference for height.  A **tidal** datum is a (local) vertical reference for height based on a specific characteristic or feature of the (local) tide over a specific 19-year tidal epoch.

If the purpose of a standard name is to allow interoperability between different producers of the same physical quantity, then a term like "tidal_sea_surface_height_above_mean_lower_low_water" is not enough information to disambiguate what vertical reference was used, because the (local) Mean Lower Low Water value will be different from one tidal epoch to the next.  Hence, my suggestion to require a second standard name for the tidal_datum_epoch.

A possible definition might be:
Term: tidal_datum_epoch
Definition: The specific 19-year period over which tide observations are taken and reduced to obtain mean values (e.g., mean lower low water, etc.) for tidal datums.  The epoch is specified by a start and an end year.
Units: None

I found one precedent of the use of standard name pairs in the CF vocabulary (v73), but there may be more: water_surface_height_above_reference_datum and water_surface_reference_datum_altitude.  Note the pairing by cross-referencing the terms in their definitions below:

Term: water_surface_height_above_reference_datum
Definition: 'Water surface height above reference datum' means the height of the upper surface of a body of liquid water, such as sea, lake or river, above an arbitrary reference datum. **The altitude of the datum should be provided in a variable with standard name water_surface_reference_datum_altitude.** (Emphasis added)  The surface called "surface" means the lower boundary of the atmosphere. 

Term: water_surface_reference_datum_altitude
Definition: Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level. **'Water surface reference datum altitude' means the altitude of the arbitrary datum referred to by a quantity with standard name 'water_surface_height_above_reference_datum'**. (Emphasis added)  The surface called "surface" means the lower boundary of the atmosphere.

So, potentially, if one agrees with me for the need to include the start and year as tidal_datum_epoch, then the definition of "tidal_sea_surface_height_above_mean_lower_low_water" ought to include a statement at the end of its definition requiring this, i.e. "The start and end years of the specific 19-year tidal epoch should be provided in a variable with standard name tidal_datum_epoch."

**Comment by DanHollis** [comment]
It strikes me that the general question of how to specify a reference datum is relevant to other standard names. For example, we already have air_pressure_anomaly, air_temperature_anomaly, sea_water_temperature_anomaly and surface_temperature_anomaly. These define “anomaly” as “difference from climatology”, but they provide no indication of how to specify the climatology or even the climatological period.

It’s interesting to see the existing example of paired variables and the proposal for new variables following a similar pattern. It would be useful to hear from others whether this is the preferred/recommended approach for specifying a reference climatology. In particular, to avoid a proliferation of standard names, would a more general name such as datum_epoch, climatology_epoch or reference_climatology_epoch be preferable to tidal_datum_epoch?

**Comment by kbailey-noaa** [comment]
@aaron-sweeney et al - Thanks for the input!  I understand what you're proposing - an ancillary variable that identifies which tidal datum epoch (TDE) applies to the data - and I understand the concern about a data shift for time-series that cross 2 TDEs.  FYI, NOS/CO-OPS tentatively plans to release a new U.S. National TDE at the end of 2024, though that might be delayed. 

"...without specifying which datum epoch was used, how will a user know which datum epoch was used to define the local reference height as we move to a new NTDE? One could imagine a user discovering a datum shift and erroneously attributing that to a problem with the station, or something else."
-- The water level data relative to MLLW / MHHW will always be delivered on the current TDE.  I do agree a TDE update will need to be communicated but I'd suggest something less formal than a new CF standard name/variable attached to these proposed MLLW / MHHW variables.  One thought is to include a comment associated with the MLLW / MHHW variable.  e.g. "Data are delivered on the current Tidal Datum Epoch" and/or "Data prior to [xx/xx/2024] use the superseded 1983-2001 Tidal Datum Epoch" (for the U.S. example). 

I don't disagree the TDE is important, but I think a TDE variable would be more relevant on a vertical datum offset variable that is used for a conversion from water level above station datum to water level above MLLW / MHHW.  In that case, the user would need to know which Epoch that datum offset applies to.  But for what we're proposing, the water level data relative to MLLW/ MHHW data will obviously be already converted, and therefore will always be delivered on the current Epoch.  In our case, the TDE won't serve any purpose other than to explain a potential data shift for some brief time in 2024 (or a date that only occurs once every ~20 yrs) and therefore its relevance is fleeting.

Re: newer stations with shorter time-series, NOS/CO-OPS does a comparison of simultaneous observations with a control tide station to derive the equivalent datum of the TDE.  But our nonfederal partners (whose use cases require less stringent practices) apply a nearby CO-OPS station's datum offset to convert their water level data to MLLW.  I don't believe they do any calculation to come up with their own offset.

**Comment by aaron-sweeney** [comment]
@kbailey-noaa I'm not understanding your point about "some brief time."  If you have a set of heights relative to MLLW as defined from observations collected over the epoch 1960-1978, then in order to express these heights relative to MLLW as defined in a subsequent epoch (e.g. 1983-2001), you have to add/subtract a constant, correct?  This constant isn't just applied during the switchover from one epoch to another, correct?

Let's say for example that for a given station the MLLW 1983-2001 is 5 cm above the MLLW 1960-1978 (a case where local sea level is rising).  Then if you want to convert from any height relative to MLLW 1960-1978 to a height relative to MLLW 1983-2001, you have to add 5 cm.  It doesn't matter when that height was measured; it only matters against which vertical reference level it was measured.  Does this make sense?

**Comment by roy-lowry** [comment]
A concern with the way this discussion is going is backward compatability. Standard Names for sea level have started down the road of including specific datums within the Standard Name. Changing course now will cause problems for existing data sets and make life more difficult for application developers.

I would suggest going back to the original proposal but tightening up the description of the datum by specifically naming the Epoch rather than describing it as 'the most recent'. This would also need reflecting in the Standard Name and possibly additional Standard Names along the lines of:

tidal_sea_surface_height_above_mean_higher_high_water_1960_to_1978
tidal_sea_surface_height_above_mean_higher_high_water_1983_to_2001

**Comment by ukmo-ansaulter** [comment]
@roy-lowry, I'd be more inclined to say that the existing standard names use a specific datum which describes the method by which the datum is derived (e.g. LAT, MLWS) but are non-specific with regard to the epoch. Even something like LAT will vary with the analysis period.

This puts me more in the camp of having some auxiliary data to define the period over which the reference datum is defined rather than including it in the standard name. If there was to be a specific standard name for this, then I think @DanHollis 's comment about using something generic (e.g. datum_epoch) to avoid proliferation would be sensible.

**Comment by DanHollis** [comment]
I agree that it would be good to keep the epoch separate from the method by which the datum is derived. There are existing standard names that reference mean_sea_level, global_average_sea_level and mean_low_water_springs and I think it's right that this information appears in the standard name.

Looking again at the existing example highlighted by @aaron-sweeney, it's worth noting that the second of the pair of standard names (i.e. water_surface_reference_datum_altitude) describes the quantity itself, not just the epoch. Presumably the epoch covered by water_surface_reference_datum_altitude can (should?) be captured through a time coordinate and climatological cell methods.

In other situations it may be sufficient to know just the epoch (without needing the datum values themselves). For example, to compare a data set of temperature anomalies for the UK with a similar one for France it would be important to know that they are both relative to the same climatological reference period (e.g. 1961-1990) but it wouldn't be necessary to have the climatological means themselves.

In this scenario, rather than a separate variable, perhaps the epoch could be indicated via additional scalar coordinate variables in the primary data set e.g. datum_epoch_start and datum_epoch_end. This is analogous (sort of!) to variables such as number_of_days_with_air_temperature_above_threshold, where the threshold has to be provided by a coordinate variable.

**Comment by JonathanGregory** [comment]
I think the most CF-like way to specify the epoch would be with a single scalar time coordinate variable of the data variable, with bounds giving the start and end of the epoch. Of course as well as bounds it has to have a coordinate value, which is a bit arbitrary, but putting it in the middle of the epoch would be sensible; it could even be useful if there was more than one possibility and you wanted to put them in order.

**Comment by kbailey-noaa** [comment]
All - @roy-lowry plans to submit a new github issue to propose a separate standard name for tidal_datum_epoch, to separate the reporting of Epoch duration from this Standard Name proposal.  

The current tidal datum epoch is always applied, regardless of the water level data timestamp.  When a user accesses NOS/CO-OPS water level data above MLLW - even if it's data from 1980 - the current datum (i.e. the MLLW offset that was calculated using the 1983-2001 tidal datum epoch) is applied. 

I've updated definitions below (in bold) to include reference to tidal datum epoch, and also broadened the definition after finding 19 yrs is too constraining (e.g. Australia uses 20 yrs), and there are exceptions requiring a modified epoch.

**Term** tidal_sea_surface_height_above_mean_lower_low_water
**Description**
"Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean lower low water" is the arithmetic mean of the lower low water height of each tidal day observed at a station over a **Tidal Datum Epoch, which is a period of time that is usually greater than 18.6 years to include a full lunar cycle.  Tidal datums in certain regions with anomalous sea level changes may be calculated using a shorter, or modified, Tidal Datum Epoch (e.g. 5 years).**

and

**Term** tidal_sea_surface_height_above_mean_higher_high_water
**Description**
"Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean higher high water" is the arithmetic mean of the higher high water height of each tidal day observed at a station over a **Tidal Datum Epoch, which is a period of time that is usually greater than 18.6 years to include a full lunar cycle.  Tidal datums in certain regions with anomalous sea level changes may be calculated using a shorter, or modified, Tidal Datum Epoch (e.g. 5 years).**

**Comment by feggleton** [comment]
Hi all,

Thanks to @kbailey-noaa, @jessicaaustin and Micah Wengren for this proposal. Good to see lots of discussion around this and some conclusions being agreed on. Thanks to all the comments and for proposing a separate issue for the Epoch discussion, I will look at this shortly. 

I like the final version of these two names, the final sentence definitely makes sense to me and is similar to other definitions of Tidal Datum Epoch and mean higher high water that I have read. I have learnt lots from reading this discussion so thank you for that. Both of these terms are in the editor with the evolution of the definition changes if anyone would like a summary of the changes. It looks like there is mostly agreement here (after discussion) and no comments have been made for a few weeks now. I will obviously now look at the other issue 64 that relates to this. But in terms of these two names, if there are any further comments or discussion to be had, I would encourage people to voice these concerns now. If there are no further comments in the next week or so, then I believe these can be accepted.

**Comment by kbailey-noaa** [comment]
@feggleton We probably need to append a sentence to each of the standard name descriptions, but it depends on the resolution of #64.  Something like "The tidal datum epoch should be provided in a variable with standard name [...]."

**Comment by feggleton** [comment]
@kbailey-noaa Thanks for raising this. I haven't accepted these terms yet due to the epoch discussion. Currently, the definitions here don't rely on that outcome but we need to decide if something is going to be added here or accepted as they are. @japamment how do you think we should go forward with this?

**Comment by japamment** [comment]
@feggleton I agree with @kbailey-noaa that a sentence should be appended to the descriptions of these tidal names to refer to the reference_epoch name, now agreed in [#64](https://github.com/cf-convention/discuss/issues/64). I suggest this should read as follows: 'To specify the tidal datum epoch to which the quantity applies, provide a scalar coordinate variable with standard name reference_epoch'. This is similar to the style of wording in other definitions. With the addition of that sentence I think it is fine to now go ahead and accept these names for inclusion in the standard name table.

**Comment by feggleton** [comment]
Thanks Alison, much appreciated. So we have accepted the following definitions:


Term: tidal_sea_surface_height_above_mean_lower_low_water
Definition: "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean lower low water" is the arithmetic mean of the lower low water height of each tidal day observed at a station over a Tidal Datum Epoch, which is a period of time that is usually greater than 18.6 years to include a full lunar cycle. Tidal datums in certain regions with anomalous sea level changes may be calculated using a shorter, or modified, Tidal Datum Epoch (e.g. 5 years). To specify the tidal datum epoch to which the quantity applies, provide a scalar coordinate variable with standard name reference_epoch.

Term: tidal_sea_surface_height_above_mean_higher_high_water
Definition: "Sea surface height" is a time-varying quantity. "Height_above_X" means the vertical distance above the named surface X. "Mean higher high water" is the arithmetic mean of the higher high water height of each tidal day observed at a station over a Tidal Datum Epoch, which is a period of time that is usually greater than 18.6 years to include a full lunar cycle. Tidal datums in certain regions with anomalous sea level changes may be calculated using a shorter, or modified, Tidal Datum Epoch (e.g. 5 years). To specify the tidal datum epoch to which the quantity applies, provide a scalar coordinate variable with standard name reference_epoch.

**Comment by ethanrd** [comment]
I believe the new issue on grid mappings and tidal datums (#79) that spun out of the reference epoch discussion (#64) could impact the definitions of these standard names. The main discussion point in issue #79 is whether information further defining a tidal datum should be specified in a grid mapping variable (as is done with `sea_surface_height_above_geoid` and the like) or directly in a reference epoch variable.

So the outcome of that discussion could suggest changes to the last sentence of the current definitions.

**Comment by japamment** [comment]
Hi @ethanrd 

Thanks for drawing attention to issue [#79](https://github.com/cf-convention/discuss/issues/79). If I understand correctly, that issue is regarding the vertical datum for the sea_surface_height whereas [#64](https://github.com/cf-convention/discuss/issues/64) was discussing the time period over which the value of the vertical datum is established.

We do have a number of existing sea_surface_height names that specify a vertical datum, including some tidal datums. Certainly I think it is important to discuss how we should store the vertical datum information and it makes sense to continue that conversation in #79. The conclusion of that discussion will then affect both the names proposed in this issue and the existing names. At present, the names proposed here are consistent with our existing approach and they have in fact already been included in a standard name table update which is currently in preparation and has been submitted to the NERC vocab server. Publication will take place overnight tonight and the CF website will be updated tomorrow. If the outcome of #79 is to use a grid mapping or introduce a new standard name for vertical datum information then we will of course update the definitions of all relevant sea_surface_height names to add that advice.

Best wishes,
Alison

**Comment by ethanrd** [comment]
Hi @japamment - I didn't realize these were already accepted. The tidal epoch sentence was just added yesterday so I'm a bit surprised. I always thought standard names had a 3-week "no objection" period (or shorter) similar to that for changes to the CF document. And now that I'm looking I don't see the rules for how new standard names (or changes to existing ones) are accepted. Are the rules spelled out somewhere? (Sorry, I guess I haven't paid close enough attention to the process of new standard names.)

As to a possible definition change depending on the discussion in #79, wouldn't a change to the definition about how the tidal epoch is referenced break any datasets written according to the original definition?

**Comment by ethanrd** [comment]
Hi again - Sorry, one more question.

While looking at how existing standard names reference vertical datum, I noticed that the main difference between the definitions of existing `tidal_sea_surface_height_above_*` standard names and the definitions of the existing `sea_surface_height_above_*` standard names is that the former include the following sentence:

> The tidal component of sea surface height describes the predicted variability of the sea surface due to astronomic forcing (chiefly lunar and solar cycles) and shallow water resonance of tidal components; for example as generated based on harmonic analysis, or resulting from the application of harmonic tidal series as boundary conditions to a numerical tidal model.

Should the definitions agreed on in this issue contain that sentence as well?

**Comment by japamment** [comment]
Hi @ethanrd,

The rules for the standard name process are here: [http://cfconventions.org/standard_name_rules.html](http://cfconventions.org/standard_name_rules.html). When a new standard names GitHub issue is opened, a link to that document is included, but it's true it isn't yet linked from the standard names page on the CF website. I've asked Francesca to add a link as part of publishing the update later today. There is a section near the end of the document which says 'The published vocabularies are updated approximately every 1 - 2 months. The publication date will be announced ahead of time via a github issue. Any names that have been formally accepted will be included in the next update, thus the period between acceptance and publication may vary from a few weeks to as little as a day.' One of the reasons we say this is that we have to agree dates of our updates ahead of time with BODC staff because we need their help to publish the standard names in the NERC Vocabulary Server (NVS2) and to a degree that determines our publication deadlines. We have always (since the earliest days of CF) taken the approach that a standard name proposal is accepted once a discussion has reached consensus and we have never had the 'three week without comment' rule that applies to changes to the Conventions document. We do of course work hard to get standard names 'right' when they are first published, but we can (and often do) add clarifications to definitions at a later date. I should emphasize that any modifications to definition text are done to make the explanation of the name clearer, but **never** to change the meaning of an existing name. This is specifically to avoid the problem of breaking existing datasets.

Regarding your question about the additional tidal sentence for the names proposed in this issue:
> While looking at how existing standard names reference vertical datum, I noticed that the main difference between the definitions of existing `tidal_sea_surface_height_above_*` standard names and the definitions of the existing `sea_surface_height_above_*` standard names is that the former include the following sentence:
> 
> > The tidal component of sea surface height describes the predicted variability of the sea surface due to astronomic forcing (chiefly lunar and solar cycles) and shallow water resonance of tidal components; for example as generated based on harmonic analysis, or resulting from the application of harmonic tidal series as boundary conditions to a numerical tidal model.
> 
> Should the definitions agreed on in this issue contain that sentence as well?

It's a very subtle point, but I think in fact it would be better not to include that sentence for the names proposed here. I think the `tidal_sea_surface_height_above_*` names are describing just one **component** of sea surface height due to current tidal conditions, compared with some longer term tidal average. There will also be other components of sea_surface_height (e.g. waves, storm surges) that are not included in those quantities. The new names in this issue are for **total** sea surface height above some tidal average value. The current definitions do explain what the tidal datums mean so I think that is sufficient and in fact it might cause confusion to add the sentence about tidal sea surface height. (This is my own understanding of the situation so if anyone thinks this is incorrect, please do speak up)!

Best wishes,
Alison

**Comment by feggleton** [comment]
These terms have now been accepted into v76 of the standard name table update.

**Comment by ethanrd** [comment]
Hi Alison - Thanks for the pointer to the Rules for Changing Standard Names page. I’m surprised there isn’t a required comment/objection period for proposed standard names. I think we need to consider adding one, at least for those new standard names that require a longer discussion.

This issue and the `reference_epoch` issue (#64) both were discussed for several months. The `reference_epoch` standard name was accepted just days after there was some indication of agreement. The new `tidal_sea_surface_height_` standard names were also accepted quickly after a final change. The timeline for acceptance was not clear and, for me, came as a bit of a surprise. 

A formal comment/objection period would make this much more transparent. I’m not as concerned with the length of the comment period as I am with having an indication that someone official thinks agreement has been reached and the terms will be accepted if no further objections are raised within some period of time.

**Comment by ethanrd** [comment]
Hi Alison,

> The new names in this issue are for total sea surface height above some tidal average value.

If the existing `tidal_sea_surface_height_*` terms describe the tidal component of the sea surface height and the new names here are for total sea surface height, shouldn’t these new terms drop the `tidal_` prefix and simply be `sea_surface_height_*`.

**Comment by taylor13** [comment]
To me, this seems deserving of consideration.

**Comment by japamment** [comment]
Hi Ethan, Karl,

You're quite right - my apologies. For some reason I had completely overlooked the 'tidal' at the start of these new names. So in fact we **should** add the 'tidal_sea_surface_height' sentence to the definitions, which we can do in the next update. It's additional information/clarification rather than anything that changes the meaning of the names, but it should be included for completeness.

Regarding the standard names process, we have a much faster publication rate than updates to the main conventions document and often people are in a hurry to see their names published. Sometimes we are inundated with large numbers of requests for new names, e.g. when new CMIP experiments are being planned, and keeping up a good throughput is vital. Of course, we need to balance this with the need for thorough discussion and this necessitates a pragmatic approach. For example, as long as a discussion is active and comments are being contributed we allow it to continue and certainly won't cut off the conversation prematurely. On the other hand, sometimes unanimous agreement is reached very quickly, particularly when names are similar to existing ones, and there seems little point in unnecessarily delaying acceptance. If a conversation appears to have finished, yet is missing a formal conclusion, then Francesca or I will usually post to say that the names will be accepted in the next seven days unless any further comments are received. Finally, there is the situation where a conversation peters out but leaves unresolved questions - in that case we try to revive it after a little while so that it can be brought to a conclusion. There is always an element of subjective judgement as to whether a conversation has actually reached consensus, but when we judge this point to have been reached, Francesca or I will always post a comment to formally accept the names. As explained in the rules, once accepted, the names will automatically be included in the next update. Occasionally, formal acceptance suddenly sparks further comment, in which case we can revert the names to 'under discussion' status and allow further time for discussion and we have indeed done this from time to time.

As far as possible, the rules as laid out capture the realities of our approach and do describe how we actually keep the process going from day to day. We could introduce a relatively short post-acceptance period prior to publication if that would make people more comfortable, but it is important to recognize that on occasion it could lead to names 'missing the boat' for the next update, then having to wait another 1- 2 months before appearing in the table. Is such a delay acceptable? Regular updates mean that any omissions, such as the missing sentence in the new tidal names definitions, can be addressed relatively quickly. If the community does feel that there should always be a pause between acceptance and publication I would suggest adopting a seven day 'cooling off' period to allow one final opportunity for comment while keeping delays in the process to a minimum.

Best wishes,
Alison

**Comment by ethanrd** [comment]
Hi Alison,

I’m actually wondering now if these should have been `sea_surface_height_*` terms rather than `tidal_sea_surface_height_*`.

From the [first comment](https://github.com/cf-convention/discuss/issues/57#issue-643244687), @jessicaaustin says
> We wish to describe water level data referenced to tidal datums.

If they are wanting to use these with observed sea level data, I don’t think `tidal_sea_surface_height_*` is the correct term.

@jessicaaustin, @kbailey-noaa, and @mwengren - Are these terms for observational data of water levels?

**Comment by kbailey-noaa** [comment]
Much thanks to the community and moderators for pushing this to conclusion.
No objection to adding the missing 'tidal' sentence to the descriptions.  

I'm not following why the term 'tidal' matters w/r/t whether these are water level observation or not.  These names will be applied to tidal water level observations measured at coastal tide gauges.  Also, a precedent for this naming convention has already been set with the other tidal water level names referenced to a vertical tidal datum: 
tidal_sea_surface_height_above_lowest_astronomical_tide (LAT)
tidal_sea_surface_height_above_mean_sea_level (MSL)
tidal_sea_surface_height_above_mean_low_water_springs

The names should remain tidal_sea_surface_height_*

As one of the proposers I'm a bit dismayed that changes are being recommended at this overdue stage.  I saw community consensus/resolution and thought this issue was closed, as the moderators also apparently concluded.  The names are published in v76, so I'm not sure what purpose further discussion within this issue 57 will serve. 
FWIW an additional 3 week delay (or more, considering we'd have had to wait until v77) on top of the 4-month comment period would have been fairly frustrating, esp since we have projects that depend on the approval of these variables.

**Comment by ethanrd** [comment]
@japamment - I started a new issue for discussion of the rules for new standard names (#80). Lets move that part of the discussion there.

**Comment by ethanrd** [comment]
Hi @kbailey-noaa - This issue led to the `reference_epoch` issue (#64) which led to the “tidal epoch / grid mapping” issue (#79). I am not convinced the results of issue #79 shouldn’t, depending on the results, impact the definition of these terms. Both issue #64 and this issue (#57) concluded rather quickly following some indication of agreement on issue #64. This led me to suggest that CF should formalize some final comment period before standard names are accepted (new issue #80).

Believe me, I take no joy in slowing down the acceptance of new CF standard names. I understand how frustrating this can be, I have been frustrated at the pace of CF plenty of times over the years. However, I still believe it is important to give time for discussion after final changes.

**Comment by ethanrd** [comment]
@kbailey-noaa - Regarding the `tidal_` bit of the name -- not being an ocean/coastal person, I am happy with whatever you all decide. I was simply looking at the consistency of existing CF standard names with these terms. The definitions for the three existing `tidal_sea_surface_height_*` standard names and the `non_tidal_elevation_of_sea_surface_height` standard name all talk about components of the sea surface height. For instance,
> The phrase `non_tidal_elevation` describes the contribution to sea surface height variability made by processes other than astronomic forcing of the ocean and shallow water resonance of tidal components.

This makes me think that all the existing terms are specific to models that may handle separately (and output the values separately) the effects of different physical processes on the sea surface height. For observations, it is the total sea surface height being measured, not just one of these components. The existing `sea_surface_height_*` standard names seem like a better precedent to follow for that.

**Comment by ukmo-ansaulter** [comment]
Hi @ethanrd just to confirm that one intended use of the tidal_ part of these names was to enable a degree of separation between tidal predictions (e.g model or harmonic tides) and other contributors to sea-surface height (e.g. a predicted storm surge component, wave set-up).

Thanks everyone for the discussion in this thread and getting it all worked through :-)

**Comment by JonathanGregory** [comment]
In case it helps to clarify, here's what we wrote in a paper (10.1007/s10712-019-09525-z) last year about sea level terminology:

> The tidal height is the vertical distance of the sea surface height due to the predicted tide above a local benchmark or a surface which is fixed with respect to the terrestrial reference frame. Often, this surface is a tidal datum, defined by a extremum of the periodic tide, such as mean lower-low water level.
 
In standard names, we are using `tidal_sea_surface_height` to mean "tidal height" exactly as defined here, and with "sea surface height" included for clarity. It should be applicable equally to observations and models. We also wrote

> The sea surface varies periodically with various frequencies due to tides. It varies also on all timescales due to sea-surface waves, atmospheric pressure, surface flux exchanges (with the atmosphere), river inflow, variability that is internally generated by ocean dynamics, motion of the sea floor and changes in the mass distribution within the ocean and solid Earth

and

> Mean sea level (MSL) is the time-mean of the sea surface. The period for the time-mean must be long enough to eliminate the effects of waves and other meteorologically induced fluctuations. Predicted tidal variations are subtracted if the period is not long enough to remove time-dependent tides, but permanent tides are included in MSL. For a precise definition of MSL, the period of the time-mean should be specified, and it could be described either with or without dependence on the time of year.

Jonathan

**Comment by ethanrd** [comment]
Thanks Andy (@ukmo-ansaulter) and Jonathan (@JonathanGregory) for your comments and your patience.

I’m clearly missing something. I believe you are both saying that the `tidal_sea_surface_height` is the part of the sea-surface height “due to the predicted tide”. What I’m not understanding is, if there are other components that contribute to the sea-surface height, how can `tidal_sea_surface_height` be equally applicable to observations and models? Doesn’t an observed sea-surface height, by definition, include all components?

Anyway, given these terms have already been accepted and others seem happy with them, I am going to stop asking questions. (Here anyway. Perhaps over a beer someday, preferably somewhere with a view of the water.)

**Comment by ukmo-ansaulter** [comment]
@ethanrd a beer sounds like a wonderful idea!

And its always good to ask questions. In closing off this discussion I will completely agree with you that using tidal_sea_surface_height with observations has its flaws if you assume that these are astronomical effects only. Tidal predictions direct from observations will use all contributions. However, an assumption is often made that the astronomical/resonant interaction parts of the sea-surface height and, say storm surge, are independent (they aren't) to the point where the additional contributions are averaged out (also not completely true).

However the important part in the definition of the standard name is "due to the predicted tide". What we are saying here is that we are defining an estimate of sea surface height based on our chosen tidal prediction method (harmonic analysis/model/what my mate down the pub told me last night) which we can then compare to an observed/modelled instantaneous sea surface height - in our case this is done to estimate storm surge. At that point we don't care about what has gone into creating the prediction, simply that the intention of the variable, which is what the standard name is describing, remains the same regardless of the method by which the quantity is derived. The prediction method, if needed to be defined more fully, is most likely a matter for the variable's comment attribute where we can be nice and verbose.

Thirsty now :-), shame its only breakfast time...

**Comment by feggleton** [comment]
Thanks for the further explanations and discussion, everyone. I will close this now as I think all other discussions have been taken outside this issue or have been resolved. Feel free to open new issues if you need to discuss further (or reopen if this shouldn't have been closed).
