### ISSUE TITLE
seeking help constructing standard name for a height difference

### ISSUE THREAD

**Issue by aaron-sweeney** [cf-convention/discuss#6]
Hi,

I am trying to develop a standard name for the observation of distance between a reference point on  a bridge and the instantaneous sea surface below it.  This is a type of measurement performed for the safe navigation of seagoing vessels under bridges.  I've been reviewing the [Guidelines for Construction of CF Standard Names](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html), as well as reviewing the current [CF Standard Name Table](http://cfconventions.org/Data/cf-standard-names/69/build/cf-standard-name-table.html) for examples.  I've found a few standard names that express "difference\_between," but these terms are absent from the Guidelines, hence I am feeling a bit lost.  The Guidelines suggest including the medium ("in\_air") through which the physical quantity is expressed or measured.  I did not find any guidance regarding a temporal qualifier, such as "instantaneous."  Forgive me if I've missed something, as I am rather new at this and simply seeking help.  For posterity's reference, I initiated an ill-fated conversation on this topic July 24, 2019, on the cf-metadata mailing list with the subject "proposal for new standard name: air\_gap."

If I understand the Guidelines and existing standard names well enough, I might propose this: 
"height\_difference\_[in\_air]\_between\_bridge\_reference\_point\_and\_[instantaneous]\_sea\_surface."  I left the words "in\_air" and "instantaneous" in brackets, as I wonder if one or both might be unnecessary.  Could anyone point me in the right direction?  Constructive comments welcome.  I believe a community is only as good as its willingness to help new people.

Thanks for your kind attention.

Cordially,
Aaron

**Comment by roy-lowry** [comment]
Hi Aaron,

Maybe the precedent for your requirement could be sea_surface_height_above_geoid which uses the 'height_above' construct rather than 'height_difference_between'. Something like navigation_hazard_height_above_sea_surface?
--

**Comment by roy-lowry** [comment]
I've no idea why my comment above is in big bold text. It's not intended as emphasis!!

**Comment by aaron-sweeney** [comment]
Thanks, @roy-lowry.  That sounds fine to me: "navigation\_hazard\_height\_above\_sea\_surface."  What should my next step be?  I think I need to declare a canonical unit ("m" or "meter" makes sense) and a long description, correct?

**Comment by roy-lowry** [comment]
Canonical units of metres is a no-brainer. Text for the long description would certainly be helpful. If there are no more comments then your proposal should make the Standard Name list with no further cation required.

**Comment by aaron-sweeney** [comment]
Ok.

Standard Name: navigation\_hazard\_height\_above\_sea\_surface
Canonical Unit: m

Here's a long description for consideration:

"The height above the sea surface of a hazard to navigation (for example, a bridge)."

**Comment by roy-lowry** [comment]
Hi Aaron,

I would suggest changing this to:

'The vertical upwards distance between the sea surface and a hazard to navigation such as a bridge.'

to get around having 'height' in both the Standard Name and its definition.

OK?

**Comment by DocOtak** [comment]
Hi @aaron-sweeney,
Can you expand on what can affect the distance? I think the "instantaneous" was originally proposed because the bridge or whatever the hazard is can move based on loading or other forces?

I guess I'm wondering what the source of the data are. If it was, for example, some distance sensor attached to the bridge looking at the surface of the water, then the measured distance would be affected by anything which would change the height of the bridge (loading, winds, temperature, etc..), and anything that would change the height of the water it is looking at (tides, river flow, waves, ship wakes, etc..).

@roy-lowry if this also applies to internal navigable waterways, such as rivers and lakes, would "sea_surface" still apply?

The US Coast Guard calls this distance a "clearance" in their [bridge permitting process](https://www.dco.uscg.mil/Our-Organization/Assistant-Commandant-for-Prevention-Policy-CG-5P/Marine-Transportation-Systems-CG-5PW/Office-of-Bridge-Programs/Bridge-Guide-Clearances/) and it applies to both vertical and horizontal distances.

**Comment by aaron-sweeney** [comment]
@DocOtak, the source is a downward-looking, microwave radar sensor mounted on the underside of a bridge.  The data are reported at 6-minute intervals.  Changes in the distance are due to all of the things you mention, to a greater or lesser degree.  In many cases, it is the change in instantaneous water level that dominates.

I think the guide clearance you are referring to is a single number, intended as a minimal clearance requirement before the bridge is designed.  

I think the proposed standard name takes some of the ambiguity out of terms such as "clearance" and "air gap."  I suppose "water_surface" would be more generally applicable than "sea_surface."

**Comment by roy-lowry** [comment]
@DocOtak To date freshwater bodies have been mostly off the radar for CF - it is a standard with its roots in atmospheric/oceanic modelling. There have been discussions in the past on whether sea_water_temperature should be applied throughout data sets in estuarine/river systems where salinity varies from 34 to 0. The conclusion was that preservation of sanity required flexibility rather than pedantism in the meaning of sea_water. 

As @aaron-sweeney says water_surface could be used as a salinity neutral term. However, I have some concerns about setting such a precedent here and the can of worms it could open for existing 'sea_water' Standard Names and the data sets labelled using them from places like the Great Lakes. One possible solution could be to change the definition to 'The vertical upwards distance between the water surface and a hazard to navigation such as a bridge. 'sea_water' covers all navigable waterways whether or not the water is saline.' Other opinions on this would be welcome.

I totally agree that 'clearance' is the lowest conceivable value for this measurement for a given hazard.

**Comment by DocOtak** [comment]
Yeah, "Guide Clearance" is the single number and appears to be determined by operational/economic drivers of what should be able to fit places. When digging into that site, it looks like "vertical clearance" is how they usually refer to the concept we are discussing. I like this terminology since it sets you up for related concepts such as "horizontal clearance".  These terms also appear in the [regulations governing bridges](https://www.ecfr.gov/cgi-bin/text-idx?SID=06d00273c56694053b3ecf728f02a80e&mc=true&node=pt33.1.115&rgn=div5). I personally love being able to cite someone else's precedent.

I could find two standard names with "water_surface" not prefixed by "sea_", and it has the description of "The surface called "surface" means the lower boundary of the atmosphere." There are a few names with just the phrase "surface" or sometimes "wrt_surface" and then define the surface in the standard name definition.

A full straw-man:

standard_name: vertical_navigation_clearance_wrt_surface
units: m
defintion:
"Vertical navigation clearance" is a time-varying quantity. The vertical navigation clearance describes the distance between the surface of a navigable waterway and hazard above the waterway such as a bridge. 
The clearance distance is due to all processes which may change either the surface or position of the hazard. The surface called "surface" means the lower boundary of the atmosphere.

**Comment by roy-lowry** [comment]
A comment just to bring this thread to the attention of the CF list now Jeff has turned on the link from GitHub. A quick look last night revealed active participants to Standard Name discussions who are not currently watching the GitHub.

**Comment by DocOtak** [comment]
A comment to say that I'm still interested in seeing this get into the name list somehow. I feel like it is "taking a while" because it is somewhat of a new field/type and we are "precedent setting".

A question for @aaron-sweeney are there other related parameters that might help in setting this up?

**Comment by roy-lowry** [comment]
Dear @DocOtak ,

I think this is a time of transition in CF from the mailman list to GitHub. I don't know if you are taking note but the number of GitHub watchers has increased rapidly over the past few days, including the addition of people whose absence from the watcher list concerned me. Once things have stabilised and I have a little time (family issues dominate this week) I will add a post that will hopefully start driving this discussion to conclusion.

**Comment by DocOtak** [comment]
Thanks @roy-lowry I just don't want @aaron-sweeney to feel like this isn't going anywhere, especially since this is their second ask to get this name in.

**Comment by feggleton** [comment]
Hi all,

Thank you to Aaron for your request and to others for your comments. Apologies for the delay in getting round to commenting on this proposal and yes I agree discussions may start slow due to the transition to GitHub as some people are still moving across. Apologies that there was no conclusive discussion back when air_gap was suggested, hopefully, we can get this name into the December release which is being published on the 10th. 

I just wanted to collate some of the discussions for any further comments so we can start to come to some conclusion. So far we have:

standard_name: navigation_hazard_height_above_sea_surface
units: m
definition: 'The vertical upwards distance between the water surface and a hazard to navigation such as a bridge'

This was agreed by Roy and Aaron I believe. DocOtak also suggested the below, which I believe is still to be commented on:

standard_name: vertical_navigation_clearance_wrt_surface
units: m
definition: "Vertical navigation clearance" is a time-varying quantity. The vertical navigation clearance describes the distance between the surface of a navigable waterway and hazard above the waterway such as a bridge. The clearance distance is due to all processes which may change either the surface or position of the hazard. The surface called "surface" means the lower boundary of the atmosphere.

Thanks.

**Comment by roy-lowry** [comment]
Thanks for you summary Fran,

As I see it there are two issues to resolve in this Standard Name request.

First is the terminology to use for the gap between the hazard and what is underneath it.  I suggested navigation_hazard_height. Andrew's suggestion was vertical_navigation_clearance. I prefer Andrew's. Although it introduces community-specific terminology in the form of 'clearance' - something for which I have received criticism in the past - it avoids any possible uncertainty with'height' which could be confused with a distance with respect to a fixed datum.

Secondly, there is the description of the relationship between the hazard and the location of the object that could potentially hit it. I suggested 'above_sea_surface'. Aaron suggested modifying this to 'above_water_surface'. Andrew came up with 'wrt_surface'. My preference is still 'above_sea_surface', but I could live with 'above_water_surface'. However, I have concerns about 'wrt_surface' as it brings both bridges over land and underwater obstructions into scope which I feel is semantically too broad for a single Standard Name.

**Comment by aaron-sweeney** [comment]
I agree with @roy-lowry's point regarding the second issue he raises that the term 'surface' without defining the medium is too broad.  This type of measurement is only made above a navigable waterway.  

Applying this constraint, the definition proposed by @DocOtak includes a statement that the 'surface means the lower boundary of the atmosphere,' which leaves the medium of the surface undefined (the lower boundary of the atmosphere could be either 'land' or water, where 'land' is also a bit difficult to define as it might be bare earth, top of canopy, or top of built environment).  I would prefer either 'sea_surface' or 'water_surface,' whichever is more consistent with existing convention.

**Comment by DocOtak** [comment]
For reference, I tried to pick the "surface" from [the guidelines](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html#surface).

How about `vertical_navigation_clearance_wrt_waterway_surface`?
Slightly revised definition:
"Vertical navigation clearance" is a time-varying quantity. The vertical navigation clearance describes the distance between the surface of a navigable waterway and hazard above the waterway such as a bridge. The clearance distance is due to all processes which may change either the surface or position of the hazard. The surface called "waterway surface" means the upper boundary of any [part of any] body of water intended for navigation [including liquid water and ice].

The brackets indicating something I'm unsure of: the phrase "part of any" is an attempt to say this applies only to things like ship channels and not other parts of some body of water _not_ intended for navigation. The "including liquid water and ice" phrase is there because my guess is that the sensor would see any ice as "the surface".

The guidelines have the phrase "surface water" when talking about `ground_level`, not as any standard name part, just in the sentence, I couldn't think of a good way to use it though. I think "waterway" might be worth adding since it could constrains the measurements to the parts of the water you care about.

Aside: apparently [landships are a thing](https://en.wikipedia.org/wiki/Landship)

**Comment by roy-lowry** [comment]
Thanks Andrew,

'surface' works best when looking at things from an atmospheric perspective where one doesn't want to specify what is underneath it.  However, my greater concern was with 'wrt', which includes both above and below making it ambiguous, which in a navigation context could be unfortunate. I know you clarify this in your definition, but not everybody reads them.

Thinking from a navigation perspective I like 'waterway' as it is what a seafarer would call it. So I'm happy to accept:

vertical_navigation_clearance_above_waterway_surface

I've tweaked your definition slightly as I see saying what something is to be more important than a statement on possible co-ordinates. OK?

"Vertical navigation clearance" is the vertical distance between the surface of a navigable waterway and a hazard above it such as a bridge. It is a time-varying quantity because the clearance distance is due to all processes that change the position of either the surface or the hazard.  "Waterway surface" means the upper boundary of any body of navigable water, which may be water or ice.

Cheers, Roy.

**Comment by DocOtak** [comment]
@roy-lowry name/def looks good to me... 
@aaron-sweeney think we got this sorted?

**Comment by aaron-sweeney** [comment]
I don't understand the reason to include 'ice' in the definition.  Any marine debris of significant size (ice floes included) may possibly produce spurious readings.  If the waterway is completely ice-covered, it becomes unnavigable (to anything but an icebreaker).  Is it really necessary to specifically call out ice in the definition?

**Comment by roy-lowry** [comment]
I think @DocOtak was thinking along the lines that the Standard Name describes the measurement and the instrument returns a number to be described whether it's water or ice under the bridge. However, I can see the clash with the phrase 'navigable waterway' - icebreakers don't skate on the ice surface - so as far as I'm concerned if the phrase 'which may be water or ice' worries you then it could be left out.

**Comment by feggleton** [comment]
Hi all,

Thank you all for your discussions and comments. Looks like we may have come to some agreement here, below is the most recent agreed term. If everyone is in agreement and there are no more comments regarding this term in the next few days I can accept it and it will go into the next release which is being done on Tuesday! Any issues at all, let me know.

vertical_navigation_clearance_above_waterway_surface

"Vertical navigation clearance" is the vertical distance between the surface of a navigable waterway and a hazard above it such as a bridge. It is a time-varying quantity because the clearance distance is due to all processes that change the position of either the surface or the hazard. "Waterway surface" means the upper boundary of any body of navigable water.”

Thanks, Fran

**Comment by aaron-sweeney** [comment]
Yes, @feggleton, I agree on your latest standard name and definition (and the unit is 'm' or 'meter,' however that is written out in existing conventions).

Thank you very much @roy-lowry, @DocOtak, and @feggleton for your help in steering this ship into port.  :)

**Comment by feggleton** [comment]
These changes have been published in version 70 of the standard name table.

**Comment by graybeal** [comment]
@feggleton I support these changes, but I was surprised to see they were already incorporated. My understanding is that there is a three-week comment period before a 'final' wording is considered accepted. (Because often people are away from the list for a week or two, or additional ideas surface.) Can you help clarify how the process works?

**Comment by japamment** [comment]
Hi @graybeal I think the three week period you mention is the one adopted for changes to the main CF conventions document. For standard names our usual practice has been to accept names once consensus has been achieved among those actively participating in a conversation. The dates for actually publishing standard name table updates are agreed ahead of time with staff at BODC because we need their help to publish the terms in the NERC vocab server. This means that the time between acceptance of a term and publication can vary from a few weeks to only a day or so. Also, the standard name table is quicker and easier to update than the conventions document in the event we do need to change anything - although we try our best to get it right first time :-) .
