### ISSUE TITLE
 Standard names: latent_heat_flux_due_to: evaporation and transpiration

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#68]
**Proposer's names** Beate Geyer and Burkhardt Rockel
**Date** 2020/08/21

_Basing on the variables surface_upward_latent_heat_flux and water_evapotranspiration_flux and their descriptions we would like to propose additional names to include the origin of the latent heat flux: evaporation and transpiration._

-**Term** surface_upward_latent_heat_flux_due_to_evaporation
-**Definition** The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). The surface latent heat flux is the exchange of heat between the surface and the air on account of evaporation (including sublimation). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Evaporation is the conversion of fluid into vapor. It excludes plant transpiration.
-**Units** W m-2

_and_

-**Term** surface_upward_latent_heat_flux_due_to_transpiration
-**Definition** The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). The surface latent heat flux is the exchange of heat between the surface and the air, here on account of transpiration. In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Transpiration is the conversion of fluid into vapor by plants.
-**Units** W m-2

**Comment by feggleton** [comment]
Hi Beate,

Thanks for the proposal of these two terms. I have now added these into the editor (http://cfeditor.ceda.ac.uk/proposals/1). These seem quite straight forward additions to me. We already have different iterations of surface_upward_latent_heat_flux_due_to.... for example, 'surface_upward_latent_heat_flux_due_to_sublimation' and the definitions are in line with those, bar the final line describing the 'due to' process. These both seem fine to me. As normal I would welcome any comments or changes please and I will check back in a couple of days. @japamment thoughts on these?  They were submitted 19 days ago and are simple additions so maybe they could go into the next update?

Thanks

**Comment by japamment** [comment]
Hi Beate, Burkhardt @GeyerB 

Thank you for these proposals - as requested by @feggleton, I have checked the definitions of these names against existing ones for evaporation, transpiration and evapotranspiration as we need to ensure consistency.

I think the first name looks fine with a little rewording of the definition (the first sentence is now similar to the definition of surface_water_evaporation_flux):
**surface_upward_latent_heat_flux_due_to_evaporation** (Canonical units: W m-2)
'The quantity with standard name surface_upward_latent_heat_flux_due_to_evaporation does not include transpiration from vegetation. The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Evaporation is the conversion of liquid or solid into vapor. (The conversion of solid alone into vapor is called "sublimation"). The surface latent heat flux is the exchange of heat between the surface and the air on account of evaporation (including sublimation).'

Our existing definition of transpiration is 'Evaporation is the conversion of liquid or solid into vapor. Transpiration is the process by which water is carried from the roots of plants and evaporates from the stomata. (The conversion of solid alone into vapor is called "sublimation".)' This is taken from the definition of water_evapotranspiration_flux. This makes me think that it would be better not to call the transpiration name a 'surface' flux. The plants are growing upwards from the surface of course, but they will grow to various heights - some will be close to the ground but evaporation from the leaves of tall trees may be taking place tens of metres above the surface. I note that our existing names transpiration_amount and transpiration_flux also make no mention of surface, so my suggestion would be:
**upward_latent_heat_flux_into_air_due_to_transpiration** (Canonical units: W m-2)
' "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Transpiration is the process by which water is carried from the roots of plants and evaporates from the stomata. Latent heat flux due to transpiration is the exchange of heat between plant surfaces and the air due to the evaporation and submlimation of transpired water.'

Do these look okay?

N.B. We should also add the definition of transpiration to the transpiration_amount and transpiration_flux names as currently it is missing.

Best wishes,
Alison

**Comment by japamment** [comment]
Dear Beate, Burkhardt, @GeyerB,

I realized that I missed a couple of sentences from the definition of the second name. It was meant to be:
**upward_latent_heat_flux_into_air_due_to_transpiration** (Canonical units: W m-2)
' "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Transpiration is the process by which water is carried from the roots of plants and evaporates from the stomata. Evaporation is the conversion of liquid or solid into vapor. (The conversion of solid alone into vapor is called "sublimation".) Latent heat flux due to transpiration is the exchange of heat between plant surfaces and air due to the evaporation and sublimation of transpired water.'

Best wishes,
Alison

**Comment by GeyerB** [comment]
Dear Alison,
Taking a private biology lesson today I learned that transpiration has nothing to do with transport of water in the plants.
Transpirations means the transformation process from liquid water to water vapor. The plant cools down during this proccess - so the wording 'Latent heat flux due to transpiration is the exchange of heat between' is not correct enough - it has to be 'Latent heat flux due to transpiration is the exchange of latent heat between...'

All together it ends up as (native speaker English corrections might be necessary again):

**upward_latent_heat_flux_into_air_due_to_transpiration** (Canonical units: W m-2)
' "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Transpiration is the process by which water in plants changes from their stomata into water vapor in the atmosphere. The latent heat flux due to transpiration is the release of latent heat from plant surfaces to the air due to the release of water vapor.'

What do you think about that version?

**Comment by GeyerB** [comment]
Further unintended thinking lead to:
Is the '**upward**' correct?
I would say no. The direction of heat flux is from plant to air - which implies positiv values only.
The air gets energy but she is not clearyly defined above or below the plants to allow the usage of 'upward' or 'downward'.

**Comment by GeyerB** [comment]
Do we have a chance for an agreement?
Best regards,
Beate

**Comment by feggleton** [comment]
So the terms we have are:

surface_upward_latent_heat_flux_due_to_evaporation (Canonical units: W m-2)

'The quantity with standard name surface_upward_latent_heat_flux_due_to_evaporation does not include transpiration from vegetation. The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Evaporation is the conversion of liquid or solid into vapor. (The conversion of solid alone into vapor is called "sublimation"). The surface latent heat flux is the exchange of heat between the surface and the air on account of evaporation (including sublimation).'


upward_latent_heat_flux_into_air_due_to_transpiration (Canonical units: W m-2)
' "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Transpiration is the process by which water in plants changes from their stomata into water vapor in the atmosphere. The latent heat flux due to transpiration is the release of latent heat from plant surfaces to the air due to the release of water vapor.'

@japamment are we happy for these to enter the 7 day review period before being accepted?

**Comment by feggleton** [comment]
Please do comment further if required before acceptance.

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
