### ISSUE TITLE
 Standard names: shallow convection variables

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#69]
**Proposer's names** Beate Geyer and Burkhardt Rocklel
**Date** 2020/08/21

_In atmospheric numerical models non-precipitating cumulus clouds with cloud tops below 3000 m above the surface are treated separately (see: given explanation in AMS glossary: http://glossary.ametsoc.org/wiki/Shallow_convection_parameterization). Therefore, we want to apply for several quantities in this context:
Analogue to mass_fraction_of_convective_cloud_liquid_water_in_air: mass_fraction_of_shallow_convective_cloud_liquid_water_in_air_

-**Term** mass_fraction_of_shallow_convective_cloud_liquid_water_in_air
-**Definition** "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". Shallow convective cloud is nonprecipitating cumulus cloud with cloud tops below 3000 m above the surface that produced by the convection schemes in an atmosphere model. "Cloud liquid water" refers to the liquid phase of cloud water. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.
-**Units** 1

_Analogue to 'convective_cloud_base_altitude': 'shallow_convective_cloud_base_altitude'_ 

-**Term** 'shallow_convective_cloud_base_altitude' 
-**Definition** cloud_base refers to the base of the lowest cloud. Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level. Shallow convective cloud is nonprecipitating cumulus cloud with cloud tops below 3000 m above the surface that produced by the convection schemes in an atmosphere model.
-**Units** m

_Analogue to 'convective_cloud_top_altitude'_ 

-**Term** 'shallow_convective_cloud_top_altitude' 
-**Definition** cloud_top refers to the top of the highest cloud. Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level. Shallow convective cloud is nonprecipitating cumulus cloud with cloud tops below 3000 m above the surface that produced by the convection schemes in an atmosphere model.
-**Units** m

**Comment by BrienenS** [comment]
This looks good to me. I agree on the proposed new terms 'mass_fraction_of_shallow_convective_cloud_liquid_water_in_air', 'shallow_convective_cloud_base_altitude' and 'shallow_convective_cloud_top_altitude'.

**Comment by feggleton** [comment]
Hi @GeyerB 

Thank you for your proposal and to @BrienenS for your support. 

I think the definition for mass_fraction_of_shallow_convective_cloud_liquid_water_in_air looks fine. As you say, it is similar to 'mass_fraction_of_convective_cloud_liquid_water_in_air'. It looks like we do not have a phrase for shallow_convective_cloud as we do not have any terms relating to it. The only thing I can find about shallow_convective is in 'shallow_convection_precipitation_flux' the phrase 'Some atmosphere models differentiate between shallow and deep convection.' Not sure whether it might be necessary to add this in after your proposed phrase for shallow_convective_cloud. I like the phrase you have given for this:

Shallow convective cloud is nonprecipitating cumulus cloud with cloud tops below 3000 m above the surface that produced by the convection schemes in an atmosphere model.

I would just amend it slightly to:

Shallow convective cloud is nonprecipitating cumulus cloud with a cloud top below 3000m above the surface produced by the convection schemes in an atmosphere model. 

The second term looks fine and obviously we will match the shallow convective cloud phrase to both.

**Comment by GeyerB** [comment]
OK, fine with me, thanks!!

**Comment by feggleton** [comment]
Ok great. So we have the following definitions:

Term: mass_fraction_of_shallow_convective_cloud_liquid_water_in_air
Definition: "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". Shallow convective cloud is nonprecipitating cumulus cloud with a cloud top below 3000m above the surface produced by the convection schemes in an atmosphere model. Some atmosphere models differentiate between shallow and deep convection. "Cloud liquid water" refers to the liquid phase of cloud water. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.

Term: shallow_convective_cloud_base_altitude
Definition: The phrase "cloud_base" refers to the base of the lowest cloud. Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level. Shallow convective cloud is nonprecipitating cumulus cloud with a cloud top below 3000m above the surface produced by the convection schemes in an atmosphere model. Some atmosphere models differentiate between shallow and deep convection.

Term: shallow_convective_cloud_top_altitude
Definition: The phrase "cloud_top" refers to the top of the highest cloud. Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level. Shallow convective cloud is nonprecipitating cumulus cloud with a cloud top below 3000m above the surface produced by the convection schemes in an atmosphere model. Some atmosphere models differentiate between shallow and deep convection.

If there are no further comments on these in the next 7 days these can be accepted into the next update.

Thanks

**Comment by feggleton** [comment]
These have now been accepted for the next update. Thanks

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
