### ISSUE TITLE
 Standard names: Tendency_of_mass_fraction_of_convective_cloud_...

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#70]
**Proposer's names** Beate Geyer and Burkhardt Rockel
**Date** 2020/08/21

_Analogue to mass_fraction_of_convective_cloud_liquid_water_in_air we want to apply for the tendency:_

-**Term** Tendency_of_mass_fraction_of_convective_cloud_liquid_water_in_air
-**Definition** "Tendency_of_X" means derivative of X with respect to time. "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". Convective cloud is that produced by the convection schemes in an atmosphere model. "Cloud liquid water" refers to the liquid phase of cloud water. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.
-**Units** s-1

_Analogue to ‘mass_fraction_of_convective_cloud_ice_in_air’ we want to apply for the tendency:_

-**Term** tendency_of_mass_fraction_of_convective_cloud_ice_in_air
-**Definition** Mass fraction is used in the construction mass_fraction_of_X_in_Y, where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). Convective cloud is that produced by the convection schemes in an atmosphere model.
-**Units** s-1

**Comment by Kerkweg** [comment]
Both variables are used in atmosphere modelling and should therefore be introduced.

The variable definition of 'tendency_of_mass_fraction_of_convective_cloud_ice_in_air ' should start as well with
"Tendency_of_X" means derivative of X with respect to time.

**Comment by feggleton** [comment]
Thank you for your proposal. I have now added these two terms to the editor. I have made some small changes to ensure the phrases match those which we already use.

Term: tendency_of_mass_fraction_of_convective_cloud_ice_in_air
Definition: The phrase "tendency_of_X" means derivative of X with respect to time. "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". Convective cloud is that produced by the convection schemes in an atmosphere model.

Term: tendency_of_mass_fraction_of_convective_cloud_liquid_water_in_air
Definition: The phrase "tendency_of_X" means derivative of X with respect to time. "Mass fraction" is used in the construction "mass_fraction_of_X_in_Y", where X is a material constituent of Y. It means the ratio of the mass of X to the mass of Y (including X). A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". Convective cloud is that produced by the convection schemes in an atmosphere model. "Cloud liquid water" refers to the liquid phase of cloud water. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.

I would encourage others to review the terms and ensure all are happy. Thanks

**Comment by rpnaut** [comment]
I am very fine with the proposal and the last modifications of feggleton.

Let us finish the discussion.

**Comment by feggleton** [comment]
Thanks all. If there are no further comments on these in the next 7 days then they can be accepted into the next update.

**Comment by feggleton** [comment]
These terms have now been accepted into the next update. Thanks

**Comment by feggleton** [comment]
These terms have been added to the standard name table v77.
