### ISSUE TITLE
 Standard names: direction_of_surface_downward_stress

### ISSUE THREAD

**Issue by ngalbraith** [cf-convention/discuss#76]
**Proposer's name:** Nan Galbraith
**Date:** Oct 6 2020
**- Term:** direction_of_surface_downward_stress
**- Description:** (something like) The shear stress exerted by the wind on the surface of large bodies of water. The  surface called "surface" means the lower boundary of the atmosphere.  "Downward" indicates a  vector component which is positive when directed downward (negative  upward) 
**- Units:**  degree

This standard name is needed to complement the existing terms surface_downward_eastward_stress, surface_downward_northward_stress, and magnitude_of_surface_downward_stress. 

I'm putting forward "The shear stress exerted by the wind on the surface of large bodies of water" as a strawman, taken from the web, because I don't have a better definition at hand. Whatever we choose to define stress should be added to the definitions of the other 3, which really need to be improved. 

The current definition of magnitude_of_surface_downward_stress is 
'The  surface called "surface" means the lower boundary of the atmosphere.  "magnitude_of_X" means magnitude of a vector X. "Downward" indicates a  vector component which is positive when directed downward (negative  upward). '

Not sure why the text at the top is so bold, sorry about that, I was unable to fix it.

**Comment by JonathanGregory** [comment]
This proposal seems fine to me, except that with windstress there might be the ambiguity about direction that applies to wind, so maybe it would be worth considering `to`/`from_direction_of_surface_downward_stress`.

**Comment by ngalbraith** [comment]
Thank you, Jonathan, this looks good to me.

> This proposal seems fine to me, except that with windstress there might be the ambiguity about direction that applies to wind, so maybe it would be worth considering `to`/`from_direction_of_surface_downward_stress`.

**Comment by ngalbraith** [comment]
This proposal hasn't gotten any comments in more than 4 weeks, and I think it's ready to be adopted. @japamment, can you please confirm? I have some data files ready to go, and would love to start using this standard name. I'm not thrilled with the definition, but at least it contains a little more content than the existing definitions for downward stress vectors.

- Term: to/from_direction_of_surface_downward_stress
- Description: The shear stress exerted by the wind on the surface of large bodies of water. The surface called "surface" means the lower boundary of the atmosphere. "Downward" indicates a vector component which is positive when directed downward (negative upward)
- Units: degree

**Comment by japamment** [comment]
@ngalbraith Apologies for the delay in looking at this proposal. I agree it is a sensible addition and will complement existing names. It seems we are now talking about adding two new names, to_direction_of_surface_downward_stress and from_direction_of_surface_downward_stress.

I agree that the definitions of existing surface downward stress names need to be tidied up as some of them are more comprehensive than others and it would be good to make them all as consistent as possible. As regards the definition of surface downward stress itself, I'd suggest ' "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents.' (This is an amalgamation of a few definitions including the AMS glossary and text used for existing standard names).

Combining this with our usual text for the other phrases would give:
**to_direction_of_surface_downward_stress** (degree)
'The phrase "to_direction" is used in the construction X_to_direction and indicates the direction towards which the vector of X is headed. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward).'

**from_direction_of_surface_downward_stress** (degree)
'The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward).'

Are these okay?

There are 11 existing surface_downward stress names whose definitions should be updated in line with this discussion. Rather than copy them all here, please see the CEDA vocabulary editor for a full listing: [http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=stress&proposerfilter=galbraith&descfilter=&unitfilter=&yearfilter=&commentfilter=&filter+and+display=Filter](http://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=stress&proposerfilter=galbraith&descfilter=&unitfilter=&yearfilter=&commentfilter=&filter+and+display=Filter.)

If you are happy with these changes then I think they can all be accepted in time for the next update, scheduled for 18-19 January.

Best wishes,
Alison

**Comment by ngalbraith** [comment]
Yes, these are great. Thanks very much for following up on these. 

I should point out that there will probably never be a need for the from_direction, since a force, by definition - I think - represents a forward motion. If it's necessary to add the from_ term, I certainly have no objection to it.

Thank you again!

**Comment by japamment** [comment]
Hi Nan,

Okay, many thanks for checking. If there's no real need for the from_ name, I won't add that one for now. The to_ name and updates to the existing definitions are now accepted for publication in the standard name table and will be added in next week's update.

Best wishes,
Alison

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
