### ISSUE TITLE
 Standard names: mass_concentration_of_phaeopigment_in_sea_water

### ISSUE THREAD

**Issue by timvdstap** [cf-convention/discuss#81]
**Tim van der Stap** 
**October 16, 2020** 

I would like to propose a standard name for phaeopigment concentration in sea water. I could not find any in the current CF Convention. If I have overlooked any standard name that accurately represents phaeopigment concentration in sea water, I apologize, and would like to be pointed in the right direction. 

**- Term**: mass_concentration_of_phaeopigments_in_sea_water
**- Description**: Concentration of phaeopigment per unit volume of the water body, where the filtration size or collection method is unspecified (Source: http://vocab.nerc.ac.uk/collection/P01/current/PHAEZZXX/). Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are a group of non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. Phaeopigments contain phaeophytin, which fluoresces in response to excitation light, and phaeophorbide, which is colorless and does not fluoresce (source: https://academic.oup.com/plankt/article/24/11/1221/1505482). Phaeopigment concentration commonly increases during the development phase of marine phytoplankton blooms, and declines in the post bloom stage (source: https://www.sciencedirect.com/science/article/pii/0967063793901018). 
**- Units**: kg m-3

Though typically phaeopigment concentrations are measured in mg m-3 (ug/L), I noticed that the canonical units displayed in CF Conventions for e.g. mass concentration of chlorophyll in sea water is kg m-3, and I think it would be good to remain consistent.

**Comment by roy-lowry** [comment]
Looks straightforward except I would replace phaeopigment by phaeopigments in the name to more accurately reflect that it is a  grouping and not just one pigment.  To  emphasise this I would also replace 'Phaeopigments are non-photosynthetic pigments' by 'Phaeopigments are a grouping of non-photosynthetic pigments' in the description.

**Comment by timvdstap** [comment]
> Looks straightforward except I would replace phaeopigment by phaeopigments in the name to more accurately reflect that it is a grouping and not just one pigment. To emphasise this I would also replace 'Phaeopigments are non-photosynthetic pigments' by 'Phaeopigments are a group of non-photosynthetic pigments' in the description.

Thank you Roy, I've addressed your feedback in the original post.

**Comment by fcarvalhopacheco** [comment]
Hi, we have a long list of almost 75 variables from HOT coming soon. One of them is the one you just proposed. Please take a look at what a put together and let me know if does make sense.

Term HOT: | mass_concentration_of_pheopigments_in_sea_water

Definititon (NERC): | fluorometric assay of acetone extract from particulates on a GF/F filter filtering water previously filtered through a 200um pore filter.

Definititon (HOT): | Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Chlorophylls are the green pigments found in most plants, algae and cyanobacteria; their presence is essential for photosynthesis to take place. There are several different forms of chlorophyll that occur naturally. All contain a chlorin ring (chemical formula C20H16N4) which gives the green pigment and a side chain whose structure varies. The naturally occurring forms of chlorophyll contain between 35 and 55 carbon atoms. Historically chlorophyll a (chl a) has been used as a measure of phytoplankton standing stock. Also, when related to photosynthetic carbon production, the concentration of chl a and distribution in the water column allows one to estimate an index of the efficiency of phytoplankton in harvesting light. Fluorescence is produced by atoms or molecules that, under exited state, return to their state of minimum energy (or ground state) by losing energy in the form of light. The absorption of blue light by chlorophylls and pheopigments produces emission of red light. In a sample, the fraction of light transformed is proportional to the amount of pigment. Hence, by knowing the amount of incident light and by measuring the light emitted at a second wavelength, it is possible to estimate the concentration of these pigments in the sample.The difference in polarity and molecular size between photosynthetic pigments is used to separate these molecules by high-performance liquid chromatography. The integration of the area under a particular peak in absorbance or fluorescence at 436 nm or 640 respectivelly is a measure of the amount of pigment injected in the column. Pigments routinely measured are: chlorophyll a, b and c and their degradation products, fucoxanthin, diadinoxanthin, β-carotene, zexanthin, lutein, alloxanthin, prasino- xanthin 19'-hexanoyloxyfucoxanthin and 19'-butanoyloxyfucoxanthin.

Units: | [ug/l](HOT),[mg m-3](CF)

short_Term: | Pheo(HOT) or Fluor_Phae_GFF-200um (NERC)

NERC link | https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/P01/
   there are many options, so need to be decided ... search for Pheopigments
    
NERC example | http://vocab.nerc.ac.uk/collection/P01/current/SPHAFLPJ/

**Comment by roy-lowry** [comment]
@fcarvalhopacheco I can see some issues being raised by your proposed request. I have a number of comments concerning this example. 

1) There are philosophical differences between P01 and CF Standard Names. Particularly relevant to this case is that Standard Names describe the geophysical variable and not how it was measured, whereas many P01 concepts include methodology details. This means that the mapping in many cases between Standard Name and P01 will be one to many. In order to preserve semantic interoperability between P01 and CF there has been a policy of setting up 'generic' methodology-independent concepts in P01 to provide mapping targets for Standard Names. A significant number have been set up and more can easily be added on request. You will notice that @timvdstap chose the generic phaeopigments concept (PHAEZZXX) whereas you have chosen a specific filtration and analytical protocol. Consequently, I find the original proposal more acceptable than yours.

2) I feel your definition includes too much background information. The original definition tells me what I feel I need to know and is much more likely to be read thoroughly,

3) Standard Names have canonical units reflecting dimensionality so in this case should be Kg m-3. The actual units of measure including appropriate scaling is included as a parameter attribute in the data file.

I suggest that this ticket progresses as proposed and that HOT uses Standard Name as set up. That way we don't delay @timvdstap unnecessarily. 

Further work will obviously be required for the HOT Standard Name requirement. I fear a single ticket for 70+ Standard Names will create discussions of such complexity that moderation will become impossible. I'll have some offline discussions with relevant people to see if we can come up with an effective way forward.

**Comment by fcarvalhopacheco** [comment]
Hi @roy-lowry.

Thank you so much for the comments. We are still building up the terms and I will pass the information to some of the group.

Please let me know if there is a better way to bring our list to the discussion.

Cheers!

**Comment by timvdstap** [comment]
Appreciate your input in this @roy-lowry , very informative, also to propose new standard names in the future!

**Comment by ngalbraith** [comment]
I'm interested to see how this progresses, because we're dealing with similar issues in OceanSITES. Is there a possibility of using a (new) CF standard name to indicate that the variable is something like 'mass_concentration_of_something_in_sea_water', and that 'something' is identified outside the standard name, using a (new) standard attribute that contains both a link to the NERC ID and a human-readable (standardized, but not part of CF) name?

**Comment by roy-lowry** [comment]
@ngalbraith What you're asking is whether we should do the same with chemical species as I added to the Conventions for biological entities. This has been considered but has been rejected because of backward compatibility concerns - there are many 'single species' Standard Names in widespread usage. If you want to revisit this then I suggest you open a separate ticket for the discussion or this single Standard Name request could get blocked for some time!

To answer your specific question. I'd be careful about applications of the 'Alternative labels' They are labels and NOT identifiers. Whilst there are some conventions running through groups of P01 concepts this is far from universal. They are also not unique - I did have a spare moment project to try and eliminate duplicates but retirement came before I finished. They are also managed as labels and so can be changed - only identifiers are set in stone.

**Comment by timvdstap** [comment]
Good afternoon,

I was wondering if someone would be able to give me an update on the progress made to have this term added to the CF convention? Any information would be greatly appreciated, thank you.

Cheers, Tim

**Comment by timvdstap** [comment]
Hi, would it be possible to get an update on the status of this issue? @japamment

**Comment by feggleton** [comment]
Posting the original request to see if we can get this agreed and approved:

 Term: mass_concentration_of_phaeopigments_in_sea_water
- Description: Concentration of phaeopigment per unit volume of the water body, where the filtration size or collection method is unspecified (Source: http://vocab.nerc.ac.uk/collection/P01/current/PHAEZZXX/). Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are a group of non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. Phaeopigments contain phaeophytin, which fluoresces in response to excitation light, and phaeophorbide, which is colorless and does not fluoresce (source: https://academic.oup.com/plankt/article/24/11/1221/1505482). Phaeopigment concentration commonly increases during the development phase of marine phytoplankton blooms, and declines in the post bloom stage (source: https://www.sciencedirect.com/science/article/pii/0967063793901018).
- Units: kg m-3

@roy-lowry are you happy with this term? do we want to change the description format to be similar to what was agreed for the HOT terms such as:

Description: Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/ATPXZZDZ/2/.

**Comment by roy-lowry** [comment]
I would be happier with the description

Concentration of phaeopigment per unit volume of the water body, where the filtration size or collection method is unspecified (equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at [http://vocab.nerc.ac.uk/collection/P01/current/](http://vocab.nerc.ac.uk/collection/P01/current/PHAEZZXX/). Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are a group of non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. Phaeopigments contain phaeophytin, which fluoresces in response to excitation light, and phaeophorbide, which is colorless and does not fluoresce (source: https://academic.oup.com/plankt/article/24/11/1221/1505482). Phaeopigment concentration commonly increases during the development phase of marine phytoplankton blooms, and declines in the post bloom stage (source: https://www.sciencedirect.com/science/article/pii/0967063793901018).

Note this is purely a description syntax harmonisation and so shouldn't be a blocker to moving things forward.

Cheers, Roy.

**Comment by JonathanGregory** [comment]
This proposal looks fine to me. Thanks for moving it foward.

**Comment by feggleton** [comment]
Term: mass_concentration_of_phaeopigments_in_sea_water

Definition: Concentration of phaeopigment per unit volume of the water body, where the filtration size or collection method is unspecified (equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at [http://vocab.nerc.ac.uk/collection/P01/current/](http://vocab.nerc.ac.uk/collection/P01/current/PHAEZZXX/). Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are a group of non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. Phaeopigments contain phaeophytin, which fluoresces in response to excitation light, and phaeophorbide, which is colorless and does not fluoresce (source: https://academic.oup.com/plankt/article/24/11/1221/1505482). Phaeopigment concentration commonly increases during the development phase of marine phytoplankton blooms, and declines in the post bloom stage (source: https://www.sciencedirect.com/science/article/pii/0967063793901018).

Thanks all! @japamment can update this in the cfeditor and check the phrases are correct in relation to existing names. I think if there are no further comments in the next 7 days, this can be accepted.

**Comment by feggleton** [comment]
@japamment These can be accepted now :)

**Comment by japamment** [comment]
This proposal has now been published in version 79 of the standard name table.
