### ISSUE TITLE
 Standard names: Different components of sea surface current

### ISSUE THREAD

**Issue by cderval** [cf-convention/discuss#85]
**Proposer's name** Corinne Derval
**Date** Nov, 13 , 2020

**- Term** : sea_surface_tidal_current_y_velocity
**- Description** A velocity is a vector quantity. "y" indicates a vector component which is positive when directed eastward (negative westward). Tides are the rise and fall of sea levels caused by the combined effects of the gravitational forces exerted by the Moon and the Sun, and the rotation of the Earth. This rise in water level is accompanied by a horizontal movement of water called the tidal current.
**- Units** m s-1

**- Term** : sea_surface_tidal_current_x_velocity
**- Description** A velocity is a vector quantity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). Tides are the rise and fall of sea levels caused by the combined effects of the gravitational forces exerted by the Moon and the Sun, and the rotation of the Earth. This rise in water level is accompanied by a horizontal movement of water called the tidal current.
**- Units** m s-1

**- Term** : sea_surface_total_current_y_velocity
**- Description** A velocity is a vector quantity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). Ocean currents are related to phenomena of different nature and processes, such as density currents, currents raised by the wind, tide, wave propagation, mass flow in estuaries, etc. The term "total" here encompasses several processes simultaneously in order to get as close as possible to reality.
**- Units** m s-1

**- Term** : sea_surface_total_current_x_velocity
**- Description** A velocity is a vector quantity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). Ocean currents are related to phenomena of different nature and processes, such as density currents, currents raised by the wind, tide, wave propagation, mass flow in estuaries, etc. The term "total" here encompasses several processes simultaneously in order to get as close as possible to reality.
**- Units** m s-1

It would be usefull to have these standard names to describe the different components of sea surface current related to waves and tide.

**Comment by roy-lowry** [comment]
There is a precedent for current components due to specified causes - sea_water_x_velocity_due_to_parameterized_mesoscale_eddies - so I would suggest:

surface_sea_water_y_velocity_due_to_tides
surface_sea_water_x_velocity_due_to_tides

The y_velocity descriptions refer to positive eastward. I think this should be positive northward!

I also think it is an established precedent that 'total' is the default such as in sea_water_x_velocity, so I would suggest:

surface_sea_water_y_velocity
surface_sea_water_x_velocity

with an appropriate adjustment to the description e.g. for surface_sea_water_y_velocity

A velocity is a vector quantity. "y" indicates a vector component which is positive when directed northward (negative southward). Ocean currents are related to phenomena of different nature and processes, such as density currents, currents raised by the wind, tide, wave propagation, mass flow in estuaries, etc. This Standard Name refers to the sum of currents of all origins. 

with an appropriate adjustment to the description

**Comment by JonathanGregory** [comment]
I agree with Roy's suggestions.

**Comment by ngalbraith** [comment]
Is it correct to modify the description of surface_sea_water_y_velocity (and x_velocity) by adding
 'This Standard Name refers to the sum of currents of all origins' 
if the term is being used to describe observed sea water velocity? I'm mulling this over - I'm not sure whether it changes the meaning or not. Would it be preferable to use 'may refer to the sum of currents of all origins', or is that putting too fine a point on it?

**Comment by roy-lowry** [comment]
I think the issue here is the word 'sum' being interpreted as a set of measured numbers added together, whereas I was thinking in terms of a set of causes combining together to produce a single phenomenon that is then measured. Would changing the sentence to 'This Standard Name refers to the combination of currents of all origins' be better?

**Comment by JonathanGregory** [comment]
As @roy-lowry said earlier, there's a general pattern with standard names that quantities which aren't qualified as being a constituent of something (with `due_to`, for example) describe the whole of it (sum, net, or whatever).

**Comment by feggleton** [comment]
Hi all, if there everyone is happy with the discussed terms above and there are no further comments in the next 7 days then I think these can be accepted. @cderval are you happy with the above?

**Comment by cderval** [comment]
Hi,
Perfect for me! 
Thanks all,
Corinne

**Comment by feggleton** [comment]
Thanks these can now be accepted @japamment

**Comment by taylor13** [comment]
I think it is inviting vagueness to refer to a "sea surface current" without explaining what we mean by "surface".  I think "surface" should always refer to the interface between two media (usually the atmosphere and the surface below, but sometimes for sea, the interface between the sea and whatever lies above ... e.g., sea ice).  If we follow this precise definition of "surface" then a "surface current" should refer to the water horizontal velocity components at the interface between the sea and the air (or sea ice) above it.  If the "sea surface current" is meant to represent a transport (integrated through some vertical depth near the surface), then we should define a standard name without the "surface" qualifier.  Then the user would need to define a scalar depth coordinate with bounds indicating what depth is considered in computing the transport.

I usually think of a current as a transport, which means it is a vertically integrated quantity.  About the only use I can think of for "sea surface current" (with the restricted definition of "surface) is in computing the surface wind stress.

**Comment by taylor13** [comment]
If it is agreed that this is truly the sea water velocity at the ocean surface (and not a vertically distributed "transport" of water by a "current", then I think the names should be patterned after existing names:

"surface_northward_sea_water_velocity_due_to_tides"
"surface_eastward_sea_water_velocity_due_to_tides"

and the other two already exist:

"surface_northward_sea_water_velocity"
"surface_eastward_sea_water_velocity"

I would note that if the velocity is some measure of current integrated over a layer, then there are the following standard names available (and one would specify a vertical coordinate with bounds to indicate the depth layer containing the current):

"northward_sea_water_velocity_due_to_tides"
"eastward_sea_water_velocity_due_to_tides"
"northward_sea_water_velocity"
"eastward_sea_water_velocity

**Comment by roy-lowry** [comment]
The issue that is starting to emerge here is that the word 'current' has two meanings. As an observational oceanographer the default meaning is the Eulerian current whose velocity is the speed the water is moving in a given direction at a given point in space and time. There was also a processed quantity we dealt with occasionally - a spatiotemporal average of Eulerian currents - that was always clearly labelled the Lagrangian current that was then used to compute transports in units of Sieverts. My current understanding is that this is Karl's default for 'current'. 

Am I correct? If so, I'll give a little time to investigating the implications for existing Standard Names and this proposal.

**Comment by taylor13** [comment]
My understanding is based on a "man on the street" perspective, so shouldn't be taken too seriously.  When I think of a current, I think of things like the "Humboldt Current" or the more generic "western boundary current" and "eastern boundary current", which in my mind refer to the directional flow of a volume of water, not simply the velocity of water at a point.  So, I think it might be better to refer to water velocity at a point as "sea_water_velocity", and possibly avoid the use of "current" altogether.  I would note that I only found one existing standard name that included the string "current": ``dvorak_tropical_cyclone_current_intensity_number``.

Thanks, Roy (aka @roy-lowry ), for giving this some thought.

**Comment by Zelenke** [comment]
@akirincich @brianemery @hroarty @teresaupdyke @rowg @rucool @LorenzoCorgnati This conversation is on standard names for the different components of sea surface currents, and I thought you might be interested as it pertains to high-frequency radar (HFR) measurements of surface currents.  [Climate and Forecast (CF) Metadata Conventions](https://cfconventions.org/) maintains a list of [standard names](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) which defines strings that identify physical quantities.  In the conversation [here](https://github.com/cf-convention/discuss/issues/85), they are discussing a proposition of adding new terms for "sea surface current".  The [HFRNet](https://cordc.ucsd.edu/projects/hfrnet) data assembly center (DAC) aligns data to CF, so I believe this is a pertinent discussion for our community to contribute to.

**Comment by roy-lowry** [comment]
@Zelenke I think the word 'current' was the problem here which is why in the second post in this thread I rephrased the proposal in terms of sea-water velocity which is a synonym for Eulerian current. Karl was thinking in terms of Lagrangian currents and I think now realises the difference. I have experience of radar surface water velocity (aka surface current) measurements going back to the first OSCR system deployed on the Wirral in the 1980s and so understand the requirements which I felt were covered by this proposal as initially accepted before Karl's comments.

**Comment by taylor13** [comment]
I think I've introduced considerable confusion and probably wasted folks time.  I think I read the original proposal only and somehow missed that it had been updated [here](https://github.com/cf-convention/discuss/issues/85#issuecomment-754706178) where "current" was replaced by "velocity".  I apologize.

Regarding the updated proposal, I think there remains small problem of consistency.  I think that to this point x_velocity has only been used with the meaning "A velocity is a vector quantity. "x" indicates a vector component along the grid x-axis, positive with increasing x" (quoting from the definition provided for existing standard names).  So in the [proposed new standard names](https://github.com/cf-convention/discuss/issues/85#issuecomment-754706178) , either the definition should be edited, or the standard names should be different: for example "surface_sea_water_x_velocity_due_to_tides" should be replaced by "surface_eastward_sea_water_velocity_due_to_tides", and similarly for the other new names.

**Comment by roy-lowry** [comment]
The first thing I would say is that this ticket was agreed - effectively published - at the end of April but for some reason the mechanics of the publication process leading to the closure of the ticket was never executed. I see that @JonathanGregory has added an entry on a ticket to rectify this. This has to be done to keep to CF rules thereby protecting anybody taking action on an agreed ticket from having the rug pulled from under them. I was trying to diplomatically damp down the re-ignited discussion, but this doesn't seem to have worked so this formal statement is necessary.

Secondly, my experience of non-georeferenced Standard Names is that they cover two use cases. First, I have come across modelling studies that are spatially uncoupled. Secondly - and more appropriate here - the way we worked up OSCR data was to generate an initial data set with reference to the radar system geometry (x axis was the line along which the aerials were fixed). This was then mapped onto a spatial co-ordinate reference to give velocities relative to compass points. If the 'raw' data are preserved then they need velocities relative to x and y to differentiate them from the spatially referenced data through labelling.

If anyone feels there is a case for not allowing spatially uncoupled Standard Names for vector quantities then a new ticket should opened.

**Comment by taylor13** [comment]
First, I apologize for not having realized this ticket should have been closed.  

If what is proposed is 
I'm not suggesting that names already decided should be retracted.  Currently I find already published (and relevant to this discussion):

**sea_water_x_velocity**: A velocity is a vector quantity. "x" indicates a vector component along the grid x-axis, positive with increasing x.

**sea_water_y_velocity**: A velocity is a vector quantity. "y" indicates a vector component along the grid y-axis, positive with increasing y.

**eastward_sea_water_velocity_due_to_tides**: A velocity is a vector quantity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Due to tides" means due to all astronomical gravity changes which manifest as tides. No distinction is made between different tidal components.

**northward_sea_water_velocity_due_to_tides**: A velocity is a vector quantity. "Northward" indicates a vector component which is positive when directed northward (negative southward). The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Due to tides" means due to all astronomical gravity changes which manifest as tides. No distinction is made between different tidal components.

surface_eastward_sea_water_velocity, surface_northward_sea_water_velocity, eastward_sea_water_velocity, and northward_sea_water_velocity are also all published with definitions consistent with the above.  

My understanding from https://github.com/cf-convention/discuss/issues/85#issuecomment-754706178 above is that the new proposed variables (which have not yet been published but apparently have been approved?) can be found in [https://cfeditor.ceda.ac.uk/proposals/1](https://cfeditor.ceda.ac.uk/proposals/1).  The definitions of surface_sea_water_x_velocity, surface_sea_water_y_velocity, surface_sea_water_x_velocity_due_to_tides, surface_sea_water_y_velocity_due_to_tides found there are inconsistent with variables already published.  For example, the definition proposed for surface_sea_water_x_velocity includes the sentence: ""x" indicates a vector component which is positive when directed eastward (negative westward).", but in the already published definition of sea_water_x_velocity (see above), the statement is: ""x" indicates a vector component along the grid x-axis, positive with increasing x."

I think the already published definition of "x" is correct and the currently proposed definition for the new x_velocity variables is incorrect and inconsistent with already published variables.  Similarly for "y".  Before these (accepted?) variables get published, the definitions should be corrected.

**Comment by feggleton** [comment]
I think these terms were accepted after some discussion but there has not been an update since so the ticket does not get closed until it's in the table. If we need to re-discuss these terms then that's fine.

**Comment by feggleton** [comment]
The 4 terms originally agreed in the ticket have been published but with the correct x and y phrases to be consistent with others. I think the cfeditor hadn't been updated when this secondary discussion happened but I have checked the table and the below is reflected correctly.

Term: surface_sea_water_x_velocity_due_to_tides
Definition: A velocity is a vector quantity. "x" indicates a vector component along the grid x-axis, positive with increasing x. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Tides are the rise and fall of sea levels caused by the combined effects of the gravitational forces exerted by the Moon and the Sun, and the rotation of the Earth. This rise in water level is accompanied by a horizontal movement of water called the tidal current.

Term: surface_sea_water_x_velocity
Definition: A velocity is a vector quantity. "x" indicates a vector component along the grid x-axis, positive with increasing x. Ocean currents are related to phenomena of different nature and processes, such as density currents, currents raised by the wind, tide, wave propagation, mass flow in estuaries, etc. This standard name refers to the sum of currents of all origins.

Term: surface_sea_water_y_velocity
Definition: A velocity is a vector quantity. "y" indicates a vector component along the grid y-axis, positive with increasing y. Ocean currents are related to phenomena of different nature and processes, such as density currents, currents raised by the wind, tide, wave propagation, mass flow in estuaries, etc. This Standard Name refers to the sum of currents of all origins.

Term: surface_sea_water_y_velocity_due_to_tides
Definition: A velocity is a vector quantity. "y" indicates a vector component along the grid y-axis, positive with increasing y. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Tides are the rise and fall of sea levels caused by the combined effects of the gravitational forces exerted by the Moon and the Sun, and the rotation of the Earth. This rise in water level is accompanied by a horizontal movement of water called the tidal current.
