### ISSUE TITLE
 Standard names: wave model ancillary forcing parameters

### ISSUE THREAD

**Issue by ukmo-ansaulter** [cf-convention/discuss#89]
**Proposer's name**  Andy Saulter 
**Date** 21st December 2021

**- Term** temperature_difference_between_sea_water_and_air
**- Description** Sea water temperature is the in situ temperature of the sea water. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.
**- Units** degree

**- Term** sea_surface_wave_variance_spectral_density_attenuation_coefficient_due_to_icebergs
**- Description** The attenuation coefficient is the fractional reduction of sea_surface_wave_variance_spectral_density due to the stated process. Attenuation is the sum of absorption and scattering.
**- Units** None

**- Term** sediment_grain_size
**- Description** Average size of grains (also known as particles) in a sediment sample.
**- Units** m

**- Term** sea_ice_maximum_floe_diameter
**- Description** Sea_ice means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs. An ice floe is a flat expanse of sea ice, generally taken to be less than 10 km across. Ice floe_diameter corresponds to the diameter of a circle with the same area as the ice floe.
**- Units** m

**Comment by JonathanGregory** [comment]
Dear Andy

Thanks for your proposals. I have comments on three of them.

> **- Term** temperature_difference_between_sea_water_and_air
> **- Description** Sea water temperature is the in situ temperature of the sea water. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.
> **- Units** degree

I think that the name itself should specify the where the temperatures apply, since air_temperature and sea_water_temperature are used throughout the atmosphere and ocean, respectively. For the water temperature, do you mean the SST i.e. the bulk temperature rather than the skin, as for atmosphere? If so, I would suggest difference_between_sea_surface_temperature_and_air_temperature. We don't have a standard name for surface air temperature (and I don't think we should revisit that decision) because it we describe it as air_temperature with a vertical coordinate. For consistency your name would also need a vertical coordinate for the air temperature. Also, the canonical unit should be K, or degC.

> **- Term** sediment_grain_size
> **- Description** Average size of grains (also known as particles) in a sediment sample.
> **- Units** m

What sort of sediment do you have in mind - I mean, where in the Earth system?

> **- Term** sea_ice_maximum_floe_diameter
> **- Description** Sea_ice means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs. An ice floe is a flat expanse of sea ice, generally taken to be less than 10 km across. Ice floe_diameter corresponds to the diameter of a circle with the same area as the ice floe.
> **- Units** m

I think sea_ice_floe_diameter would be fine. The maximum can be specified by cell_methods as "area: maximum". You can imagine other statistics being useful too for this quantity.

Best wishes

Jonathan

**Comment by ukmo-ansaulter** [comment]
Thanks @JonathanGregory. Re your comments:

Agree, **difference_between_sea_surface_temperature_and_air_temperature** would be better, and units should be K

The sediment is on the sea-bed (unless the tide is out :-) ), so possibly sea_floor_sediment_grain_size might be a bit more specific and inline with existing names?

Agree, **sea_ice_floe_diameter** with maximum in cell_methods is better.

**Comment by JonathanGregory** [comment]
> The sediment is on the sea-bed (unless the tide is out :-) ), so possibly sea_floor_sediment_grain_size might be a bit more specific and inline with existing names?

Yes, I think that would be perfect. Thanks. A bed without covers is still a bed. :-)

**Comment by roy-lowry** [comment]
Just to voice agreement with @JonathanGregory comments, particularly the addition of 'sea_floor'. Sediment suspended in sea water is another possibility that it is best excluded explicitly.

**Comment by feggleton** [comment]
Thank you for this proposal and thank you both for your comments. I have now added these terms to the editor. To summarise, so far, here's what we have:

Term: sea_ice_floe_diameter
Definition: "Sea ice" means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs. An ice floe is a flat expanse of sea ice, generally taken to be less than 10 km across. ice_floe_diameter corresponds to the diameter of a circle with the same area as the ice floe.

There is another phrase we have, not sure whether it is needed here: "Lateral growth of ice floe" means the accumulation of ice at the extreme edges of the ice area. Let me know and I can add that.

Term: sea_floor_sediment_grain_size
Definition: The average size of grains (also known as particles) in a sediment sample.

Term: difference_between_sea_surface_temperature_and_air_temperature
Definition: Sea water temperature is the in situ temperature of the sea water. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.

I think we already have standard phrases for sea_surface_temperature which may be better placed here instead of the first sentence? 

Sea surface temperature is usually abbreviated as "SST". It is the temperature of sea water near the surface (including the part under sea-ice, if any), not the skin or interface temperature, whose standard names are sea_surface_skin_temperature and surface_temperature, respectively. For the temperature of sea water at a particular depth or layer, a data variable of "sea_water_temperature" with a vertical coordinate axis should be used.

Making the definition: Sea surface temperature is usually abbreviated as "SST". It is the temperature of sea water near the surface (including the part under sea-ice, if any), not the skin or interface temperature, whose standard names are sea_surface_skin_temperature and surface_temperature, respectively. For the temperature of sea water at a particular depth or layer, a data variable of "sea_water_temperature" with a vertical coordinate axis should be used. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.

**Comment by ukmo-ansaulter** [comment]
Thanks @feggleton 

I think the definition for sea_ice_floe_diameter is OK as is, and does not need the lateral growth term description added

The revised definition text for difference_between_sea_surface_temperature_and_air_temperature looks good

**Comment by feggleton** [comment]
Ok so now we have:

Term: sea_ice_floe_diameter
Definition: "Sea ice" means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs. An ice floe is a flat expanse of sea ice, generally taken to be less than 10 km across. ice_floe_diameter corresponds to the diameter of a circle with the same area as the ice floe.

Term: sea_floor_sediment_grain_size
Definition: The average size of grains (also known as particles) in a sediment sample.

Term: difference_between_sea_surface_temperature_and_air_temperature
Definition: Sea surface temperature is usually abbreviated as "SST". It is the temperature of sea water near the surface (including the part under sea-ice, if any), not the skin or interface temperature, whose standard names are sea_surface_skin_temperature and surface_temperature, respectively. For the temperature of sea water at a particular depth or layer, a data variable of "sea_water_temperature" with a vertical coordinate axis should be used. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.

If there are no further comments in the next 7 days then these can be accepted. Thanks

**Comment by feggleton** [comment]
As there have been no further comments on these terms, these can now be accepted into the next update.

**Comment by feggleton** [comment]
These terms have now been added into Version 78, 21 September 2021
